desc "Creates cg atlas tables for neuraceq"
task :create_neuraceq_atlas_tables => :environment do

     create_homic = "CREATE TABLE `cg_pet_neuraceq_roi_atlas_homic_mni_v1` (
  `subjectid` varchar(50) DEFAULT NULL, `enrollment_id` INT(11) DEFAULT NULL, `scan_procedure_id` INT(11) DEFAULT NULL, `reggie_id` varchar(10) DEFAULT NULL, `protocol` varchar(100) DEFAULT NULL, `enumber_only` varchar(30) DEFAULT NULL, `age` FLOAT DEFAULT NULL, `suvr_front_pole_l` FLOAT DEFAULT NULL, `suvr_front_pole_r` FLOAT DEFAULT NULL, `suvr_insular_ctx_l` FLOAT DEFAULT NULL, `suvr_insular_ctx_r` FLOAT DEFAULT NULL, `suvr_sup_front_gy_l` FLOAT DEFAULT NULL, `suvr_sup_front_gy_r` FLOAT DEFAULT NULL, `suvr_mid_front_gy_l` FLOAT DEFAULT NULL, `suvr_mid_front_gy_r` FLOAT DEFAULT NULL, `suvr_inf_front_gy_pars_triangularis_l` FLOAT DEFAULT NULL, `suvr_inf_front_gy_pars_triangularis_r` FLOAT DEFAULT NULL, `suvr_inf_front_gy_pars_opercularis_l` FLOAT DEFAULT NULL, `suvr_inf_front_gy_pars_opercularis_r` FLOAT DEFAULT NULL, `suvr_precentral_gy_l` FLOAT DEFAULT NULL, `suvr_precentral_gy_r` FLOAT DEFAULT NULL, `suvr_temp_pole_l` FLOAT DEFAULT NULL, `suvr_temp_pole_r` FLOAT DEFAULT NULL, `suvr_sup_temp_gy_ant_l` FLOAT DEFAULT NULL, `suvr_sup_temp_gy_ant_r` FLOAT DEFAULT NULL, `suvr_sup_temp_gy_post_l` FLOAT DEFAULT NULL, `suvr_sup_temp_gy_post_r` FLOAT DEFAULT NULL, `suvr_mid_temp_gy_ant_l` FLOAT DEFAULT NULL, `suvr_mid_temp_gy_ant_r` FLOAT DEFAULT NULL, `suvr_mid_temp_gy_post_l` FLOAT DEFAULT NULL, `suvr_mid_temp_gy_post_r` FLOAT DEFAULT NULL, `suvr_mid_temp_gy_temporooccipital_l` FLOAT DEFAULT NULL, `suvr_mid_temp_gy_temporooccipital_r` FLOAT DEFAULT NULL, `suvr_inf_temp_gy_ant_l` FLOAT DEFAULT NULL, `suvr_inf_temp_gy_ant_r` FLOAT DEFAULT NULL, `suvr_inf_temp_gy_post_l` FLOAT DEFAULT NULL, `suvr_inf_temp_gy_post_r` FLOAT DEFAULT NULL, `suvr_inf_temp_gy_temporooccipital_l` FLOAT DEFAULT NULL, `suvr_inf_temp_gy_temporooccipital_r` FLOAT DEFAULT NULL, `suvr_postcentral_gy_l` FLOAT DEFAULT NULL, `suvr_postcentral_gy_r` FLOAT DEFAULT NULL, `suvr_sup_parietal_lobule_l` FLOAT DEFAULT NULL, `suvr_sup_parietal_lobule_r` FLOAT DEFAULT NULL, `suvr_supramarginal_gy_ant_l` FLOAT DEFAULT NULL, `suvr_supramarginal_gy_ant_r` FLOAT DEFAULT NULL, `suvr_supramarginal_gy_post_l` FLOAT DEFAULT NULL, `suvr_supramarginal_gy_post_r` FLOAT DEFAULT NULL, `suvr_angular_gy_l` FLOAT DEFAULT NULL, `suvr_angular_gy_r` FLOAT DEFAULT NULL, `suvr_lat_occ_ctx_sup_l` FLOAT DEFAULT NULL, `suvr_lat_occ_ctx_sup_r` FLOAT DEFAULT NULL, `suvr_lat_occ_ctx_inf_l` FLOAT DEFAULT NULL, `suvr_lat_occ_ctx_inf_r` FLOAT DEFAULT NULL, `suvr_intracalcarine_ctx_l` FLOAT DEFAULT NULL, `suvr_intracalcarine_ctx_r` FLOAT DEFAULT NULL, `suvr_front_medial_ctx_l` FLOAT DEFAULT NULL, `suvr_front_medial_ctx_r` FLOAT DEFAULT NULL, `suvr_juxtapositional_lobule_ctx_l` FLOAT DEFAULT NULL, `suvr_juxtapositional_lobule_ctx_r` FLOAT DEFAULT NULL, `suvr_subcallosal_ctx_l` FLOAT DEFAULT NULL, `suvr_subcallosal_ctx_r` FLOAT DEFAULT NULL, `suvr_paracingulate_gy_l` FLOAT DEFAULT NULL, `suvr_paracingulate_gy_r` FLOAT DEFAULT NULL, `suvr_cingulate_gy_ant_l` FLOAT DEFAULT NULL, `suvr_cingulate_gy_ant_r` FLOAT DEFAULT NULL, `suvr_cingulate_gy_post_l` FLOAT DEFAULT NULL, `suvr_cingulate_gy_post_r` FLOAT DEFAULT NULL, `suvr_precuneous_ctx_l` FLOAT DEFAULT NULL, `suvr_precuneous_ctx_r` FLOAT DEFAULT NULL, `suvr_cuneal_ctx_l` FLOAT DEFAULT NULL, `suvr_cuneal_ctx_r` FLOAT DEFAULT NULL, `suvr_front_orbital_ctx_l` FLOAT DEFAULT NULL, `suvr_front_orbital_ctx_r` FLOAT DEFAULT NULL, `suvr_parahippocampal_gy_ant_l` FLOAT DEFAULT NULL, `suvr_parahippocampal_gy_ant_r` FLOAT DEFAULT NULL, `suvr_parahippocampal_gy_post_l` FLOAT DEFAULT NULL, `suvr_parahippocampal_gy_post_r` FLOAT DEFAULT NULL, `suvr_lingual_gy_l` FLOAT DEFAULT NULL, `suvr_lingual_gy_r` FLOAT DEFAULT NULL, `suvr_temp_fusiform_ctx_ant_l` FLOAT DEFAULT NULL, `suvr_temp_fusiform_ctx_ant_r` FLOAT DEFAULT NULL, `suvr_temp_fusiform_ctx_post_l` FLOAT DEFAULT NULL, `suvr_temp_fusiform_ctx_post_r` FLOAT DEFAULT NULL, `suvr_temp_occ_fusiform_ctx_l` FLOAT DEFAULT NULL, `suvr_temp_occ_fusiform_ctx_r` FLOAT DEFAULT NULL, `suvr_occ_fusiform_gy_l` FLOAT DEFAULT NULL, `suvr_occ_fusiform_gy_r` FLOAT DEFAULT NULL, `suvr_front_operculum_ctx_l` FLOAT DEFAULT NULL, `suvr_front_operculum_ctx_r` FLOAT DEFAULT NULL, `suvr_central_opercular_ctx_l` FLOAT DEFAULT NULL, `suvr_central_opercular_ctx_r` FLOAT DEFAULT NULL, `suvr_parietal_operculum_ctx_l` FLOAT DEFAULT NULL, `suvr_parietal_operculum_ctx_r` FLOAT DEFAULT NULL, `suvr_planum_polare_l` FLOAT DEFAULT NULL, `suvr_planum_polare_r` FLOAT DEFAULT NULL, `suvr_heschls_gy_l` FLOAT DEFAULT NULL, `suvr_heschls_gy_r` FLOAT DEFAULT NULL, `suvr_planum_temporale_l` FLOAT DEFAULT NULL, `suvr_planum_temporale_r` FLOAT DEFAULT NULL, `suvr_supracalcarine_ctx_l` FLOAT DEFAULT NULL, `suvr_supracalcarine_ctx_r` FLOAT DEFAULT NULL, `suvr_occ_pole_l` FLOAT DEFAULT NULL, `suvr_occ_pole_r` FLOAT DEFAULT NULL, `suvr_thalamus_l` FLOAT DEFAULT NULL, `suvr_thalamus_r` FLOAT DEFAULT NULL, `suvr_caudate_l` FLOAT DEFAULT NULL, `suvr_caudate_r` FLOAT DEFAULT NULL, `suvr_putamen_l` FLOAT DEFAULT NULL, `suvr_putamen_r` FLOAT DEFAULT NULL, `suvr_pallidum_l` FLOAT DEFAULT NULL, `suvr_pallidum_r` FLOAT DEFAULT NULL, `suvr_hippocampus_l` FLOAT DEFAULT NULL, `suvr_hippocampus_r` FLOAT DEFAULT NULL, `suvr_amygdala_l` FLOAT DEFAULT NULL, `suvr_amygdala_r` FLOAT DEFAULT NULL, `suvr_accumbens_l` FLOAT DEFAULT NULL, `suvr_accumbens_r` FLOAT DEFAULT NULL, `suvr_cerebellum_gm_l` FLOAT DEFAULT NULL, `suvr_cerebellum_gm_r` FLOAT DEFAULT NULL, `suvr_cerebellum_wm_l` FLOAT DEFAULT NULL, `suvr_cerebellum_wm_r` FLOAT DEFAULT NULL, `suvr_brainstem` FLOAT DEFAULT NULL, `volume_cc_front_pole_l` FLOAT DEFAULT NULL, `volume_cc_front_pole_r` FLOAT DEFAULT NULL, `volume_cc_insular_ctx_l` FLOAT DEFAULT NULL, `volume_cc_insular_ctx_r` FLOAT DEFAULT NULL, `volume_cc_sup_front_gy_l` FLOAT DEFAULT NULL, `volume_cc_sup_front_gy_r` FLOAT DEFAULT NULL, `volume_cc_mid_front_gy_l` FLOAT DEFAULT NULL, `volume_cc_mid_front_gy_r` FLOAT DEFAULT NULL, `volume_cc_inf_front_gy_pars_triangularis_l` FLOAT DEFAULT NULL, `volume_cc_inf_front_gy_pars_triangularis_r` FLOAT DEFAULT NULL, `volume_cc_inf_front_gy_pars_opercularis_l` FLOAT DEFAULT NULL, `volume_cc_inf_front_gy_pars_opercularis_r` FLOAT DEFAULT NULL, `volume_cc_precentral_gy_l` FLOAT DEFAULT NULL, `volume_cc_precentral_gy_r` FLOAT DEFAULT NULL, `volume_cc_temp_pole_l` FLOAT DEFAULT NULL, `volume_cc_temp_pole_r` FLOAT DEFAULT NULL, `volume_cc_sup_temp_gy_ant_l` FLOAT DEFAULT NULL, `volume_cc_sup_temp_gy_ant_r` FLOAT DEFAULT NULL, `volume_cc_sup_temp_gy_post_l` FLOAT DEFAULT NULL, `volume_cc_sup_temp_gy_post_r` FLOAT DEFAULT NULL, `volume_cc_mid_temp_gy_ant_l` FLOAT DEFAULT NULL, `volume_cc_mid_temp_gy_ant_r` FLOAT DEFAULT NULL, `volume_cc_mid_temp_gy_post_l` FLOAT DEFAULT NULL, `volume_cc_mid_temp_gy_post_r` FLOAT DEFAULT NULL, `volume_cc_mid_temp_gy_temporooccipital_l` FLOAT DEFAULT NULL, `volume_cc_mid_temp_gy_temporooccipital_r` FLOAT DEFAULT NULL, `volume_cc_inf_temp_gy_ant_l` FLOAT DEFAULT NULL, `volume_cc_inf_temp_gy_ant_r` FLOAT DEFAULT NULL, `volume_cc_inf_temp_gy_post_l` FLOAT DEFAULT NULL, `volume_cc_inf_temp_gy_post_r` FLOAT DEFAULT NULL, `volume_cc_inf_temp_gy_temporooccipital_l` FLOAT DEFAULT NULL, `volume_cc_inf_temp_gy_temporooccipital_r` FLOAT DEFAULT NULL, `volume_cc_postcentral_gy_l` FLOAT DEFAULT NULL, `volume_cc_postcentral_gy_r` FLOAT DEFAULT NULL, `volume_cc_sup_parietal_lobule_l` FLOAT DEFAULT NULL, `volume_cc_sup_parietal_lobule_r` FLOAT DEFAULT NULL, `volume_cc_supramarginal_gy_ant_l` FLOAT DEFAULT NULL, `volume_cc_supramarginal_gy_ant_r` FLOAT DEFAULT NULL, `volume_cc_supramarginal_gy_post_l` FLOAT DEFAULT NULL, `volume_cc_supramarginal_gy_post_r` FLOAT DEFAULT NULL, `volume_cc_angular_gy_l` FLOAT DEFAULT NULL, `volume_cc_angular_gy_r` FLOAT DEFAULT NULL, `volume_cc_lat_occ_ctx_sup_l` FLOAT DEFAULT NULL, `volume_cc_lat_occ_ctx_sup_r` FLOAT DEFAULT NULL, `volume_cc_lat_occ_ctx_inf_l` FLOAT DEFAULT NULL, `volume_cc_lat_occ_ctx_inf_r` FLOAT DEFAULT NULL, `volume_cc_intracalcarine_ctx_l` FLOAT DEFAULT NULL, `volume_cc_intracalcarine_ctx_r` FLOAT DEFAULT NULL, `volume_cc_front_medial_ctx_l` FLOAT DEFAULT NULL, `volume_cc_front_medial_ctx_r` FLOAT DEFAULT NULL, `volume_cc_juxtapositional_lobule_ctx_l` FLOAT DEFAULT NULL, `volume_cc_juxtapositional_lobule_ctx_r` FLOAT DEFAULT NULL, `volume_cc_subcallosal_ctx_l` FLOAT DEFAULT NULL, `volume_cc_subcallosal_ctx_r` FLOAT DEFAULT NULL, `volume_cc_paracingulate_gy_l` FLOAT DEFAULT NULL, `volume_cc_paracingulate_gy_r` FLOAT DEFAULT NULL, `volume_cc_cingulate_gy_ant_l` FLOAT DEFAULT NULL, `volume_cc_cingulate_gy_ant_r` FLOAT DEFAULT NULL, `volume_cc_cingulate_gy_post_l` FLOAT DEFAULT NULL, `volume_cc_cingulate_gy_post_r` FLOAT DEFAULT NULL, `volume_cc_precuneous_ctx_l` FLOAT DEFAULT NULL, `volume_cc_precuneous_ctx_r` FLOAT DEFAULT NULL, `volume_cc_cuneal_ctx_l` FLOAT DEFAULT NULL, `volume_cc_cuneal_ctx_r` FLOAT DEFAULT NULL, `volume_cc_front_orbital_ctx_l` FLOAT DEFAULT NULL, `volume_cc_front_orbital_ctx_r` FLOAT DEFAULT NULL, `volume_cc_parahippocampal_gy_ant_l` FLOAT DEFAULT NULL, `volume_cc_parahippocampal_gy_ant_r` FLOAT DEFAULT NULL, `volume_cc_parahippocampal_gy_post_l` FLOAT DEFAULT NULL, `volume_cc_parahippocampal_gy_post_r` FLOAT DEFAULT NULL, `volume_cc_lingual_gy_l` FLOAT DEFAULT NULL, `volume_cc_lingual_gy_r` FLOAT DEFAULT NULL, `volume_cc_temp_fusiform_ctx_ant_l` FLOAT DEFAULT NULL, `volume_cc_temp_fusiform_ctx_ant_r` FLOAT DEFAULT NULL, `volume_cc_temp_fusiform_ctx_post_l` FLOAT DEFAULT NULL, `volume_cc_temp_fusiform_ctx_post_r` FLOAT DEFAULT NULL, `volume_cc_temp_occ_fusiform_ctx_l` FLOAT DEFAULT NULL, `volume_cc_temp_occ_fusiform_ctx_r` FLOAT DEFAULT NULL, `volume_cc_occ_fusiform_gy_l` FLOAT DEFAULT NULL, `volume_cc_occ_fusiform_gy_r` FLOAT DEFAULT NULL, `volume_cc_front_operculum_ctx_l` FLOAT DEFAULT NULL, `volume_cc_front_operculum_ctx_r` FLOAT DEFAULT NULL, `volume_cc_central_opercular_ctx_l` FLOAT DEFAULT NULL, `volume_cc_central_opercular_ctx_r` FLOAT DEFAULT NULL, `volume_cc_parietal_operculum_ctx_l` FLOAT DEFAULT NULL, `volume_cc_parietal_operculum_ctx_r` FLOAT DEFAULT NULL, `volume_cc_planum_polare_l` FLOAT DEFAULT NULL, `volume_cc_planum_polare_r` FLOAT DEFAULT NULL, `volume_cc_heschls_gy_l` FLOAT DEFAULT NULL, `volume_cc_heschls_gy_r` FLOAT DEFAULT NULL, `volume_cc_planum_temporale_l` FLOAT DEFAULT NULL, `volume_cc_planum_temporale_r` FLOAT DEFAULT NULL, `volume_cc_supracalcarine_ctx_l` FLOAT DEFAULT NULL, `volume_cc_supracalcarine_ctx_r` FLOAT DEFAULT NULL, `volume_cc_occ_pole_l` FLOAT DEFAULT NULL, `volume_cc_occ_pole_r` FLOAT DEFAULT NULL, `volume_cc_thalamus_l` FLOAT DEFAULT NULL, `volume_cc_thalamus_r` FLOAT DEFAULT NULL, `volume_cc_caudate_l` FLOAT DEFAULT NULL, `volume_cc_caudate_r` FLOAT DEFAULT NULL, `volume_cc_putamen_l` FLOAT DEFAULT NULL, `volume_cc_putamen_r` FLOAT DEFAULT NULL, `volume_cc_pallidum_l` FLOAT DEFAULT NULL, `volume_cc_pallidum_r` FLOAT DEFAULT NULL, `volume_cc_hippocampus_l` FLOAT DEFAULT NULL, `volume_cc_hippocampus_r` FLOAT DEFAULT NULL, `volume_cc_amygdala_l` FLOAT DEFAULT NULL, `volume_cc_amygdala_r` FLOAT DEFAULT NULL, `volume_cc_accumbens_l` FLOAT DEFAULT NULL, `volume_cc_accumbens_r` FLOAT DEFAULT NULL, `volume_cc_cerebellum_gm_l` FLOAT DEFAULT NULL, `volume_cc_cerebellum_gm_r` FLOAT DEFAULT NULL, `volume_cc_cerebellum_wm_l` FLOAT DEFAULT NULL, `volume_cc_cerebellum_wm_r` FLOAT DEFAULT NULL, `volume_cc_brainstem` FLOAT DEFAULT NULL, `general_comment` varchar(2000) DEFAULT NULL, `file_name` varchar(500) DEFAULT NULL, `secondary_key` varchar(10) DEFAULT NULL, `atlas` varchar(500) DEFAULT NULL, `pet_processing_date` VARCHAR(30) DEFAULT NULL, `pet_code_version` varchar(30) DEFAULT NULL, `ecat_file_name` varchar(500) DEFAULT NULL, `original_t1_mri_file_name` varchar(200) DEFAULT NULL, `age_at_appointment` FLOAT DEFAULT NULL, `bias_corrected_t1_mri_file` varchar(200) DEFAULT NULL, `mni_space_t1_mri` varchar(200) DEFAULT NULL, `multispectral_file` varchar(200) DEFAULT NULL, `pet_date_mri_date_diff_days` INT DEFAULT NULL, `mri_processing_date` varchar(30) DEFAULT NULL, `pet_log_file` varchar(200) DEFAULT NULL, `coregistration_reference_file` varchar(200) DEFAULT NULL, `processed_4d_pet_file` varchar(200) DEFAULT NULL, `processed_sum_pet_file` varchar(200) DEFAULT NULL, `processed_suvr_pet_file` varchar(200) DEFAULT NULL, `mni_space_suvr_pet_file` varchar(200) DEFAULT NULL, `pet_analysis_log_file` varchar(200) DEFAULT NULL,
  KEY `ind_cg_pet_neuraceq_roi_atlas_homic_mni_v1` (`enrollment_id`,`scan_procedure_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;"

     create_new_homic = "CREATE TABLE `cg_pet_neuraceq_roi_atlas_homic_mni_v1_new` (
  `subjectid` varchar(50) DEFAULT NULL, `enrollment_id` INT(11) DEFAULT NULL, `scan_procedure_id` INT(11) DEFAULT NULL, `reggie_id` varchar(10) DEFAULT NULL, `protocol` varchar(100) DEFAULT NULL, `enumber_only` varchar(30) DEFAULT NULL, `age` FLOAT DEFAULT NULL, `suvr_front_pole_l` FLOAT DEFAULT NULL, `suvr_front_pole_r` FLOAT DEFAULT NULL, `suvr_insular_ctx_l` FLOAT DEFAULT NULL, `suvr_insular_ctx_r` FLOAT DEFAULT NULL, `suvr_sup_front_gy_l` FLOAT DEFAULT NULL, `suvr_sup_front_gy_r` FLOAT DEFAULT NULL, `suvr_mid_front_gy_l` FLOAT DEFAULT NULL, `suvr_mid_front_gy_r` FLOAT DEFAULT NULL, `suvr_inf_front_gy_pars_triangularis_l` FLOAT DEFAULT NULL, `suvr_inf_front_gy_pars_triangularis_r` FLOAT DEFAULT NULL, `suvr_inf_front_gy_pars_opercularis_l` FLOAT DEFAULT NULL, `suvr_inf_front_gy_pars_opercularis_r` FLOAT DEFAULT NULL, `suvr_precentral_gy_l` FLOAT DEFAULT NULL, `suvr_precentral_gy_r` FLOAT DEFAULT NULL, `suvr_temp_pole_l` FLOAT DEFAULT NULL, `suvr_temp_pole_r` FLOAT DEFAULT NULL, `suvr_sup_temp_gy_ant_l` FLOAT DEFAULT NULL, `suvr_sup_temp_gy_ant_r` FLOAT DEFAULT NULL, `suvr_sup_temp_gy_post_l` FLOAT DEFAULT NULL, `suvr_sup_temp_gy_post_r` FLOAT DEFAULT NULL, `suvr_mid_temp_gy_ant_l` FLOAT DEFAULT NULL, `suvr_mid_temp_gy_ant_r` FLOAT DEFAULT NULL, `suvr_mid_temp_gy_post_l` FLOAT DEFAULT NULL, `suvr_mid_temp_gy_post_r` FLOAT DEFAULT NULL, `suvr_mid_temp_gy_temporooccipital_l` FLOAT DEFAULT NULL, `suvr_mid_temp_gy_temporooccipital_r` FLOAT DEFAULT NULL, `suvr_inf_temp_gy_ant_l` FLOAT DEFAULT NULL, `suvr_inf_temp_gy_ant_r` FLOAT DEFAULT NULL, `suvr_inf_temp_gy_post_l` FLOAT DEFAULT NULL, `suvr_inf_temp_gy_post_r` FLOAT DEFAULT NULL, `suvr_inf_temp_gy_temporooccipital_l` FLOAT DEFAULT NULL, `suvr_inf_temp_gy_temporooccipital_r` FLOAT DEFAULT NULL, `suvr_postcentral_gy_l` FLOAT DEFAULT NULL, `suvr_postcentral_gy_r` FLOAT DEFAULT NULL, `suvr_sup_parietal_lobule_l` FLOAT DEFAULT NULL, `suvr_sup_parietal_lobule_r` FLOAT DEFAULT NULL, `suvr_supramarginal_gy_ant_l` FLOAT DEFAULT NULL, `suvr_supramarginal_gy_ant_r` FLOAT DEFAULT NULL, `suvr_supramarginal_gy_post_l` FLOAT DEFAULT NULL, `suvr_supramarginal_gy_post_r` FLOAT DEFAULT NULL, `suvr_angular_gy_l` FLOAT DEFAULT NULL, `suvr_angular_gy_r` FLOAT DEFAULT NULL, `suvr_lat_occ_ctx_sup_l` FLOAT DEFAULT NULL, `suvr_lat_occ_ctx_sup_r` FLOAT DEFAULT NULL, `suvr_lat_occ_ctx_inf_l` FLOAT DEFAULT NULL, `suvr_lat_occ_ctx_inf_r` FLOAT DEFAULT NULL, `suvr_intracalcarine_ctx_l` FLOAT DEFAULT NULL, `suvr_intracalcarine_ctx_r` FLOAT DEFAULT NULL, `suvr_front_medial_ctx_l` FLOAT DEFAULT NULL, `suvr_front_medial_ctx_r` FLOAT DEFAULT NULL, `suvr_juxtapositional_lobule_ctx_l` FLOAT DEFAULT NULL, `suvr_juxtapositional_lobule_ctx_r` FLOAT DEFAULT NULL, `suvr_subcallosal_ctx_l` FLOAT DEFAULT NULL, `suvr_subcallosal_ctx_r` FLOAT DEFAULT NULL, `suvr_paracingulate_gy_l` FLOAT DEFAULT NULL, `suvr_paracingulate_gy_r` FLOAT DEFAULT NULL, `suvr_cingulate_gy_ant_l` FLOAT DEFAULT NULL, `suvr_cingulate_gy_ant_r` FLOAT DEFAULT NULL, `suvr_cingulate_gy_post_l` FLOAT DEFAULT NULL, `suvr_cingulate_gy_post_r` FLOAT DEFAULT NULL, `suvr_precuneous_ctx_l` FLOAT DEFAULT NULL, `suvr_precuneous_ctx_r` FLOAT DEFAULT NULL, `suvr_cuneal_ctx_l` FLOAT DEFAULT NULL, `suvr_cuneal_ctx_r` FLOAT DEFAULT NULL, `suvr_front_orbital_ctx_l` FLOAT DEFAULT NULL, `suvr_front_orbital_ctx_r` FLOAT DEFAULT NULL, `suvr_parahippocampal_gy_ant_l` FLOAT DEFAULT NULL, `suvr_parahippocampal_gy_ant_r` FLOAT DEFAULT NULL, `suvr_parahippocampal_gy_post_l` FLOAT DEFAULT NULL, `suvr_parahippocampal_gy_post_r` FLOAT DEFAULT NULL, `suvr_lingual_gy_l` FLOAT DEFAULT NULL, `suvr_lingual_gy_r` FLOAT DEFAULT NULL, `suvr_temp_fusiform_ctx_ant_l` FLOAT DEFAULT NULL, `suvr_temp_fusiform_ctx_ant_r` FLOAT DEFAULT NULL, `suvr_temp_fusiform_ctx_post_l` FLOAT DEFAULT NULL, `suvr_temp_fusiform_ctx_post_r` FLOAT DEFAULT NULL, `suvr_temp_occ_fusiform_ctx_l` FLOAT DEFAULT NULL, `suvr_temp_occ_fusiform_ctx_r` FLOAT DEFAULT NULL, `suvr_occ_fusiform_gy_l` FLOAT DEFAULT NULL, `suvr_occ_fusiform_gy_r` FLOAT DEFAULT NULL, `suvr_front_operculum_ctx_l` FLOAT DEFAULT NULL, `suvr_front_operculum_ctx_r` FLOAT DEFAULT NULL, `suvr_central_opercular_ctx_l` FLOAT DEFAULT NULL, `suvr_central_opercular_ctx_r` FLOAT DEFAULT NULL, `suvr_parietal_operculum_ctx_l` FLOAT DEFAULT NULL, `suvr_parietal_operculum_ctx_r` FLOAT DEFAULT NULL, `suvr_planum_polare_l` FLOAT DEFAULT NULL, `suvr_planum_polare_r` FLOAT DEFAULT NULL, `suvr_heschls_gy_l` FLOAT DEFAULT NULL, `suvr_heschls_gy_r` FLOAT DEFAULT NULL, `suvr_planum_temporale_l` FLOAT DEFAULT NULL, `suvr_planum_temporale_r` FLOAT DEFAULT NULL, `suvr_supracalcarine_ctx_l` FLOAT DEFAULT NULL, `suvr_supracalcarine_ctx_r` FLOAT DEFAULT NULL, `suvr_occ_pole_l` FLOAT DEFAULT NULL, `suvr_occ_pole_r` FLOAT DEFAULT NULL, `suvr_thalamus_l` FLOAT DEFAULT NULL, `suvr_thalamus_r` FLOAT DEFAULT NULL, `suvr_caudate_l` FLOAT DEFAULT NULL, `suvr_caudate_r` FLOAT DEFAULT NULL, `suvr_putamen_l` FLOAT DEFAULT NULL, `suvr_putamen_r` FLOAT DEFAULT NULL, `suvr_pallidum_l` FLOAT DEFAULT NULL, `suvr_pallidum_r` FLOAT DEFAULT NULL, `suvr_hippocampus_l` FLOAT DEFAULT NULL, `suvr_hippocampus_r` FLOAT DEFAULT NULL, `suvr_amygdala_l` FLOAT DEFAULT NULL, `suvr_amygdala_r` FLOAT DEFAULT NULL, `suvr_accumbens_l` FLOAT DEFAULT NULL, `suvr_accumbens_r` FLOAT DEFAULT NULL, `suvr_cerebellum_gm_l` FLOAT DEFAULT NULL, `suvr_cerebellum_gm_r` FLOAT DEFAULT NULL, `suvr_cerebellum_wm_l` FLOAT DEFAULT NULL, `suvr_cerebellum_wm_r` FLOAT DEFAULT NULL, `suvr_brainstem` FLOAT DEFAULT NULL, `volume_cc_front_pole_l` FLOAT DEFAULT NULL, `volume_cc_front_pole_r` FLOAT DEFAULT NULL, `volume_cc_insular_ctx_l` FLOAT DEFAULT NULL, `volume_cc_insular_ctx_r` FLOAT DEFAULT NULL, `volume_cc_sup_front_gy_l` FLOAT DEFAULT NULL, `volume_cc_sup_front_gy_r` FLOAT DEFAULT NULL, `volume_cc_mid_front_gy_l` FLOAT DEFAULT NULL, `volume_cc_mid_front_gy_r` FLOAT DEFAULT NULL, `volume_cc_inf_front_gy_pars_triangularis_l` FLOAT DEFAULT NULL, `volume_cc_inf_front_gy_pars_triangularis_r` FLOAT DEFAULT NULL, `volume_cc_inf_front_gy_pars_opercularis_l` FLOAT DEFAULT NULL, `volume_cc_inf_front_gy_pars_opercularis_r` FLOAT DEFAULT NULL, `volume_cc_precentral_gy_l` FLOAT DEFAULT NULL, `volume_cc_precentral_gy_r` FLOAT DEFAULT NULL, `volume_cc_temp_pole_l` FLOAT DEFAULT NULL, `volume_cc_temp_pole_r` FLOAT DEFAULT NULL, `volume_cc_sup_temp_gy_ant_l` FLOAT DEFAULT NULL, `volume_cc_sup_temp_gy_ant_r` FLOAT DEFAULT NULL, `volume_cc_sup_temp_gy_post_l` FLOAT DEFAULT NULL, `volume_cc_sup_temp_gy_post_r` FLOAT DEFAULT NULL, `volume_cc_mid_temp_gy_ant_l` FLOAT DEFAULT NULL, `volume_cc_mid_temp_gy_ant_r` FLOAT DEFAULT NULL, `volume_cc_mid_temp_gy_post_l` FLOAT DEFAULT NULL, `volume_cc_mid_temp_gy_post_r` FLOAT DEFAULT NULL, `volume_cc_mid_temp_gy_temporooccipital_l` FLOAT DEFAULT NULL, `volume_cc_mid_temp_gy_temporooccipital_r` FLOAT DEFAULT NULL, `volume_cc_inf_temp_gy_ant_l` FLOAT DEFAULT NULL, `volume_cc_inf_temp_gy_ant_r` FLOAT DEFAULT NULL, `volume_cc_inf_temp_gy_post_l` FLOAT DEFAULT NULL, `volume_cc_inf_temp_gy_post_r` FLOAT DEFAULT NULL, `volume_cc_inf_temp_gy_temporooccipital_l` FLOAT DEFAULT NULL, `volume_cc_inf_temp_gy_temporooccipital_r` FLOAT DEFAULT NULL, `volume_cc_postcentral_gy_l` FLOAT DEFAULT NULL, `volume_cc_postcentral_gy_r` FLOAT DEFAULT NULL, `volume_cc_sup_parietal_lobule_l` FLOAT DEFAULT NULL, `volume_cc_sup_parietal_lobule_r` FLOAT DEFAULT NULL, `volume_cc_supramarginal_gy_ant_l` FLOAT DEFAULT NULL, `volume_cc_supramarginal_gy_ant_r` FLOAT DEFAULT NULL, `volume_cc_supramarginal_gy_post_l` FLOAT DEFAULT NULL, `volume_cc_supramarginal_gy_post_r` FLOAT DEFAULT NULL, `volume_cc_angular_gy_l` FLOAT DEFAULT NULL, `volume_cc_angular_gy_r` FLOAT DEFAULT NULL, `volume_cc_lat_occ_ctx_sup_l` FLOAT DEFAULT NULL, `volume_cc_lat_occ_ctx_sup_r` FLOAT DEFAULT NULL, `volume_cc_lat_occ_ctx_inf_l` FLOAT DEFAULT NULL, `volume_cc_lat_occ_ctx_inf_r` FLOAT DEFAULT NULL, `volume_cc_intracalcarine_ctx_l` FLOAT DEFAULT NULL, `volume_cc_intracalcarine_ctx_r` FLOAT DEFAULT NULL, `volume_cc_front_medial_ctx_l` FLOAT DEFAULT NULL, `volume_cc_front_medial_ctx_r` FLOAT DEFAULT NULL, `volume_cc_juxtapositional_lobule_ctx_l` FLOAT DEFAULT NULL, `volume_cc_juxtapositional_lobule_ctx_r` FLOAT DEFAULT NULL, `volume_cc_subcallosal_ctx_l` FLOAT DEFAULT NULL, `volume_cc_subcallosal_ctx_r` FLOAT DEFAULT NULL, `volume_cc_paracingulate_gy_l` FLOAT DEFAULT NULL, `volume_cc_paracingulate_gy_r` FLOAT DEFAULT NULL, `volume_cc_cingulate_gy_ant_l` FLOAT DEFAULT NULL, `volume_cc_cingulate_gy_ant_r` FLOAT DEFAULT NULL, `volume_cc_cingulate_gy_post_l` FLOAT DEFAULT NULL, `volume_cc_cingulate_gy_post_r` FLOAT DEFAULT NULL, `volume_cc_precuneous_ctx_l` FLOAT DEFAULT NULL, `volume_cc_precuneous_ctx_r` FLOAT DEFAULT NULL, `volume_cc_cuneal_ctx_l` FLOAT DEFAULT NULL, `volume_cc_cuneal_ctx_r` FLOAT DEFAULT NULL, `volume_cc_front_orbital_ctx_l` FLOAT DEFAULT NULL, `volume_cc_front_orbital_ctx_r` FLOAT DEFAULT NULL, `volume_cc_parahippocampal_gy_ant_l` FLOAT DEFAULT NULL, `volume_cc_parahippocampal_gy_ant_r` FLOAT DEFAULT NULL, `volume_cc_parahippocampal_gy_post_l` FLOAT DEFAULT NULL, `volume_cc_parahippocampal_gy_post_r` FLOAT DEFAULT NULL, `volume_cc_lingual_gy_l` FLOAT DEFAULT NULL, `volume_cc_lingual_gy_r` FLOAT DEFAULT NULL, `volume_cc_temp_fusiform_ctx_ant_l` FLOAT DEFAULT NULL, `volume_cc_temp_fusiform_ctx_ant_r` FLOAT DEFAULT NULL, `volume_cc_temp_fusiform_ctx_post_l` FLOAT DEFAULT NULL, `volume_cc_temp_fusiform_ctx_post_r` FLOAT DEFAULT NULL, `volume_cc_temp_occ_fusiform_ctx_l` FLOAT DEFAULT NULL, `volume_cc_temp_occ_fusiform_ctx_r` FLOAT DEFAULT NULL, `volume_cc_occ_fusiform_gy_l` FLOAT DEFAULT NULL, `volume_cc_occ_fusiform_gy_r` FLOAT DEFAULT NULL, `volume_cc_front_operculum_ctx_l` FLOAT DEFAULT NULL, `volume_cc_front_operculum_ctx_r` FLOAT DEFAULT NULL, `volume_cc_central_opercular_ctx_l` FLOAT DEFAULT NULL, `volume_cc_central_opercular_ctx_r` FLOAT DEFAULT NULL, `volume_cc_parietal_operculum_ctx_l` FLOAT DEFAULT NULL, `volume_cc_parietal_operculum_ctx_r` FLOAT DEFAULT NULL, `volume_cc_planum_polare_l` FLOAT DEFAULT NULL, `volume_cc_planum_polare_r` FLOAT DEFAULT NULL, `volume_cc_heschls_gy_l` FLOAT DEFAULT NULL, `volume_cc_heschls_gy_r` FLOAT DEFAULT NULL, `volume_cc_planum_temporale_l` FLOAT DEFAULT NULL, `volume_cc_planum_temporale_r` FLOAT DEFAULT NULL, `volume_cc_supracalcarine_ctx_l` FLOAT DEFAULT NULL, `volume_cc_supracalcarine_ctx_r` FLOAT DEFAULT NULL, `volume_cc_occ_pole_l` FLOAT DEFAULT NULL, `volume_cc_occ_pole_r` FLOAT DEFAULT NULL, `volume_cc_thalamus_l` FLOAT DEFAULT NULL, `volume_cc_thalamus_r` FLOAT DEFAULT NULL, `volume_cc_caudate_l` FLOAT DEFAULT NULL, `volume_cc_caudate_r` FLOAT DEFAULT NULL, `volume_cc_putamen_l` FLOAT DEFAULT NULL, `volume_cc_putamen_r` FLOAT DEFAULT NULL, `volume_cc_pallidum_l` FLOAT DEFAULT NULL, `volume_cc_pallidum_r` FLOAT DEFAULT NULL, `volume_cc_hippocampus_l` FLOAT DEFAULT NULL, `volume_cc_hippocampus_r` FLOAT DEFAULT NULL, `volume_cc_amygdala_l` FLOAT DEFAULT NULL, `volume_cc_amygdala_r` FLOAT DEFAULT NULL, `volume_cc_accumbens_l` FLOAT DEFAULT NULL, `volume_cc_accumbens_r` FLOAT DEFAULT NULL, `volume_cc_cerebellum_gm_l` FLOAT DEFAULT NULL, `volume_cc_cerebellum_gm_r` FLOAT DEFAULT NULL, `volume_cc_cerebellum_wm_l` FLOAT DEFAULT NULL, `volume_cc_cerebellum_wm_r` FLOAT DEFAULT NULL, `volume_cc_brainstem` FLOAT DEFAULT NULL, `general_comment` varchar(2000) DEFAULT NULL, `file_name` varchar(500) DEFAULT NULL, `secondary_key` varchar(10) DEFAULT NULL, `atlas` varchar(500) DEFAULT NULL, `pet_processing_date` VARCHAR(30) DEFAULT NULL, `pet_code_version` varchar(30) DEFAULT NULL, `ecat_file_name` varchar(500) DEFAULT NULL, `original_t1_mri_file_name` varchar(200) DEFAULT NULL, `age_at_appointment` FLOAT DEFAULT NULL, `bias_corrected_t1_mri_file` varchar(200) DEFAULT NULL, `mni_space_t1_mri` varchar(200) DEFAULT NULL, `multispectral_file` varchar(200) DEFAULT NULL, `pet_date_mri_date_diff_days` INT DEFAULT NULL, `mri_processing_date` varchar(30) DEFAULT NULL, `pet_log_file` varchar(200) DEFAULT NULL, `coregistration_reference_file` varchar(200) DEFAULT NULL, `processed_4d_pet_file` varchar(200) DEFAULT NULL, `processed_sum_pet_file` varchar(200) DEFAULT NULL, `processed_suvr_pet_file` varchar(200) DEFAULT NULL, `mni_space_suvr_pet_file` varchar(200) DEFAULT NULL, `pet_analysis_log_file` varchar(200) DEFAULT NULL,
  KEY `ind_cg_pet_neuraceq_roi_atlas_homic_mni_v1_new` (`enrollment_id`,`scan_procedure_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;"

     create_old_homic = "CREATE TABLE `cg_pet_neuraceq_roi_atlas_homic_mni_v1_old` (
  `subjectid` varchar(50) DEFAULT NULL, `enrollment_id` INT(11) DEFAULT NULL, `scan_procedure_id` INT(11) DEFAULT NULL, `reggie_id` varchar(10) DEFAULT NULL, `protocol` varchar(100) DEFAULT NULL, `enumber_only` varchar(30) DEFAULT NULL, `age` FLOAT DEFAULT NULL, `suvr_front_pole_l` FLOAT DEFAULT NULL, `suvr_front_pole_r` FLOAT DEFAULT NULL, `suvr_insular_ctx_l` FLOAT DEFAULT NULL, `suvr_insular_ctx_r` FLOAT DEFAULT NULL, `suvr_sup_front_gy_l` FLOAT DEFAULT NULL, `suvr_sup_front_gy_r` FLOAT DEFAULT NULL, `suvr_mid_front_gy_l` FLOAT DEFAULT NULL, `suvr_mid_front_gy_r` FLOAT DEFAULT NULL, `suvr_inf_front_gy_pars_triangularis_l` FLOAT DEFAULT NULL, `suvr_inf_front_gy_pars_triangularis_r` FLOAT DEFAULT NULL, `suvr_inf_front_gy_pars_opercularis_l` FLOAT DEFAULT NULL, `suvr_inf_front_gy_pars_opercularis_r` FLOAT DEFAULT NULL, `suvr_precentral_gy_l` FLOAT DEFAULT NULL, `suvr_precentral_gy_r` FLOAT DEFAULT NULL, `suvr_temp_pole_l` FLOAT DEFAULT NULL, `suvr_temp_pole_r` FLOAT DEFAULT NULL, `suvr_sup_temp_gy_ant_l` FLOAT DEFAULT NULL, `suvr_sup_temp_gy_ant_r` FLOAT DEFAULT NULL, `suvr_sup_temp_gy_post_l` FLOAT DEFAULT NULL, `suvr_sup_temp_gy_post_r` FLOAT DEFAULT NULL, `suvr_mid_temp_gy_ant_l` FLOAT DEFAULT NULL, `suvr_mid_temp_gy_ant_r` FLOAT DEFAULT NULL, `suvr_mid_temp_gy_post_l` FLOAT DEFAULT NULL, `suvr_mid_temp_gy_post_r` FLOAT DEFAULT NULL, `suvr_mid_temp_gy_temporooccipital_l` FLOAT DEFAULT NULL, `suvr_mid_temp_gy_temporooccipital_r` FLOAT DEFAULT NULL, `suvr_inf_temp_gy_ant_l` FLOAT DEFAULT NULL, `suvr_inf_temp_gy_ant_r` FLOAT DEFAULT NULL, `suvr_inf_temp_gy_post_l` FLOAT DEFAULT NULL, `suvr_inf_temp_gy_post_r` FLOAT DEFAULT NULL, `suvr_inf_temp_gy_temporooccipital_l` FLOAT DEFAULT NULL, `suvr_inf_temp_gy_temporooccipital_r` FLOAT DEFAULT NULL, `suvr_postcentral_gy_l` FLOAT DEFAULT NULL, `suvr_postcentral_gy_r` FLOAT DEFAULT NULL, `suvr_sup_parietal_lobule_l` FLOAT DEFAULT NULL, `suvr_sup_parietal_lobule_r` FLOAT DEFAULT NULL, `suvr_supramarginal_gy_ant_l` FLOAT DEFAULT NULL, `suvr_supramarginal_gy_ant_r` FLOAT DEFAULT NULL, `suvr_supramarginal_gy_post_l` FLOAT DEFAULT NULL, `suvr_supramarginal_gy_post_r` FLOAT DEFAULT NULL, `suvr_angular_gy_l` FLOAT DEFAULT NULL, `suvr_angular_gy_r` FLOAT DEFAULT NULL, `suvr_lat_occ_ctx_sup_l` FLOAT DEFAULT NULL, `suvr_lat_occ_ctx_sup_r` FLOAT DEFAULT NULL, `suvr_lat_occ_ctx_inf_l` FLOAT DEFAULT NULL, `suvr_lat_occ_ctx_inf_r` FLOAT DEFAULT NULL, `suvr_intracalcarine_ctx_l` FLOAT DEFAULT NULL, `suvr_intracalcarine_ctx_r` FLOAT DEFAULT NULL, `suvr_front_medial_ctx_l` FLOAT DEFAULT NULL, `suvr_front_medial_ctx_r` FLOAT DEFAULT NULL, `suvr_juxtapositional_lobule_ctx_l` FLOAT DEFAULT NULL, `suvr_juxtapositional_lobule_ctx_r` FLOAT DEFAULT NULL, `suvr_subcallosal_ctx_l` FLOAT DEFAULT NULL, `suvr_subcallosal_ctx_r` FLOAT DEFAULT NULL, `suvr_paracingulate_gy_l` FLOAT DEFAULT NULL, `suvr_paracingulate_gy_r` FLOAT DEFAULT NULL, `suvr_cingulate_gy_ant_l` FLOAT DEFAULT NULL, `suvr_cingulate_gy_ant_r` FLOAT DEFAULT NULL, `suvr_cingulate_gy_post_l` FLOAT DEFAULT NULL, `suvr_cingulate_gy_post_r` FLOAT DEFAULT NULL, `suvr_precuneous_ctx_l` FLOAT DEFAULT NULL, `suvr_precuneous_ctx_r` FLOAT DEFAULT NULL, `suvr_cuneal_ctx_l` FLOAT DEFAULT NULL, `suvr_cuneal_ctx_r` FLOAT DEFAULT NULL, `suvr_front_orbital_ctx_l` FLOAT DEFAULT NULL, `suvr_front_orbital_ctx_r` FLOAT DEFAULT NULL, `suvr_parahippocampal_gy_ant_l` FLOAT DEFAULT NULL, `suvr_parahippocampal_gy_ant_r` FLOAT DEFAULT NULL, `suvr_parahippocampal_gy_post_l` FLOAT DEFAULT NULL, `suvr_parahippocampal_gy_post_r` FLOAT DEFAULT NULL, `suvr_lingual_gy_l` FLOAT DEFAULT NULL, `suvr_lingual_gy_r` FLOAT DEFAULT NULL, `suvr_temp_fusiform_ctx_ant_l` FLOAT DEFAULT NULL, `suvr_temp_fusiform_ctx_ant_r` FLOAT DEFAULT NULL, `suvr_temp_fusiform_ctx_post_l` FLOAT DEFAULT NULL, `suvr_temp_fusiform_ctx_post_r` FLOAT DEFAULT NULL, `suvr_temp_occ_fusiform_ctx_l` FLOAT DEFAULT NULL, `suvr_temp_occ_fusiform_ctx_r` FLOAT DEFAULT NULL, `suvr_occ_fusiform_gy_l` FLOAT DEFAULT NULL, `suvr_occ_fusiform_gy_r` FLOAT DEFAULT NULL, `suvr_front_operculum_ctx_l` FLOAT DEFAULT NULL, `suvr_front_operculum_ctx_r` FLOAT DEFAULT NULL, `suvr_central_opercular_ctx_l` FLOAT DEFAULT NULL, `suvr_central_opercular_ctx_r` FLOAT DEFAULT NULL, `suvr_parietal_operculum_ctx_l` FLOAT DEFAULT NULL, `suvr_parietal_operculum_ctx_r` FLOAT DEFAULT NULL, `suvr_planum_polare_l` FLOAT DEFAULT NULL, `suvr_planum_polare_r` FLOAT DEFAULT NULL, `suvr_heschls_gy_l` FLOAT DEFAULT NULL, `suvr_heschls_gy_r` FLOAT DEFAULT NULL, `suvr_planum_temporale_l` FLOAT DEFAULT NULL, `suvr_planum_temporale_r` FLOAT DEFAULT NULL, `suvr_supracalcarine_ctx_l` FLOAT DEFAULT NULL, `suvr_supracalcarine_ctx_r` FLOAT DEFAULT NULL, `suvr_occ_pole_l` FLOAT DEFAULT NULL, `suvr_occ_pole_r` FLOAT DEFAULT NULL, `suvr_thalamus_l` FLOAT DEFAULT NULL, `suvr_thalamus_r` FLOAT DEFAULT NULL, `suvr_caudate_l` FLOAT DEFAULT NULL, `suvr_caudate_r` FLOAT DEFAULT NULL, `suvr_putamen_l` FLOAT DEFAULT NULL, `suvr_putamen_r` FLOAT DEFAULT NULL, `suvr_pallidum_l` FLOAT DEFAULT NULL, `suvr_pallidum_r` FLOAT DEFAULT NULL, `suvr_hippocampus_l` FLOAT DEFAULT NULL, `suvr_hippocampus_r` FLOAT DEFAULT NULL, `suvr_amygdala_l` FLOAT DEFAULT NULL, `suvr_amygdala_r` FLOAT DEFAULT NULL, `suvr_accumbens_l` FLOAT DEFAULT NULL, `suvr_accumbens_r` FLOAT DEFAULT NULL, `suvr_cerebellum_gm_l` FLOAT DEFAULT NULL, `suvr_cerebellum_gm_r` FLOAT DEFAULT NULL, `suvr_cerebellum_wm_l` FLOAT DEFAULT NULL, `suvr_cerebellum_wm_r` FLOAT DEFAULT NULL, `suvr_brainstem` FLOAT DEFAULT NULL, `volume_cc_front_pole_l` FLOAT DEFAULT NULL, `volume_cc_front_pole_r` FLOAT DEFAULT NULL, `volume_cc_insular_ctx_l` FLOAT DEFAULT NULL, `volume_cc_insular_ctx_r` FLOAT DEFAULT NULL, `volume_cc_sup_front_gy_l` FLOAT DEFAULT NULL, `volume_cc_sup_front_gy_r` FLOAT DEFAULT NULL, `volume_cc_mid_front_gy_l` FLOAT DEFAULT NULL, `volume_cc_mid_front_gy_r` FLOAT DEFAULT NULL, `volume_cc_inf_front_gy_pars_triangularis_l` FLOAT DEFAULT NULL, `volume_cc_inf_front_gy_pars_triangularis_r` FLOAT DEFAULT NULL, `volume_cc_inf_front_gy_pars_opercularis_l` FLOAT DEFAULT NULL, `volume_cc_inf_front_gy_pars_opercularis_r` FLOAT DEFAULT NULL, `volume_cc_precentral_gy_l` FLOAT DEFAULT NULL, `volume_cc_precentral_gy_r` FLOAT DEFAULT NULL, `volume_cc_temp_pole_l` FLOAT DEFAULT NULL, `volume_cc_temp_pole_r` FLOAT DEFAULT NULL, `volume_cc_sup_temp_gy_ant_l` FLOAT DEFAULT NULL, `volume_cc_sup_temp_gy_ant_r` FLOAT DEFAULT NULL, `volume_cc_sup_temp_gy_post_l` FLOAT DEFAULT NULL, `volume_cc_sup_temp_gy_post_r` FLOAT DEFAULT NULL, `volume_cc_mid_temp_gy_ant_l` FLOAT DEFAULT NULL, `volume_cc_mid_temp_gy_ant_r` FLOAT DEFAULT NULL, `volume_cc_mid_temp_gy_post_l` FLOAT DEFAULT NULL, `volume_cc_mid_temp_gy_post_r` FLOAT DEFAULT NULL, `volume_cc_mid_temp_gy_temporooccipital_l` FLOAT DEFAULT NULL, `volume_cc_mid_temp_gy_temporooccipital_r` FLOAT DEFAULT NULL, `volume_cc_inf_temp_gy_ant_l` FLOAT DEFAULT NULL, `volume_cc_inf_temp_gy_ant_r` FLOAT DEFAULT NULL, `volume_cc_inf_temp_gy_post_l` FLOAT DEFAULT NULL, `volume_cc_inf_temp_gy_post_r` FLOAT DEFAULT NULL, `volume_cc_inf_temp_gy_temporooccipital_l` FLOAT DEFAULT NULL, `volume_cc_inf_temp_gy_temporooccipital_r` FLOAT DEFAULT NULL, `volume_cc_postcentral_gy_l` FLOAT DEFAULT NULL, `volume_cc_postcentral_gy_r` FLOAT DEFAULT NULL, `volume_cc_sup_parietal_lobule_l` FLOAT DEFAULT NULL, `volume_cc_sup_parietal_lobule_r` FLOAT DEFAULT NULL, `volume_cc_supramarginal_gy_ant_l` FLOAT DEFAULT NULL, `volume_cc_supramarginal_gy_ant_r` FLOAT DEFAULT NULL, `volume_cc_supramarginal_gy_post_l` FLOAT DEFAULT NULL, `volume_cc_supramarginal_gy_post_r` FLOAT DEFAULT NULL, `volume_cc_angular_gy_l` FLOAT DEFAULT NULL, `volume_cc_angular_gy_r` FLOAT DEFAULT NULL, `volume_cc_lat_occ_ctx_sup_l` FLOAT DEFAULT NULL, `volume_cc_lat_occ_ctx_sup_r` FLOAT DEFAULT NULL, `volume_cc_lat_occ_ctx_inf_l` FLOAT DEFAULT NULL, `volume_cc_lat_occ_ctx_inf_r` FLOAT DEFAULT NULL, `volume_cc_intracalcarine_ctx_l` FLOAT DEFAULT NULL, `volume_cc_intracalcarine_ctx_r` FLOAT DEFAULT NULL, `volume_cc_front_medial_ctx_l` FLOAT DEFAULT NULL, `volume_cc_front_medial_ctx_r` FLOAT DEFAULT NULL, `volume_cc_juxtapositional_lobule_ctx_l` FLOAT DEFAULT NULL, `volume_cc_juxtapositional_lobule_ctx_r` FLOAT DEFAULT NULL, `volume_cc_subcallosal_ctx_l` FLOAT DEFAULT NULL, `volume_cc_subcallosal_ctx_r` FLOAT DEFAULT NULL, `volume_cc_paracingulate_gy_l` FLOAT DEFAULT NULL, `volume_cc_paracingulate_gy_r` FLOAT DEFAULT NULL, `volume_cc_cingulate_gy_ant_l` FLOAT DEFAULT NULL, `volume_cc_cingulate_gy_ant_r` FLOAT DEFAULT NULL, `volume_cc_cingulate_gy_post_l` FLOAT DEFAULT NULL, `volume_cc_cingulate_gy_post_r` FLOAT DEFAULT NULL, `volume_cc_precuneous_ctx_l` FLOAT DEFAULT NULL, `volume_cc_precuneous_ctx_r` FLOAT DEFAULT NULL, `volume_cc_cuneal_ctx_l` FLOAT DEFAULT NULL, `volume_cc_cuneal_ctx_r` FLOAT DEFAULT NULL, `volume_cc_front_orbital_ctx_l` FLOAT DEFAULT NULL, `volume_cc_front_orbital_ctx_r` FLOAT DEFAULT NULL, `volume_cc_parahippocampal_gy_ant_l` FLOAT DEFAULT NULL, `volume_cc_parahippocampal_gy_ant_r` FLOAT DEFAULT NULL, `volume_cc_parahippocampal_gy_post_l` FLOAT DEFAULT NULL, `volume_cc_parahippocampal_gy_post_r` FLOAT DEFAULT NULL, `volume_cc_lingual_gy_l` FLOAT DEFAULT NULL, `volume_cc_lingual_gy_r` FLOAT DEFAULT NULL, `volume_cc_temp_fusiform_ctx_ant_l` FLOAT DEFAULT NULL, `volume_cc_temp_fusiform_ctx_ant_r` FLOAT DEFAULT NULL, `volume_cc_temp_fusiform_ctx_post_l` FLOAT DEFAULT NULL, `volume_cc_temp_fusiform_ctx_post_r` FLOAT DEFAULT NULL, `volume_cc_temp_occ_fusiform_ctx_l` FLOAT DEFAULT NULL, `volume_cc_temp_occ_fusiform_ctx_r` FLOAT DEFAULT NULL, `volume_cc_occ_fusiform_gy_l` FLOAT DEFAULT NULL, `volume_cc_occ_fusiform_gy_r` FLOAT DEFAULT NULL, `volume_cc_front_operculum_ctx_l` FLOAT DEFAULT NULL, `volume_cc_front_operculum_ctx_r` FLOAT DEFAULT NULL, `volume_cc_central_opercular_ctx_l` FLOAT DEFAULT NULL, `volume_cc_central_opercular_ctx_r` FLOAT DEFAULT NULL, `volume_cc_parietal_operculum_ctx_l` FLOAT DEFAULT NULL, `volume_cc_parietal_operculum_ctx_r` FLOAT DEFAULT NULL, `volume_cc_planum_polare_l` FLOAT DEFAULT NULL, `volume_cc_planum_polare_r` FLOAT DEFAULT NULL, `volume_cc_heschls_gy_l` FLOAT DEFAULT NULL, `volume_cc_heschls_gy_r` FLOAT DEFAULT NULL, `volume_cc_planum_temporale_l` FLOAT DEFAULT NULL, `volume_cc_planum_temporale_r` FLOAT DEFAULT NULL, `volume_cc_supracalcarine_ctx_l` FLOAT DEFAULT NULL, `volume_cc_supracalcarine_ctx_r` FLOAT DEFAULT NULL, `volume_cc_occ_pole_l` FLOAT DEFAULT NULL, `volume_cc_occ_pole_r` FLOAT DEFAULT NULL, `volume_cc_thalamus_l` FLOAT DEFAULT NULL, `volume_cc_thalamus_r` FLOAT DEFAULT NULL, `volume_cc_caudate_l` FLOAT DEFAULT NULL, `volume_cc_caudate_r` FLOAT DEFAULT NULL, `volume_cc_putamen_l` FLOAT DEFAULT NULL, `volume_cc_putamen_r` FLOAT DEFAULT NULL, `volume_cc_pallidum_l` FLOAT DEFAULT NULL, `volume_cc_pallidum_r` FLOAT DEFAULT NULL, `volume_cc_hippocampus_l` FLOAT DEFAULT NULL, `volume_cc_hippocampus_r` FLOAT DEFAULT NULL, `volume_cc_amygdala_l` FLOAT DEFAULT NULL, `volume_cc_amygdala_r` FLOAT DEFAULT NULL, `volume_cc_accumbens_l` FLOAT DEFAULT NULL, `volume_cc_accumbens_r` FLOAT DEFAULT NULL, `volume_cc_cerebellum_gm_l` FLOAT DEFAULT NULL, `volume_cc_cerebellum_gm_r` FLOAT DEFAULT NULL, `volume_cc_cerebellum_wm_l` FLOAT DEFAULT NULL, `volume_cc_cerebellum_wm_r` FLOAT DEFAULT NULL, `volume_cc_brainstem` FLOAT DEFAULT NULL, `general_comment` varchar(2000) DEFAULT NULL, `file_name` varchar(500) DEFAULT NULL, `secondary_key` varchar(10) DEFAULT NULL, `atlas` varchar(500) DEFAULT NULL, `pet_processing_date` VARCHAR(30) DEFAULT NULL, `pet_code_version` varchar(30) DEFAULT NULL, `ecat_file_name` varchar(500) DEFAULT NULL, `original_t1_mri_file_name` varchar(200) DEFAULT NULL, `age_at_appointment` FLOAT DEFAULT NULL, `bias_corrected_t1_mri_file` varchar(200) DEFAULT NULL, `mni_space_t1_mri` varchar(200) DEFAULT NULL, `multispectral_file` varchar(200) DEFAULT NULL, `pet_date_mri_date_diff_days` INT DEFAULT NULL, `mri_processing_date` varchar(30) DEFAULT NULL, `pet_log_file` varchar(200) DEFAULT NULL, `coregistration_reference_file` varchar(200) DEFAULT NULL, `processed_4d_pet_file` varchar(200) DEFAULT NULL, `processed_sum_pet_file` varchar(200) DEFAULT NULL, `processed_suvr_pet_file` varchar(200) DEFAULT NULL, `mni_space_suvr_pet_file` varchar(200) DEFAULT NULL, `pet_analysis_log_file` varchar(200) DEFAULT NULL,
  KEY `ind_cg_pet_neuraceq_roi_atlas_homic_mni_v1_old` (`enrollment_id`,`scan_procedure_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;"


     ActiveRecord::Base.connection.execute(create_new_homic);
     ActiveRecord::Base.connection.execute(create_old_homic);
     ActiveRecord::Base.connection.execute(create_homic);


create_morimod = "CREATE TABLE `cg_pet_neuraceq_roi_atlas_morimod_mni_v1` (
  `subjectid` varchar(50) DEFAULT NULL,
  `general_comment` varchar(2000) DEFAULT NULL,
  `enrollment_id` INT(11) DEFAULT NULL,
  `scan_procedure_id` INT(11) DEFAULT NULL,
  `reggie_id` varchar(10) DEFAULT NULL,
  `protocol` varchar(100) DEFAULT NULL,
  `enumber_only` varchar(30) DEFAULT NULL,
  `age` FLOAT DEFAULT NULL,
  `file_name` varchar(500) DEFAULT NULL,
  `secondary_key` varchar(10) DEFAULT NULL,
  `atlas` varchar(500) DEFAULT NULL,
  `pet_processing_date` varchar(30) DEFAULT NULL,
  `pet_code_version` varchar(30) DEFAULT NULL,
  `ecat_file_name` varchar(500) DEFAULT NULL,
  `original_t1_mri_file_name` varchar(200) DEFAULT NULL,
  `age_at_appointment` FLOAT DEFAULT NULL,
  `suvr_left_anterior_capsule_limb_of_internal` FLOAT DEFAULT NULL,
  `suvr_right_anterior_capsule_limb_of_internal` FLOAT DEFAULT NULL,
  `suvr_left_posterior_capsule_limb_of_internal` FLOAT DEFAULT NULL,
  `suvr_right_posterior_capsule_limb_of_internal` FLOAT DEFAULT NULL,
  `suvr_left_posterior_thalamic_radiation` FLOAT DEFAULT NULL,
  `suvr_right_posterior_thalamic_radiation` FLOAT DEFAULT NULL,
  `suvr_left_anterior_corona_radiata` FLOAT DEFAULT NULL,
  `suvr_right_anterior_corona_radiata` FLOAT DEFAULT NULL,
  `suvr_left_superior_corona_radiata` FLOAT DEFAULT NULL,
  `suvr_right_superior_corona_radiata` FLOAT DEFAULT NULL,
  `suvr_left_posterior_corona_radiata` FLOAT DEFAULT NULL,
  `suvr_right_posterior_corona_radiata` FLOAT DEFAULT NULL,
  `suvr_left_superior_longitudinal_longitudinal` FLOAT DEFAULT NULL,
  `suvr_right_superior_longitudinal_longitudinal` FLOAT DEFAULT NULL,
  `suvr_left_sagital_stratum` FLOAT DEFAULT NULL,
  `suvr_right_sagital_stratum` FLOAT DEFAULT NULL,
  `suvr_left_capsule_external` FLOAT DEFAULT NULL,
  `suvr_right_capsule_external` FLOAT DEFAULT NULL,
  `suvr_left_corpus_callosum_genu` FLOAT DEFAULT NULL,
  `suvr_right_corpus_callosum_genu` FLOAT DEFAULT NULL,
  `suvr_left_corpus_callosum_body` FLOAT DEFAULT NULL,
  `suvr_right_corpus_callosum_body` FLOAT DEFAULT NULL,
  `suvr_left_corpus_callosum` FLOAT DEFAULT NULL,
  `suvr_right_corpus_callosum` FLOAT DEFAULT NULL,
  `suvr_left_capsule_retrolenticular_part_of_ic` FLOAT DEFAULT NULL,
  `suvr_right_capsule_retrolenticular_part_of_ic` FLOAT DEFAULT NULL,
  `bias_corrected_t1_mri_file` varchar(200) DEFAULT NULL,
  `mni_space_t1_mri` varchar(200) DEFAULT NULL,
  `volume_cc_left_anterior_capsule_limb_of_internal` FLOAT DEFAULT NULL,
  `volume_cc_right_anterior_capsule_limb_of_internal` FLOAT DEFAULT NULL,
  `volume_cc_left_posterior_capsule_limb_of_internal` FLOAT DEFAULT NULL,
  `volume_cc_right_posterior_capsule_limb_of_internal` FLOAT DEFAULT NULL,
  `volume_cc_left_posterior_thalamic_radiation` FLOAT DEFAULT NULL,
  `volume_cc_right_posterior_thalamic_radiation` FLOAT DEFAULT NULL,
  `volume_cc_left_anterior_corona_radiata` FLOAT DEFAULT NULL,
  `volume_cc_right_anterior_corona_radiata` FLOAT DEFAULT NULL,
  `volume_cc_left_superior_corona_radiata` FLOAT DEFAULT NULL,
  `volume_cc_right_superior_corona_radiata` FLOAT DEFAULT NULL,
  `volume_cc_left_posterior_corona_radiata` FLOAT DEFAULT NULL,
  `volume_cc_right_posterior_corona_radiata` FLOAT DEFAULT NULL,
  `volume_cc_left_superior_longitudinal_longitudinal` FLOAT DEFAULT NULL,
  `volume_cc_right_superior_longitudinal_longitudinal` FLOAT DEFAULT NULL,
  `volume_cc_left_sagital_stratum` FLOAT DEFAULT NULL,
  `volume_cc_right_sagital_stratum` FLOAT DEFAULT NULL,
  `volume_cc_left_capsule_external` FLOAT DEFAULT NULL,
  `volume_cc_right_capsule_external` FLOAT DEFAULT NULL,
  `volume_cc_left_corpus_callosum_genu` FLOAT DEFAULT NULL,
  `volume_cc_right_corpus_callosum_genu` FLOAT DEFAULT NULL,
  `volume_cc_left_corpus_callosum_body` FLOAT DEFAULT NULL,
  `volume_cc_right_corpus_callosum_body` FLOAT DEFAULT NULL,
  `volume_cc_left_corpus_callosum` FLOAT DEFAULT NULL,
  `volume_cc_right_corpus_callosum` FLOAT DEFAULT NULL,
  `volume_cc_left_capsule_retrolenticular_part_of_ic` FLOAT DEFAULT NULL,
  `volume_cc_right_capsule_retrolenticular_part_of_ic` FLOAT DEFAULT NULL,
  `multispectral_file` varchar(200) DEFAULT NULL,
  `pet_date_mri_date_diff_days` FLOAT DEFAULT NULL,
  `mri_processing_date` varchar(30) DEFAULT NULL,
  `pet_log_file` varchar(200) DEFAULT NULL,
  `coregistration_reference_file` varchar(200) DEFAULT NULL,
  `processed_4d_pet_file` varchar(200) DEFAULT NULL,
  `processed_sum_pet_file` varchar(200) DEFAULT NULL,
  `processed_suvr_pet_file` varchar(200) DEFAULT NULL,
  `mni_space_suvr_pet_file` varchar(200) DEFAULT NULL,
  `pet_analysis_log_file` varchar(200) DEFAULT NULL,
  KEY `ind_cg_pet_neuraceq_roi_atlas_morimod_mni_v1` (`enrollment_id`,`scan_procedure_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;"


create_morimod_old = "CREATE TABLE `cg_pet_neuraceq_roi_atlas_morimod_mni_v1_old` (
  `subjectid` varchar(50) DEFAULT NULL,
  `general_comment` varchar(2000) DEFAULT NULL,
  `enrollment_id` INT(11) DEFAULT NULL,
  `scan_procedure_id` INT(11) DEFAULT NULL,
  `reggie_id` varchar(10) DEFAULT NULL,
  `protocol` varchar(100) DEFAULT NULL,
  `enumber_only` varchar(30) DEFAULT NULL,
  `age` FLOAT DEFAULT NULL,
  `file_name` varchar(500) DEFAULT NULL,
  `secondary_key` varchar(10) DEFAULT NULL,
  `atlas` varchar(500) DEFAULT NULL,
  `pet_processing_date` varchar(30) DEFAULT NULL,
  `pet_code_version` varchar(30) DEFAULT NULL,
  `ecat_file_name` varchar(500) DEFAULT NULL,
  `original_t1_mri_file_name` varchar(200) DEFAULT NULL,
  `age_at_appointment` FLOAT DEFAULT NULL,
  `suvr_left_anterior_capsule_limb_of_internal` FLOAT DEFAULT NULL,
  `suvr_right_anterior_capsule_limb_of_internal` FLOAT DEFAULT NULL,
  `suvr_left_posterior_capsule_limb_of_internal` FLOAT DEFAULT NULL,
  `suvr_right_posterior_capsule_limb_of_internal` FLOAT DEFAULT NULL,
  `suvr_left_posterior_thalamic_radiation` FLOAT DEFAULT NULL,
  `suvr_right_posterior_thalamic_radiation` FLOAT DEFAULT NULL,
  `suvr_left_anterior_corona_radiata` FLOAT DEFAULT NULL,
  `suvr_right_anterior_corona_radiata` FLOAT DEFAULT NULL,
  `suvr_left_superior_corona_radiata` FLOAT DEFAULT NULL,
  `suvr_right_superior_corona_radiata` FLOAT DEFAULT NULL,
  `suvr_left_posterior_corona_radiata` FLOAT DEFAULT NULL,
  `suvr_right_posterior_corona_radiata` FLOAT DEFAULT NULL,
  `suvr_left_superior_longitudinal_longitudinal` FLOAT DEFAULT NULL,
  `suvr_right_superior_longitudinal_longitudinal` FLOAT DEFAULT NULL,
  `suvr_left_sagital_stratum` FLOAT DEFAULT NULL,
  `suvr_right_sagital_stratum` FLOAT DEFAULT NULL,
  `suvr_left_capsule_external` FLOAT DEFAULT NULL,
  `suvr_right_capsule_external` FLOAT DEFAULT NULL,
  `suvr_left_corpus_callosum_genu` FLOAT DEFAULT NULL,
  `suvr_right_corpus_callosum_genu` FLOAT DEFAULT NULL,
  `suvr_left_corpus_callosum_body` FLOAT DEFAULT NULL,
  `suvr_right_corpus_callosum_body` FLOAT DEFAULT NULL,
  `suvr_left_corpus_callosum` FLOAT DEFAULT NULL,
  `suvr_right_corpus_callosum` FLOAT DEFAULT NULL,
  `suvr_left_capsule_retrolenticular_part_of_ic` FLOAT DEFAULT NULL,
  `suvr_right_capsule_retrolenticular_part_of_ic` FLOAT DEFAULT NULL,
  `bias_corrected_t1_mri_file` varchar(200) DEFAULT NULL,
  `mni_space_t1_mri` varchar(200) DEFAULT NULL,
  `volume_cc_left_anterior_capsule_limb_of_internal` FLOAT DEFAULT NULL,
  `volume_cc_right_anterior_capsule_limb_of_internal` FLOAT DEFAULT NULL,
  `volume_cc_left_posterior_capsule_limb_of_internal` FLOAT DEFAULT NULL,
  `volume_cc_right_posterior_capsule_limb_of_internal` FLOAT DEFAULT NULL,
  `volume_cc_left_posterior_thalamic_radiation` FLOAT DEFAULT NULL,
  `volume_cc_right_posterior_thalamic_radiation` FLOAT DEFAULT NULL,
  `volume_cc_left_anterior_corona_radiata` FLOAT DEFAULT NULL,
  `volume_cc_right_anterior_corona_radiata` FLOAT DEFAULT NULL,
  `volume_cc_left_superior_corona_radiata` FLOAT DEFAULT NULL,
  `volume_cc_right_superior_corona_radiata` FLOAT DEFAULT NULL,
  `volume_cc_left_posterior_corona_radiata` FLOAT DEFAULT NULL,
  `volume_cc_right_posterior_corona_radiata` FLOAT DEFAULT NULL,
  `volume_cc_left_superior_longitudinal_longitudinal` FLOAT DEFAULT NULL,
  `volume_cc_right_superior_longitudinal_longitudinal` FLOAT DEFAULT NULL,
  `volume_cc_left_sagital_stratum` FLOAT DEFAULT NULL,
  `volume_cc_right_sagital_stratum` FLOAT DEFAULT NULL,
  `volume_cc_left_capsule_external` FLOAT DEFAULT NULL,
  `volume_cc_right_capsule_external` FLOAT DEFAULT NULL,
  `volume_cc_left_corpus_callosum_genu` FLOAT DEFAULT NULL,
  `volume_cc_right_corpus_callosum_genu` FLOAT DEFAULT NULL,
  `volume_cc_left_corpus_callosum_body` FLOAT DEFAULT NULL,
  `volume_cc_right_corpus_callosum_body` FLOAT DEFAULT NULL,
  `volume_cc_left_corpus_callosum` FLOAT DEFAULT NULL,
  `volume_cc_right_corpus_callosum` FLOAT DEFAULT NULL,
  `volume_cc_left_capsule_retrolenticular_part_of_ic` FLOAT DEFAULT NULL,
  `volume_cc_right_capsule_retrolenticular_part_of_ic` FLOAT DEFAULT NULL,
  `multispectral_file` varchar(200) DEFAULT NULL,
  `pet_date_mri_date_diff_days` FLOAT DEFAULT NULL,
  `mri_processing_date` varchar(30) DEFAULT NULL,
  `pet_log_file` varchar(200) DEFAULT NULL,
  `coregistration_reference_file` varchar(200) DEFAULT NULL,
  `processed_4d_pet_file` varchar(200) DEFAULT NULL,
  `processed_sum_pet_file` varchar(200) DEFAULT NULL,
  `processed_suvr_pet_file` varchar(200) DEFAULT NULL,
  `mni_space_suvr_pet_file` varchar(200) DEFAULT NULL,
  `pet_analysis_log_file` varchar(200) DEFAULT NULL,
  KEY `ind_cg_pet_neuraceq_roi_atlas_morimod_mni_v1_old` (`enrollment_id`,`scan_procedure_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;"


create_morimod_new = "CREATE TABLE `cg_pet_neuraceq_roi_atlas_morimod_mni_v1_new` (
  `subjectid` varchar(50) DEFAULT NULL,
  `general_comment` varchar(2000) DEFAULT NULL,
  `enrollment_id` INT(11) DEFAULT NULL,
  `scan_procedure_id` INT(11) DEFAULT NULL,
  `reggie_id` varchar(10) DEFAULT NULL,
  `protocol` varchar(100) DEFAULT NULL,
  `enumber_only` varchar(30) DEFAULT NULL,
  `age` FLOAT DEFAULT NULL,
  `file_name` varchar(500) DEFAULT NULL,
  `secondary_key` varchar(10) DEFAULT NULL,
  `atlas` varchar(500) DEFAULT NULL,
  `pet_processing_date` varchar(30) DEFAULT NULL,
  `pet_code_version` varchar(30) DEFAULT NULL,
  `ecat_file_name` varchar(500) DEFAULT NULL,
  `original_t1_mri_file_name` varchar(200) DEFAULT NULL,
  `age_at_appointment` FLOAT DEFAULT NULL,
  `suvr_left_anterior_capsule_limb_of_internal` FLOAT DEFAULT NULL,
  `suvr_right_anterior_capsule_limb_of_internal` FLOAT DEFAULT NULL,
  `suvr_left_posterior_capsule_limb_of_internal` FLOAT DEFAULT NULL,
  `suvr_right_posterior_capsule_limb_of_internal` FLOAT DEFAULT NULL,
  `suvr_left_posterior_thalamic_radiation` FLOAT DEFAULT NULL,
  `suvr_right_posterior_thalamic_radiation` FLOAT DEFAULT NULL,
  `suvr_left_anterior_corona_radiata` FLOAT DEFAULT NULL,
  `suvr_right_anterior_corona_radiata` FLOAT DEFAULT NULL,
  `suvr_left_superior_corona_radiata` FLOAT DEFAULT NULL,
  `suvr_right_superior_corona_radiata` FLOAT DEFAULT NULL,
  `suvr_left_posterior_corona_radiata` FLOAT DEFAULT NULL,
  `suvr_right_posterior_corona_radiata` FLOAT DEFAULT NULL,
  `suvr_left_superior_longitudinal_longitudinal` FLOAT DEFAULT NULL,
  `suvr_right_superior_longitudinal_longitudinal` FLOAT DEFAULT NULL,
  `suvr_left_sagital_stratum` FLOAT DEFAULT NULL,
  `suvr_right_sagital_stratum` FLOAT DEFAULT NULL,
  `suvr_left_capsule_external` FLOAT DEFAULT NULL,
  `suvr_right_capsule_external` FLOAT DEFAULT NULL,
  `suvr_left_corpus_callosum_genu` FLOAT DEFAULT NULL,
  `suvr_right_corpus_callosum_genu` FLOAT DEFAULT NULL,
  `suvr_left_corpus_callosum_body` FLOAT DEFAULT NULL,
  `suvr_right_corpus_callosum_body` FLOAT DEFAULT NULL,
  `suvr_left_corpus_callosum` FLOAT DEFAULT NULL,
  `suvr_right_corpus_callosum` FLOAT DEFAULT NULL,
  `suvr_left_capsule_retrolenticular_part_of_ic` FLOAT DEFAULT NULL,
  `suvr_right_capsule_retrolenticular_part_of_ic` FLOAT DEFAULT NULL,
  `bias_corrected_t1_mri_file` varchar(200) DEFAULT NULL,
  `mni_space_t1_mri` varchar(200) DEFAULT NULL,
  `volume_cc_left_anterior_capsule_limb_of_internal` FLOAT DEFAULT NULL,
  `volume_cc_right_anterior_capsule_limb_of_internal` FLOAT DEFAULT NULL,
  `volume_cc_left_posterior_capsule_limb_of_internal` FLOAT DEFAULT NULL,
  `volume_cc_right_posterior_capsule_limb_of_internal` FLOAT DEFAULT NULL,
  `volume_cc_left_posterior_thalamic_radiation` FLOAT DEFAULT NULL,
  `volume_cc_right_posterior_thalamic_radiation` FLOAT DEFAULT NULL,
  `volume_cc_left_anterior_corona_radiata` FLOAT DEFAULT NULL,
  `volume_cc_right_anterior_corona_radiata` FLOAT DEFAULT NULL,
  `volume_cc_left_superior_corona_radiata` FLOAT DEFAULT NULL,
  `volume_cc_right_superior_corona_radiata` FLOAT DEFAULT NULL,
  `volume_cc_left_posterior_corona_radiata` FLOAT DEFAULT NULL,
  `volume_cc_right_posterior_corona_radiata` FLOAT DEFAULT NULL,
  `volume_cc_left_superior_longitudinal_longitudinal` FLOAT DEFAULT NULL,
  `volume_cc_right_superior_longitudinal_longitudinal` FLOAT DEFAULT NULL,
  `volume_cc_left_sagital_stratum` FLOAT DEFAULT NULL,
  `volume_cc_right_sagital_stratum` FLOAT DEFAULT NULL,
  `volume_cc_left_capsule_external` FLOAT DEFAULT NULL,
  `volume_cc_right_capsule_external` FLOAT DEFAULT NULL,
  `volume_cc_left_corpus_callosum_genu` FLOAT DEFAULT NULL,
  `volume_cc_right_corpus_callosum_genu` FLOAT DEFAULT NULL,
  `volume_cc_left_corpus_callosum_body` FLOAT DEFAULT NULL,
  `volume_cc_right_corpus_callosum_body` FLOAT DEFAULT NULL,
  `volume_cc_left_corpus_callosum` FLOAT DEFAULT NULL,
  `volume_cc_right_corpus_callosum` FLOAT DEFAULT NULL,
  `volume_cc_left_capsule_retrolenticular_part_of_ic` FLOAT DEFAULT NULL,
  `volume_cc_right_capsule_retrolenticular_part_of_ic` FLOAT DEFAULT NULL,
  `multispectral_file` varchar(200) DEFAULT NULL,
  `pet_date_mri_date_diff_days` FLOAT DEFAULT NULL,
  `mri_processing_date` varchar(30) DEFAULT NULL,
  `pet_log_file` varchar(200) DEFAULT NULL,
  `coregistration_reference_file` varchar(200) DEFAULT NULL,
  `processed_4d_pet_file` varchar(200) DEFAULT NULL,
  `processed_sum_pet_file` varchar(200) DEFAULT NULL,
  `processed_suvr_pet_file` varchar(200) DEFAULT NULL,
  `mni_space_suvr_pet_file` varchar(200) DEFAULT NULL,
  `pet_analysis_log_file` varchar(200) DEFAULT NULL,
  KEY `ind_cg_pet_neuraceq_roi_atlas_morimod_mni_v1_new` (`enrollment_id`,`scan_procedure_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;"


  ActiveRecord::Base.connection.execute(create_morimod_new);
  ActiveRecord::Base.connection.execute(create_morimod_old);
  ActiveRecord::Base.connection.execute(create_morimod);



create_na = "CREATE TABLE `cg_pet_neuraceq_roi_atlas_na` (
  `subjectid` varchar(50) DEFAULT NULL,
  `enrollment_id` INT DEFAULT NULL,
  `scan_procedure_id` INT DEFAULT NULL,
  `suvr_altref_cblm_gm_inf` FLOAT DEFAULT NULL,
  `suvr_altref_cblm_gm` FLOAT DEFAULT NULL,
  `suvr_altref_cblm_whole` FLOAT DEFAULT NULL,
  `suvr_altref_cblm_wm` FLOAT DEFAULT NULL,
  `suvr_altref_centsm_wm` FLOAT DEFAULT NULL,
  `reggie_id` varchar(10) DEFAULT NULL,
  `protocol` varchar(100) DEFAULT NULL,
  `enumber_only` varchar(30) DEFAULT NULL,
  `age` varchar(10) DEFAULT NULL,
  `general_comment` varchar(2000) DEFAULT NULL,
  `file_name` varchar(500) DEFAULT NULL,
  `secondary_key` varchar(10) DEFAULT NULL,
  `atlas` varchar(500) DEFAULT NULL,
  `pet_processing_date` varchar(50) DEFAULT NULL,
  `ecat_file_name` varchar(500) DEFAULT NULL,
  `original_t1_mri_file_name` varchar(200) DEFAULT NULL,
  `age_at_appointment` FLOAT DEFAULT NULL,
  `bias_corrected_t1_mri_file` varchar(200) DEFAULT NULL,
  `mni_space_t1_mri` varchar(200) DEFAULT NULL,
  `volume_cc_altref_cblm_gm_inf` FLOAT DEFAULT NULL,
  `volume_cc_altref_cblm_gm` FLOAT DEFAULT NULL,
  `volume_cc_altref_cblm_whole` FLOAT DEFAULT NULL,
  `volume_cc_altref_cblm_wm` FLOAT DEFAULT NULL,
  `volume_cc_altref_centsm_wm` FLOAT DEFAULT NULL,
  `pet_code_version` varchar(30) DEFAULT NULL,
  `multispectral_file` varchar(200) DEFAULT NULL,
  `pet_date_mri_date_diff_days` FLOAT DEFAULT NULL,
  `mri_processing_date` varchar(30) DEFAULT NULL,
  `pet_log_file` varchar(200) DEFAULT NULL,
  `coregistration_reference_file` varchar(200) DEFAULT NULL,
  `processed_4d_pet_file` varchar(200) DEFAULT NULL,
  `processed_sum_pet_file` varchar(200) DEFAULT NULL,
  `processed_suvr_pet_file` varchar(200) DEFAULT NULL,
  `mni_space_suvr_pet_file` varchar(200) DEFAULT NULL,
  `pet_analysis_log_file` varchar(200) DEFAULT NULL,
  KEY `ind_cg_pet_neuraceq_roi_atlas_na` (`enrollment_id`,`scan_procedure_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;"


create_na_new = "CREATE TABLE `cg_pet_neuraceq_roi_atlas_na_new` (
  `subjectid` varchar(50) DEFAULT NULL,
  `enrollment_id` INT DEFAULT NULL,
  `scan_procedure_id` INT DEFAULT NULL,
  `suvr_altref_cblm_gm_inf` FLOAT DEFAULT NULL,
  `suvr_altref_cblm_gm` FLOAT DEFAULT NULL,
  `suvr_altref_cblm_whole` FLOAT DEFAULT NULL,
  `suvr_altref_cblm_wm` FLOAT DEFAULT NULL,
  `suvr_altref_centsm_wm` FLOAT DEFAULT NULL,
  `reggie_id` varchar(10) DEFAULT NULL,
  `protocol` varchar(100) DEFAULT NULL,
  `enumber_only` varchar(30) DEFAULT NULL,
  `age` varchar(10) DEFAULT NULL,
  `general_comment` varchar(2000) DEFAULT NULL,
  `file_name` varchar(500) DEFAULT NULL,
  `secondary_key` varchar(10) DEFAULT NULL,
  `atlas` varchar(500) DEFAULT NULL,
  `pet_processing_date` varchar(50) DEFAULT NULL,
  `ecat_file_name` varchar(500) DEFAULT NULL,
  `original_t1_mri_file_name` varchar(200) DEFAULT NULL,
  `age_at_appointment` FLOAT DEFAULT NULL,
  `bias_corrected_t1_mri_file` varchar(200) DEFAULT NULL,
  `mni_space_t1_mri` varchar(200) DEFAULT NULL,
  `volume_cc_altref_cblm_gm_inf` FLOAT DEFAULT NULL,
  `volume_cc_altref_cblm_gm` FLOAT DEFAULT NULL,
  `volume_cc_altref_cblm_whole` FLOAT DEFAULT NULL,
  `volume_cc_altref_cblm_wm` FLOAT DEFAULT NULL,
  `volume_cc_altref_centsm_wm` FLOAT DEFAULT NULL,
  `pet_code_version` varchar(30) DEFAULT NULL,
  `multispectral_file` varchar(200) DEFAULT NULL,
  `pet_date_mri_date_diff_days` FLOAT DEFAULT NULL,
  `mri_processing_date` varchar(30) DEFAULT NULL,
  `pet_log_file` varchar(200) DEFAULT NULL,
  `coregistration_reference_file` varchar(200) DEFAULT NULL,
  `processed_4d_pet_file` varchar(200) DEFAULT NULL,
  `processed_sum_pet_file` varchar(200) DEFAULT NULL,
  `processed_suvr_pet_file` varchar(200) DEFAULT NULL,
  `mni_space_suvr_pet_file` varchar(200) DEFAULT NULL,
  `pet_analysis_log_file` varchar(200) DEFAULT NULL,
  KEY `ind_cg_pet_neuraceq_roi_atlas_na_new` (`enrollment_id`,`scan_procedure_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;"

create_na_old = "CREATE TABLE `cg_pet_neuraceq_roi_atlas_na_old` (
  `subjectid` varchar(50) DEFAULT NULL,
  `enrollment_id` INT DEFAULT NULL,
  `scan_procedure_id` INT DEFAULT NULL,
  `suvr_altref_cblm_gm_inf` FLOAT DEFAULT NULL,
  `suvr_altref_cblm_gm` FLOAT DEFAULT NULL,
  `suvr_altref_cblm_whole` FLOAT DEFAULT NULL,
  `suvr_altref_cblm_wm` FLOAT DEFAULT NULL,
  `suvr_altref_centsm_wm` FLOAT DEFAULT NULL,
  `reggie_id` varchar(10) DEFAULT NULL,
  `protocol` varchar(100) DEFAULT NULL,
  `enumber_only` varchar(30) DEFAULT NULL,
  `age` varchar(10) DEFAULT NULL,
  `general_comment` varchar(2000) DEFAULT NULL,
  `file_name` varchar(500) DEFAULT NULL,
  `secondary_key` varchar(10) DEFAULT NULL,
  `atlas` varchar(500) DEFAULT NULL,
  `pet_processing_date` varchar(50) DEFAULT NULL,
  `ecat_file_name` varchar(500) DEFAULT NULL,
  `original_t1_mri_file_name` varchar(200) DEFAULT NULL,
  `age_at_appointment` FLOAT DEFAULT NULL,
  `bias_corrected_t1_mri_file` varchar(200) DEFAULT NULL,
  `mni_space_t1_mri` varchar(200) DEFAULT NULL,
  `volume_cc_altref_cblm_gm_inf` FLOAT DEFAULT NULL,
  `volume_cc_altref_cblm_gm` FLOAT DEFAULT NULL,
  `volume_cc_altref_cblm_whole` FLOAT DEFAULT NULL,
  `volume_cc_altref_cblm_wm` FLOAT DEFAULT NULL,
  `volume_cc_altref_centsm_wm` FLOAT DEFAULT NULL,
  `pet_code_version` varchar(30) DEFAULT NULL,
  `multispectral_file` varchar(200) DEFAULT NULL,
  `pet_date_mri_date_diff_days` FLOAT DEFAULT NULL,
  `mri_processing_date` varchar(30) DEFAULT NULL,
  `pet_log_file` varchar(200) DEFAULT NULL,
  `coregistration_reference_file` varchar(200) DEFAULT NULL,
  `processed_4d_pet_file` varchar(200) DEFAULT NULL,
  `processed_sum_pet_file` varchar(200) DEFAULT NULL,
  `processed_suvr_pet_file` varchar(200) DEFAULT NULL,
  `mni_space_suvr_pet_file` varchar(200) DEFAULT NULL,
  `pet_analysis_log_file` varchar(200) DEFAULT NULL,
  KEY `ind_cg_pet_neuraceq_roi_atlas_na_old` (`enrollment_id`,`scan_procedure_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;"


  ActiveRecord::Base.connection.execute(create_na_new);
  ActiveRecord::Base.connection.execute(create_na_old);
  ActiveRecord::Base.connection.execute(create_na);


create_tjb = "CREATE TABLE `cg_pet_neuraceq_roi_atlas_tjb_mni_v1` (
  `subjectid` varchar(50) DEFAULT NULL,
  `general_comment` varchar(2000) DEFAULT NULL,
  `enrollment_id` int DEFAULT NULL,
  `scan_procedure_id` int DEFAULT NULL,
  `file_name` varchar(500) DEFAULT NULL,
  `secondary_key` varchar(10) DEFAULT NULL,
  `atlas` varchar(500) DEFAULT NULL,
  `pet_processing_date` varchar(30) DEFAULT NULL,
  `pet_code_version` varchar(30) DEFAULT NULL,
  `ecat_file_name` varchar(500) DEFAULT NULL,
  `original_t1_mri_file_name` varchar(200) DEFAULT NULL,
  `suvr_clivus` FLOAT DEFAULT NULL,
  `suvr_ethmoid` FLOAT DEFAULT NULL,
  `suvr_meninges` FLOAT DEFAULT NULL,
  `suvr_pineal` FLOAT DEFAULT NULL,
  `suvr_vermis_sup_ant` FLOAT DEFAULT NULL,
  `suvr_cerebellum_superior` FLOAT DEFAULT NULL,
  `suvr_substantia_nigra` FLOAT DEFAULT NULL,
  `suvr_sphenotemporalbuttress` FLOAT DEFAULT NULL,
  `suvr_pons` FLOAT DEFAULT NULL,
  `volume_cc_clivus` FLOAT DEFAULT NULL,
  `volume_cc_ethmoid` FLOAT DEFAULT NULL,
  `volume_cc_meninges` FLOAT DEFAULT NULL,
  `volume_cc_pineal` FLOAT DEFAULT NULL,
  `volume_cc_vermis_sup_ant` FLOAT DEFAULT NULL,
  `volume_cc_cerebellum_superior` FLOAT DEFAULT NULL,
  `volume_cc_substantia_nigra` FLOAT DEFAULT NULL,
  `volume_cc_sphenotemporalbuttress` FLOAT DEFAULT NULL,
  `volume_cc_pons` FLOAT DEFAULT NULL,
  `age_at_appointment` FLOAT DEFAULT NULL,
  `bias_corrected_t1_mri_file` varchar(200) DEFAULT NULL,
  `mni_space_t1_mri` varchar(200) DEFAULT NULL,
  `multispectral_file` varchar(200) DEFAULT NULL,
  `pet_date_mri_date_diff_days` FLOAT DEFAULT NULL,
  `mri_processing_date` varchar(30) DEFAULT NULL,
  `pet_log_file` varchar(200) DEFAULT NULL,
  `coregistration_reference_file` varchar(200) DEFAULT NULL,
  `processed_4d_pet_file` varchar(200) DEFAULT NULL,
  `processed_sum_pet_file` varchar(200) DEFAULT NULL,
  `processed_suvr_pet_file` varchar(200) DEFAULT NULL,
  `mni_space_suvr_pet_file` varchar(200) DEFAULT NULL,
  `pet_analysis_log_file` varchar(200) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;"


create_tjb_new = "CREATE TABLE `cg_pet_neuraceq_roi_atlas_tjb_mni_v1_new` (
  `subjectid` varchar(50) DEFAULT NULL,
  `general_comment` varchar(2000) DEFAULT NULL,
  `enrollment_id` int DEFAULT NULL,
  `scan_procedure_id` int DEFAULT NULL,
  `file_name` varchar(500) DEFAULT NULL,
  `secondary_key` varchar(10) DEFAULT NULL,
  `atlas` varchar(500) DEFAULT NULL,
  `pet_processing_date` varchar(30) DEFAULT NULL,
  `pet_code_version` varchar(30) DEFAULT NULL,
  `ecat_file_name` varchar(500) DEFAULT NULL,
  `original_t1_mri_file_name` varchar(200) DEFAULT NULL,
  `suvr_clivus` FLOAT DEFAULT NULL,
  `suvr_ethmoid` FLOAT DEFAULT NULL,
  `suvr_meninges` FLOAT DEFAULT NULL,
  `suvr_pineal` FLOAT DEFAULT NULL,
  `suvr_vermis_sup_ant` FLOAT DEFAULT NULL,
  `suvr_cerebellum_superior` FLOAT DEFAULT NULL,
  `suvr_substantia_nigra` FLOAT DEFAULT NULL,
  `suvr_sphenotemporalbuttress` FLOAT DEFAULT NULL,
  `suvr_pons` FLOAT DEFAULT NULL,
  `volume_cc_clivus` FLOAT DEFAULT NULL,
  `volume_cc_ethmoid` FLOAT DEFAULT NULL,
  `volume_cc_meninges` FLOAT DEFAULT NULL,
  `volume_cc_pineal` FLOAT DEFAULT NULL,
  `volume_cc_vermis_sup_ant` FLOAT DEFAULT NULL,
  `volume_cc_cerebellum_superior` FLOAT DEFAULT NULL,
  `volume_cc_substantia_nigra` FLOAT DEFAULT NULL,
  `volume_cc_sphenotemporalbuttress` FLOAT DEFAULT NULL,
  `volume_cc_pons` FLOAT DEFAULT NULL,
  `age_at_appointment` FLOAT DEFAULT NULL,
  `bias_corrected_t1_mri_file` varchar(200) DEFAULT NULL,
  `mni_space_t1_mri` varchar(200) DEFAULT NULL,
  `multispectral_file` varchar(200) DEFAULT NULL,
  `pet_date_mri_date_diff_days` FLOAT DEFAULT NULL,
  `mri_processing_date` varchar(30) DEFAULT NULL,
  `pet_log_file` varchar(200) DEFAULT NULL,
  `coregistration_reference_file` varchar(200) DEFAULT NULL,
  `processed_4d_pet_file` varchar(200) DEFAULT NULL,
  `processed_sum_pet_file` varchar(200) DEFAULT NULL,
  `processed_suvr_pet_file` varchar(200) DEFAULT NULL,
  `mni_space_suvr_pet_file` varchar(200) DEFAULT NULL,
  `pet_analysis_log_file` varchar(200) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;"


create_tjb_old = "CREATE TABLE `cg_pet_neuraceq_roi_atlas_tjb_mni_v1_old` (
  `subjectid` varchar(50) DEFAULT NULL,
  `general_comment` varchar(2000) DEFAULT NULL,
  `enrollment_id` int DEFAULT NULL,
  `scan_procedure_id` int DEFAULT NULL,
  `file_name` varchar(500) DEFAULT NULL,
  `secondary_key` varchar(10) DEFAULT NULL,
  `atlas` varchar(500) DEFAULT NULL,
  `pet_processing_date` varchar(30) DEFAULT NULL,
  `pet_code_version` varchar(30) DEFAULT NULL,
  `ecat_file_name` varchar(500) DEFAULT NULL,
  `original_t1_mri_file_name` varchar(200) DEFAULT NULL,
  `suvr_clivus` FLOAT DEFAULT NULL,
  `suvr_ethmoid` FLOAT DEFAULT NULL,
  `suvr_meninges` FLOAT DEFAULT NULL,
  `suvr_pineal` FLOAT DEFAULT NULL,
  `suvr_vermis_sup_ant` FLOAT DEFAULT NULL,
  `suvr_cerebellum_superior` FLOAT DEFAULT NULL,
  `suvr_substantia_nigra` FLOAT DEFAULT NULL,
  `suvr_sphenotemporalbuttress` FLOAT DEFAULT NULL,
  `suvr_pons` FLOAT DEFAULT NULL,
  `volume_cc_clivus` FLOAT DEFAULT NULL,
  `volume_cc_ethmoid` FLOAT DEFAULT NULL,
  `volume_cc_meninges` FLOAT DEFAULT NULL,
  `volume_cc_pineal` FLOAT DEFAULT NULL,
  `volume_cc_vermis_sup_ant` FLOAT DEFAULT NULL,
  `volume_cc_cerebellum_superior` FLOAT DEFAULT NULL,
  `volume_cc_substantia_nigra` FLOAT DEFAULT NULL,
  `volume_cc_sphenotemporalbuttress` FLOAT DEFAULT NULL,
  `volume_cc_pons` FLOAT DEFAULT NULL,
  `age_at_appointment` FLOAT DEFAULT NULL,
  `bias_corrected_t1_mri_file` varchar(200) DEFAULT NULL,
  `mni_space_t1_mri` varchar(200) DEFAULT NULL,
  `multispectral_file` varchar(200) DEFAULT NULL,
  `pet_date_mri_date_diff_days` FLOAT DEFAULT NULL,
  `mri_processing_date` varchar(30) DEFAULT NULL,
  `pet_log_file` varchar(200) DEFAULT NULL,
  `coregistration_reference_file` varchar(200) DEFAULT NULL,
  `processed_4d_pet_file` varchar(200) DEFAULT NULL,
  `processed_sum_pet_file` varchar(200) DEFAULT NULL,
  `processed_suvr_pet_file` varchar(200) DEFAULT NULL,
  `mni_space_suvr_pet_file` varchar(200) DEFAULT NULL,
  `pet_analysis_log_file` varchar(200) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;"


  ActiveRecord::Base.connection.execute(create_tjb_new);
  ActiveRecord::Base.connection.execute(create_tjb_old);
  ActiveRecord::Base.connection.execute(create_tjb);

end

