require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CgTnsController do

  def mock_cg_tn(stubs={})
    @mock_cg_tn ||= mock_model(CgTn, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all cg_tns as @cg_tns" do
      CgTn.stub(:all) { [mock_cg_tn] }
      get :index
      assigns(:cg_tns).should eq([mock_cg_tn])
    end
  end

  describe "GET show" do
    it "assigns the requested cg_tn as @cg_tn" do
      CgTn.stub(:find).with("37") { mock_cg_tn }
      get :show, :id => "37"
      assigns(:cg_tn).should be(mock_cg_tn)
    end
  end

  describe "GET new" do
    it "assigns a new cg_tn as @cg_tn" do
      CgTn.stub(:new) { mock_cg_tn }
      get :new
      assigns(:cg_tn).should be(mock_cg_tn)
    end
  end

  describe "GET edit" do
    it "assigns the requested cg_tn as @cg_tn" do
      CgTn.stub(:find).with("37") { mock_cg_tn }
      get :edit, :id => "37"
      assigns(:cg_tn).should be(mock_cg_tn)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created cg_tn as @cg_tn" do
        CgTn.stub(:new).with({'these' => 'params'}) { mock_cg_tn(:save => true) }
        post :create, :cg_tn => {'these' => 'params'}
        assigns(:cg_tn).should be(mock_cg_tn)
      end

      it "redirects to the created cg_tn" do
        CgTn.stub(:new) { mock_cg_tn(:save => true) }
        post :create, :cg_tn => {}
        response.should redirect_to(cg_tn_url(mock_cg_tn))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cg_tn as @cg_tn" do
        CgTn.stub(:new).with({'these' => 'params'}) { mock_cg_tn(:save => false) }
        post :create, :cg_tn => {'these' => 'params'}
        assigns(:cg_tn).should be(mock_cg_tn)
      end

      it "re-renders the 'new' template" do
        CgTn.stub(:new) { mock_cg_tn(:save => false) }
        post :create, :cg_tn => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cg_tn" do
        CgTn.stub(:find).with("37") { mock_cg_tn }
        mock_cg_tn.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :cg_tn => {'these' => 'params'}
      end

      it "assigns the requested cg_tn as @cg_tn" do
        CgTn.stub(:find) { mock_cg_tn(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:cg_tn).should be(mock_cg_tn)
      end

      it "redirects to the cg_tn" do
        CgTn.stub(:find) { mock_cg_tn(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(cg_tn_url(mock_cg_tn))
      end
    end

    describe "with invalid params" do
      it "assigns the cg_tn as @cg_tn" do
        CgTn.stub(:find) { mock_cg_tn(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:cg_tn).should be(mock_cg_tn)
      end

      it "re-renders the 'edit' template" do
        CgTn.stub(:find) { mock_cg_tn(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cg_tn" do
      CgTn.stub(:find).with("37") { mock_cg_tn }
      mock_cg_tn.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the cg_tns list" do
      CgTn.stub(:find) { mock_cg_tn }
      delete :destroy, :id => "1"
      response.should redirect_to(cg_tns_url)
    end
  end

end
