require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LookupSetsController do

  def mock_lookup_set(stubs={})
    @mock_lookup_set ||= mock_model(LookupSet, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lookup_sets as @lookup_sets" do
      LookupSet.stub(:all) { [mock_lookup_set] }
      get :index
      assigns(:lookup_sets).should eq([mock_lookup_set])
    end
  end

  describe "GET show" do
    it "assigns the requested lookup_set as @lookup_set" do
      LookupSet.stub(:find).with("37") { mock_lookup_set }
      get :show, :id => "37"
      assigns(:lookup_set).should be(mock_lookup_set)
    end
  end

  describe "GET new" do
    it "assigns a new lookup_set as @lookup_set" do
      LookupSet.stub(:new) { mock_lookup_set }
      get :new
      assigns(:lookup_set).should be(mock_lookup_set)
    end
  end

  describe "GET edit" do
    it "assigns the requested lookup_set as @lookup_set" do
      LookupSet.stub(:find).with("37") { mock_lookup_set }
      get :edit, :id => "37"
      assigns(:lookup_set).should be(mock_lookup_set)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lookup_set as @lookup_set" do
        LookupSet.stub(:new).with({'these' => 'params'}) { mock_lookup_set(:save => true) }
        post :create, :lookup_set => {'these' => 'params'}
        assigns(:lookup_set).should be(mock_lookup_set)
      end

      it "redirects to the created lookup_set" do
        LookupSet.stub(:new) { mock_lookup_set(:save => true) }
        post :create, :lookup_set => {}
        response.should redirect_to(lookup_set_url(mock_lookup_set))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lookup_set as @lookup_set" do
        LookupSet.stub(:new).with({'these' => 'params'}) { mock_lookup_set(:save => false) }
        post :create, :lookup_set => {'these' => 'params'}
        assigns(:lookup_set).should be(mock_lookup_set)
      end

      it "re-renders the 'new' template" do
        LookupSet.stub(:new) { mock_lookup_set(:save => false) }
        post :create, :lookup_set => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lookup_set" do
        LookupSet.stub(:find).with("37") { mock_lookup_set }
        mock_lookup_set.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lookup_set => {'these' => 'params'}
      end

      it "assigns the requested lookup_set as @lookup_set" do
        LookupSet.stub(:find) { mock_lookup_set(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lookup_set).should be(mock_lookup_set)
      end

      it "redirects to the lookup_set" do
        LookupSet.stub(:find) { mock_lookup_set(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lookup_set_url(mock_lookup_set))
      end
    end

    describe "with invalid params" do
      it "assigns the lookup_set as @lookup_set" do
        LookupSet.stub(:find) { mock_lookup_set(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lookup_set).should be(mock_lookup_set)
      end

      it "re-renders the 'edit' template" do
        LookupSet.stub(:find) { mock_lookup_set(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lookup_set" do
      LookupSet.stub(:find).with("37") { mock_lookup_set }
      mock_lookup_set.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lookup_sets list" do
      LookupSet.stub(:find) { mock_lookup_set }
      delete :destroy, :id => "1"
      response.should redirect_to(lookup_sets_url)
    end
  end

end
