require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LookupRadsController do

  def mock_lookup_rad(stubs={})
    @mock_lookup_rad ||= mock_model(LookupRad, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lookup_rads as @lookup_rads" do
      LookupRad.stub(:all) { [mock_lookup_rad] }
      get :index
      assigns(:lookup_rads).should eq([mock_lookup_rad])
    end
  end

  describe "GET show" do
    it "assigns the requested lookup_rad as @lookup_rad" do
      LookupRad.stub(:find).with("37") { mock_lookup_rad }
      get :show, :id => "37"
      assigns(:lookup_rad).should be(mock_lookup_rad)
    end
  end

  describe "GET new" do
    it "assigns a new lookup_rad as @lookup_rad" do
      LookupRad.stub(:new) { mock_lookup_rad }
      get :new
      assigns(:lookup_rad).should be(mock_lookup_rad)
    end
  end

  describe "GET edit" do
    it "assigns the requested lookup_rad as @lookup_rad" do
      LookupRad.stub(:find).with("37") { mock_lookup_rad }
      get :edit, :id => "37"
      assigns(:lookup_rad).should be(mock_lookup_rad)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lookup_rad as @lookup_rad" do
        LookupRad.stub(:new).with({'these' => 'params'}) { mock_lookup_rad(:save => true) }
        post :create, :lookup_rad => {'these' => 'params'}
        assigns(:lookup_rad).should be(mock_lookup_rad)
      end

      it "redirects to the created lookup_rad" do
        LookupRad.stub(:new) { mock_lookup_rad(:save => true) }
        post :create, :lookup_rad => {}
        response.should redirect_to(lookup_rad_url(mock_lookup_rad))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lookup_rad as @lookup_rad" do
        LookupRad.stub(:new).with({'these' => 'params'}) { mock_lookup_rad(:save => false) }
        post :create, :lookup_rad => {'these' => 'params'}
        assigns(:lookup_rad).should be(mock_lookup_rad)
      end

      it "re-renders the 'new' template" do
        LookupRad.stub(:new) { mock_lookup_rad(:save => false) }
        post :create, :lookup_rad => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lookup_rad" do
        LookupRad.stub(:find).with("37") { mock_lookup_rad }
        mock_lookup_rad.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lookup_rad => {'these' => 'params'}
      end

      it "assigns the requested lookup_rad as @lookup_rad" do
        LookupRad.stub(:find) { mock_lookup_rad(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lookup_rad).should be(mock_lookup_rad)
      end

      it "redirects to the lookup_rad" do
        LookupRad.stub(:find) { mock_lookup_rad(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lookup_rad_url(mock_lookup_rad))
      end
    end

    describe "with invalid params" do
      it "assigns the lookup_rad as @lookup_rad" do
        LookupRad.stub(:find) { mock_lookup_rad(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lookup_rad).should be(mock_lookup_rad)
      end

      it "re-renders the 'edit' template" do
        LookupRad.stub(:find) { mock_lookup_rad(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lookup_rad" do
      LookupRad.stub(:find).with("37") { mock_lookup_rad }
      mock_lookup_rad.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lookup_rads list" do
      LookupRad.stub(:find) { mock_lookup_rad }
      delete :destroy, :id => "1"
      response.should redirect_to(lookup_rads_url)
    end
  end

end
