require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LookupDemographichandednessesController do

  def mock_lookup_demographichandedness(stubs={})
    @mock_lookup_demographichandedness ||= mock_model(LookupDemographichandedness, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lookup_demographichandednesses as @lookup_demographichandednesses" do
      LookupDemographichandedness.stub(:all) { [mock_lookup_demographichandedness] }
      get :index
      assigns(:lookup_demographichandednesses).should eq([mock_lookup_demographichandedness])
    end
  end

  describe "GET show" do
    it "assigns the requested lookup_demographichandedness as @lookup_demographichandedness" do
      LookupDemographichandedness.stub(:find).with("37") { mock_lookup_demographichandedness }
      get :show, :id => "37"
      assigns(:lookup_demographichandedness).should be(mock_lookup_demographichandedness)
    end
  end

  describe "GET new" do
    it "assigns a new lookup_demographichandedness as @lookup_demographichandedness" do
      LookupDemographichandedness.stub(:new) { mock_lookup_demographichandedness }
      get :new
      assigns(:lookup_demographichandedness).should be(mock_lookup_demographichandedness)
    end
  end

  describe "GET edit" do
    it "assigns the requested lookup_demographichandedness as @lookup_demographichandedness" do
      LookupDemographichandedness.stub(:find).with("37") { mock_lookup_demographichandedness }
      get :edit, :id => "37"
      assigns(:lookup_demographichandedness).should be(mock_lookup_demographichandedness)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lookup_demographichandedness as @lookup_demographichandedness" do
        LookupDemographichandedness.stub(:new).with({'these' => 'params'}) { mock_lookup_demographichandedness(:save => true) }
        post :create, :lookup_demographichandedness => {'these' => 'params'}
        assigns(:lookup_demographichandedness).should be(mock_lookup_demographichandedness)
      end

      it "redirects to the created lookup_demographichandedness" do
        LookupDemographichandedness.stub(:new) { mock_lookup_demographichandedness(:save => true) }
        post :create, :lookup_demographichandedness => {}
        response.should redirect_to(lookup_demographichandedness_url(mock_lookup_demographichandedness))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lookup_demographichandedness as @lookup_demographichandedness" do
        LookupDemographichandedness.stub(:new).with({'these' => 'params'}) { mock_lookup_demographichandedness(:save => false) }
        post :create, :lookup_demographichandedness => {'these' => 'params'}
        assigns(:lookup_demographichandedness).should be(mock_lookup_demographichandedness)
      end

      it "re-renders the 'new' template" do
        LookupDemographichandedness.stub(:new) { mock_lookup_demographichandedness(:save => false) }
        post :create, :lookup_demographichandedness => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lookup_demographichandedness" do
        LookupDemographichandedness.stub(:find).with("37") { mock_lookup_demographichandedness }
        mock_lookup_demographichandedness.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lookup_demographichandedness => {'these' => 'params'}
      end

      it "assigns the requested lookup_demographichandedness as @lookup_demographichandedness" do
        LookupDemographichandedness.stub(:find) { mock_lookup_demographichandedness(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lookup_demographichandedness).should be(mock_lookup_demographichandedness)
      end

      it "redirects to the lookup_demographichandedness" do
        LookupDemographichandedness.stub(:find) { mock_lookup_demographichandedness(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lookup_demographichandedness_url(mock_lookup_demographichandedness))
      end
    end

    describe "with invalid params" do
      it "assigns the lookup_demographichandedness as @lookup_demographichandedness" do
        LookupDemographichandedness.stub(:find) { mock_lookup_demographichandedness(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lookup_demographichandedness).should be(mock_lookup_demographichandedness)
      end

      it "re-renders the 'edit' template" do
        LookupDemographichandedness.stub(:find) { mock_lookup_demographichandedness(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lookup_demographichandedness" do
      LookupDemographichandedness.stub(:find).with("37") { mock_lookup_demographichandedness }
      mock_lookup_demographichandedness.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lookup_demographichandednesses list" do
      LookupDemographichandedness.stub(:find) { mock_lookup_demographichandedness }
      delete :destroy, :id => "1"
      response.should redirect_to(lookup_demographichandednesses_url)
    end
  end

end
