require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LookupDemographicmaritalstatusesController do

  def mock_lookup_demographicmaritalstatus(stubs={})
    @mock_lookup_demographicmaritalstatus ||= mock_model(LookupDemographicmaritalstatus, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lookup_demographicmaritalstatuses as @lookup_demographicmaritalstatuses" do
      LookupDemographicmaritalstatus.stub(:all) { [mock_lookup_demographicmaritalstatus] }
      get :index
      assigns(:lookup_demographicmaritalstatuses).should eq([mock_lookup_demographicmaritalstatus])
    end
  end

  describe "GET show" do
    it "assigns the requested lookup_demographicmaritalstatus as @lookup_demographicmaritalstatus" do
      LookupDemographicmaritalstatus.stub(:find).with("37") { mock_lookup_demographicmaritalstatus }
      get :show, :id => "37"
      assigns(:lookup_demographicmaritalstatus).should be(mock_lookup_demographicmaritalstatus)
    end
  end

  describe "GET new" do
    it "assigns a new lookup_demographicmaritalstatus as @lookup_demographicmaritalstatus" do
      LookupDemographicmaritalstatus.stub(:new) { mock_lookup_demographicmaritalstatus }
      get :new
      assigns(:lookup_demographicmaritalstatus).should be(mock_lookup_demographicmaritalstatus)
    end
  end

  describe "GET edit" do
    it "assigns the requested lookup_demographicmaritalstatus as @lookup_demographicmaritalstatus" do
      LookupDemographicmaritalstatus.stub(:find).with("37") { mock_lookup_demographicmaritalstatus }
      get :edit, :id => "37"
      assigns(:lookup_demographicmaritalstatus).should be(mock_lookup_demographicmaritalstatus)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lookup_demographicmaritalstatus as @lookup_demographicmaritalstatus" do
        LookupDemographicmaritalstatus.stub(:new).with({'these' => 'params'}) { mock_lookup_demographicmaritalstatus(:save => true) }
        post :create, :lookup_demographicmaritalstatus => {'these' => 'params'}
        assigns(:lookup_demographicmaritalstatus).should be(mock_lookup_demographicmaritalstatus)
      end

      it "redirects to the created lookup_demographicmaritalstatus" do
        LookupDemographicmaritalstatus.stub(:new) { mock_lookup_demographicmaritalstatus(:save => true) }
        post :create, :lookup_demographicmaritalstatus => {}
        response.should redirect_to(lookup_demographicmaritalstatus_url(mock_lookup_demographicmaritalstatus))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lookup_demographicmaritalstatus as @lookup_demographicmaritalstatus" do
        LookupDemographicmaritalstatus.stub(:new).with({'these' => 'params'}) { mock_lookup_demographicmaritalstatus(:save => false) }
        post :create, :lookup_demographicmaritalstatus => {'these' => 'params'}
        assigns(:lookup_demographicmaritalstatus).should be(mock_lookup_demographicmaritalstatus)
      end

      it "re-renders the 'new' template" do
        LookupDemographicmaritalstatus.stub(:new) { mock_lookup_demographicmaritalstatus(:save => false) }
        post :create, :lookup_demographicmaritalstatus => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lookup_demographicmaritalstatus" do
        LookupDemographicmaritalstatus.stub(:find).with("37") { mock_lookup_demographicmaritalstatus }
        mock_lookup_demographicmaritalstatus.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lookup_demographicmaritalstatus => {'these' => 'params'}
      end

      it "assigns the requested lookup_demographicmaritalstatus as @lookup_demographicmaritalstatus" do
        LookupDemographicmaritalstatus.stub(:find) { mock_lookup_demographicmaritalstatus(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lookup_demographicmaritalstatus).should be(mock_lookup_demographicmaritalstatus)
      end

      it "redirects to the lookup_demographicmaritalstatus" do
        LookupDemographicmaritalstatus.stub(:find) { mock_lookup_demographicmaritalstatus(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lookup_demographicmaritalstatus_url(mock_lookup_demographicmaritalstatus))
      end
    end

    describe "with invalid params" do
      it "assigns the lookup_demographicmaritalstatus as @lookup_demographicmaritalstatus" do
        LookupDemographicmaritalstatus.stub(:find) { mock_lookup_demographicmaritalstatus(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lookup_demographicmaritalstatus).should be(mock_lookup_demographicmaritalstatus)
      end

      it "re-renders the 'edit' template" do
        LookupDemographicmaritalstatus.stub(:find) { mock_lookup_demographicmaritalstatus(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lookup_demographicmaritalstatus" do
      LookupDemographicmaritalstatus.stub(:find).with("37") { mock_lookup_demographicmaritalstatus }
      mock_lookup_demographicmaritalstatus.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lookup_demographicmaritalstatuses list" do
      LookupDemographicmaritalstatus.stub(:find) { mock_lookup_demographicmaritalstatus }
      delete :destroy, :id => "1"
      response.should redirect_to(lookup_demographicmaritalstatuses_url)
    end
  end

end
