require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LookupVisitfrequenciesController do

  def mock_lookup_visitfrequency(stubs={})
    @mock_lookup_visitfrequency ||= mock_model(LookupVisitfrequency, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lookup_visitfrequencies as @lookup_visitfrequencies" do
      LookupVisitfrequency.stub(:all) { [mock_lookup_visitfrequency] }
      get :index
      assigns(:lookup_visitfrequencies).should eq([mock_lookup_visitfrequency])
    end
  end

  describe "GET show" do
    it "assigns the requested lookup_visitfrequency as @lookup_visitfrequency" do
      LookupVisitfrequency.stub(:find).with("37") { mock_lookup_visitfrequency }
      get :show, :id => "37"
      assigns(:lookup_visitfrequency).should be(mock_lookup_visitfrequency)
    end
  end

  describe "GET new" do
    it "assigns a new lookup_visitfrequency as @lookup_visitfrequency" do
      LookupVisitfrequency.stub(:new) { mock_lookup_visitfrequency }
      get :new
      assigns(:lookup_visitfrequency).should be(mock_lookup_visitfrequency)
    end
  end

  describe "GET edit" do
    it "assigns the requested lookup_visitfrequency as @lookup_visitfrequency" do
      LookupVisitfrequency.stub(:find).with("37") { mock_lookup_visitfrequency }
      get :edit, :id => "37"
      assigns(:lookup_visitfrequency).should be(mock_lookup_visitfrequency)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lookup_visitfrequency as @lookup_visitfrequency" do
        LookupVisitfrequency.stub(:new).with({'these' => 'params'}) { mock_lookup_visitfrequency(:save => true) }
        post :create, :lookup_visitfrequency => {'these' => 'params'}
        assigns(:lookup_visitfrequency).should be(mock_lookup_visitfrequency)
      end

      it "redirects to the created lookup_visitfrequency" do
        LookupVisitfrequency.stub(:new) { mock_lookup_visitfrequency(:save => true) }
        post :create, :lookup_visitfrequency => {}
        response.should redirect_to(lookup_visitfrequency_url(mock_lookup_visitfrequency))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lookup_visitfrequency as @lookup_visitfrequency" do
        LookupVisitfrequency.stub(:new).with({'these' => 'params'}) { mock_lookup_visitfrequency(:save => false) }
        post :create, :lookup_visitfrequency => {'these' => 'params'}
        assigns(:lookup_visitfrequency).should be(mock_lookup_visitfrequency)
      end

      it "re-renders the 'new' template" do
        LookupVisitfrequency.stub(:new) { mock_lookup_visitfrequency(:save => false) }
        post :create, :lookup_visitfrequency => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lookup_visitfrequency" do
        LookupVisitfrequency.stub(:find).with("37") { mock_lookup_visitfrequency }
        mock_lookup_visitfrequency.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lookup_visitfrequency => {'these' => 'params'}
      end

      it "assigns the requested lookup_visitfrequency as @lookup_visitfrequency" do
        LookupVisitfrequency.stub(:find) { mock_lookup_visitfrequency(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lookup_visitfrequency).should be(mock_lookup_visitfrequency)
      end

      it "redirects to the lookup_visitfrequency" do
        LookupVisitfrequency.stub(:find) { mock_lookup_visitfrequency(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lookup_visitfrequency_url(mock_lookup_visitfrequency))
      end
    end

    describe "with invalid params" do
      it "assigns the lookup_visitfrequency as @lookup_visitfrequency" do
        LookupVisitfrequency.stub(:find) { mock_lookup_visitfrequency(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lookup_visitfrequency).should be(mock_lookup_visitfrequency)
      end

      it "re-renders the 'edit' template" do
        LookupVisitfrequency.stub(:find) { mock_lookup_visitfrequency(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lookup_visitfrequency" do
      LookupVisitfrequency.stub(:find).with("37") { mock_lookup_visitfrequency }
      mock_lookup_visitfrequency.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lookup_visitfrequencies list" do
      LookupVisitfrequency.stub(:find) { mock_lookup_visitfrequency }
      delete :destroy, :id => "1"
      response.should redirect_to(lookup_visitfrequencies_url)
    end
  end

end
