require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LookupStatusesController do

  def mock_lookup_status(stubs={})
    @mock_lookup_status ||= mock_model(LookupStatus, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lookup_statuses as @lookup_statuses" do
      LookupStatus.stub(:all) { [mock_lookup_status] }
      get :index
      assigns(:lookup_statuses).should eq([mock_lookup_status])
    end
  end

  describe "GET show" do
    it "assigns the requested lookup_status as @lookup_status" do
      LookupStatus.stub(:find).with("37") { mock_lookup_status }
      get :show, :id => "37"
      assigns(:lookup_status).should be(mock_lookup_status)
    end
  end

  describe "GET new" do
    it "assigns a new lookup_status as @lookup_status" do
      LookupStatus.stub(:new) { mock_lookup_status }
      get :new
      assigns(:lookup_status).should be(mock_lookup_status)
    end
  end

  describe "GET edit" do
    it "assigns the requested lookup_status as @lookup_status" do
      LookupStatus.stub(:find).with("37") { mock_lookup_status }
      get :edit, :id => "37"
      assigns(:lookup_status).should be(mock_lookup_status)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lookup_status as @lookup_status" do
        LookupStatus.stub(:new).with({'these' => 'params'}) { mock_lookup_status(:save => true) }
        post :create, :lookup_status => {'these' => 'params'}
        assigns(:lookup_status).should be(mock_lookup_status)
      end

      it "redirects to the created lookup_status" do
        LookupStatus.stub(:new) { mock_lookup_status(:save => true) }
        post :create, :lookup_status => {}
        response.should redirect_to(lookup_status_url(mock_lookup_status))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lookup_status as @lookup_status" do
        LookupStatus.stub(:new).with({'these' => 'params'}) { mock_lookup_status(:save => false) }
        post :create, :lookup_status => {'these' => 'params'}
        assigns(:lookup_status).should be(mock_lookup_status)
      end

      it "re-renders the 'new' template" do
        LookupStatus.stub(:new) { mock_lookup_status(:save => false) }
        post :create, :lookup_status => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lookup_status" do
        LookupStatus.stub(:find).with("37") { mock_lookup_status }
        mock_lookup_status.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lookup_status => {'these' => 'params'}
      end

      it "assigns the requested lookup_status as @lookup_status" do
        LookupStatus.stub(:find) { mock_lookup_status(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lookup_status).should be(mock_lookup_status)
      end

      it "redirects to the lookup_status" do
        LookupStatus.stub(:find) { mock_lookup_status(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lookup_status_url(mock_lookup_status))
      end
    end

    describe "with invalid params" do
      it "assigns the lookup_status as @lookup_status" do
        LookupStatus.stub(:find) { mock_lookup_status(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lookup_status).should be(mock_lookup_status)
      end

      it "re-renders the 'edit' template" do
        LookupStatus.stub(:find) { mock_lookup_status(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lookup_status" do
      LookupStatus.stub(:find).with("37") { mock_lookup_status }
      mock_lookup_status.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lookup_statuses list" do
      LookupStatus.stub(:find) { mock_lookup_status }
      delete :destroy, :id => "1"
      response.should redirect_to(lookup_statuses_url)
    end
  end

end
