require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LookupDiagnosesController do

  def mock_lookup_diagnosis(stubs={})
    @mock_lookup_diagnosis ||= mock_model(LookupDiagnosis, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lookup_diagnoses as @lookup_diagnoses" do
      LookupDiagnosis.stub(:all) { [mock_lookup_diagnosis] }
      get :index
      assigns(:lookup_diagnoses).should eq([mock_lookup_diagnosis])
    end
  end

  describe "GET show" do
    it "assigns the requested lookup_diagnosis as @lookup_diagnosis" do
      LookupDiagnosis.stub(:find).with("37") { mock_lookup_diagnosis }
      get :show, :id => "37"
      assigns(:lookup_diagnosis).should be(mock_lookup_diagnosis)
    end
  end

  describe "GET new" do
    it "assigns a new lookup_diagnosis as @lookup_diagnosis" do
      LookupDiagnosis.stub(:new) { mock_lookup_diagnosis }
      get :new
      assigns(:lookup_diagnosis).should be(mock_lookup_diagnosis)
    end
  end

  describe "GET edit" do
    it "assigns the requested lookup_diagnosis as @lookup_diagnosis" do
      LookupDiagnosis.stub(:find).with("37") { mock_lookup_diagnosis }
      get :edit, :id => "37"
      assigns(:lookup_diagnosis).should be(mock_lookup_diagnosis)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lookup_diagnosis as @lookup_diagnosis" do
        LookupDiagnosis.stub(:new).with({'these' => 'params'}) { mock_lookup_diagnosis(:save => true) }
        post :create, :lookup_diagnosis => {'these' => 'params'}
        assigns(:lookup_diagnosis).should be(mock_lookup_diagnosis)
      end

      it "redirects to the created lookup_diagnosis" do
        LookupDiagnosis.stub(:new) { mock_lookup_diagnosis(:save => true) }
        post :create, :lookup_diagnosis => {}
        response.should redirect_to(lookup_diagnosis_url(mock_lookup_diagnosis))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lookup_diagnosis as @lookup_diagnosis" do
        LookupDiagnosis.stub(:new).with({'these' => 'params'}) { mock_lookup_diagnosis(:save => false) }
        post :create, :lookup_diagnosis => {'these' => 'params'}
        assigns(:lookup_diagnosis).should be(mock_lookup_diagnosis)
      end

      it "re-renders the 'new' template" do
        LookupDiagnosis.stub(:new) { mock_lookup_diagnosis(:save => false) }
        post :create, :lookup_diagnosis => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lookup_diagnosis" do
        LookupDiagnosis.stub(:find).with("37") { mock_lookup_diagnosis }
        mock_lookup_diagnosis.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lookup_diagnosis => {'these' => 'params'}
      end

      it "assigns the requested lookup_diagnosis as @lookup_diagnosis" do
        LookupDiagnosis.stub(:find) { mock_lookup_diagnosis(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lookup_diagnosis).should be(mock_lookup_diagnosis)
      end

      it "redirects to the lookup_diagnosis" do
        LookupDiagnosis.stub(:find) { mock_lookup_diagnosis(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lookup_diagnosis_url(mock_lookup_diagnosis))
      end
    end

    describe "with invalid params" do
      it "assigns the lookup_diagnosis as @lookup_diagnosis" do
        LookupDiagnosis.stub(:find) { mock_lookup_diagnosis(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lookup_diagnosis).should be(mock_lookup_diagnosis)
      end

      it "re-renders the 'edit' template" do
        LookupDiagnosis.stub(:find) { mock_lookup_diagnosis(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lookup_diagnosis" do
      LookupDiagnosis.stub(:find).with("37") { mock_lookup_diagnosis }
      mock_lookup_diagnosis.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lookup_diagnoses list" do
      LookupDiagnosis.stub(:find) { mock_lookup_diagnosis }
      delete :destroy, :id => "1"
      response.should redirect_to(lookup_diagnoses_url)
    end
  end

end
