require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LookupFamhxesController do

  def mock_lookup_famhx(stubs={})
    @mock_lookup_famhx ||= mock_model(LookupFamhx, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lookup_famhxes as @lookup_famhxes" do
      LookupFamhx.stub(:all) { [mock_lookup_famhx] }
      get :index
      assigns(:lookup_famhxes).should eq([mock_lookup_famhx])
    end
  end

  describe "GET show" do
    it "assigns the requested lookup_famhx as @lookup_famhx" do
      LookupFamhx.stub(:find).with("37") { mock_lookup_famhx }
      get :show, :id => "37"
      assigns(:lookup_famhx).should be(mock_lookup_famhx)
    end
  end

  describe "GET new" do
    it "assigns a new lookup_famhx as @lookup_famhx" do
      LookupFamhx.stub(:new) { mock_lookup_famhx }
      get :new
      assigns(:lookup_famhx).should be(mock_lookup_famhx)
    end
  end

  describe "GET edit" do
    it "assigns the requested lookup_famhx as @lookup_famhx" do
      LookupFamhx.stub(:find).with("37") { mock_lookup_famhx }
      get :edit, :id => "37"
      assigns(:lookup_famhx).should be(mock_lookup_famhx)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lookup_famhx as @lookup_famhx" do
        LookupFamhx.stub(:new).with({'these' => 'params'}) { mock_lookup_famhx(:save => true) }
        post :create, :lookup_famhx => {'these' => 'params'}
        assigns(:lookup_famhx).should be(mock_lookup_famhx)
      end

      it "redirects to the created lookup_famhx" do
        LookupFamhx.stub(:new) { mock_lookup_famhx(:save => true) }
        post :create, :lookup_famhx => {}
        response.should redirect_to(lookup_famhx_url(mock_lookup_famhx))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lookup_famhx as @lookup_famhx" do
        LookupFamhx.stub(:new).with({'these' => 'params'}) { mock_lookup_famhx(:save => false) }
        post :create, :lookup_famhx => {'these' => 'params'}
        assigns(:lookup_famhx).should be(mock_lookup_famhx)
      end

      it "re-renders the 'new' template" do
        LookupFamhx.stub(:new) { mock_lookup_famhx(:save => false) }
        post :create, :lookup_famhx => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lookup_famhx" do
        LookupFamhx.stub(:find).with("37") { mock_lookup_famhx }
        mock_lookup_famhx.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lookup_famhx => {'these' => 'params'}
      end

      it "assigns the requested lookup_famhx as @lookup_famhx" do
        LookupFamhx.stub(:find) { mock_lookup_famhx(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lookup_famhx).should be(mock_lookup_famhx)
      end

      it "redirects to the lookup_famhx" do
        LookupFamhx.stub(:find) { mock_lookup_famhx(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lookup_famhx_url(mock_lookup_famhx))
      end
    end

    describe "with invalid params" do
      it "assigns the lookup_famhx as @lookup_famhx" do
        LookupFamhx.stub(:find) { mock_lookup_famhx(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lookup_famhx).should be(mock_lookup_famhx)
      end

      it "re-renders the 'edit' template" do
        LookupFamhx.stub(:find) { mock_lookup_famhx(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lookup_famhx" do
      LookupFamhx.stub(:find).with("37") { mock_lookup_famhx }
      mock_lookup_famhx.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lookup_famhxes list" do
      LookupFamhx.stub(:find) { mock_lookup_famhx }
      delete :destroy, :id => "1"
      response.should redirect_to(lookup_famhxes_url)
    end
  end

end
