require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LookupScantasksController do

  def mock_lookup_scantask(stubs={})
    @mock_lookup_scantask ||= mock_model(LookupScantask, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lookup_scantasks as @lookup_scantasks" do
      LookupScantask.stub(:all) { [mock_lookup_scantask] }
      get :index
      assigns(:lookup_scantasks).should eq([mock_lookup_scantask])
    end
  end

  describe "GET show" do
    it "assigns the requested lookup_scantask as @lookup_scantask" do
      LookupScantask.stub(:find).with("37") { mock_lookup_scantask }
      get :show, :id => "37"
      assigns(:lookup_scantask).should be(mock_lookup_scantask)
    end
  end

  describe "GET new" do
    it "assigns a new lookup_scantask as @lookup_scantask" do
      LookupScantask.stub(:new) { mock_lookup_scantask }
      get :new
      assigns(:lookup_scantask).should be(mock_lookup_scantask)
    end
  end

  describe "GET edit" do
    it "assigns the requested lookup_scantask as @lookup_scantask" do
      LookupScantask.stub(:find).with("37") { mock_lookup_scantask }
      get :edit, :id => "37"
      assigns(:lookup_scantask).should be(mock_lookup_scantask)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lookup_scantask as @lookup_scantask" do
        LookupScantask.stub(:new).with({'these' => 'params'}) { mock_lookup_scantask(:save => true) }
        post :create, :lookup_scantask => {'these' => 'params'}
        assigns(:lookup_scantask).should be(mock_lookup_scantask)
      end

      it "redirects to the created lookup_scantask" do
        LookupScantask.stub(:new) { mock_lookup_scantask(:save => true) }
        post :create, :lookup_scantask => {}
        response.should redirect_to(lookup_scantask_url(mock_lookup_scantask))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lookup_scantask as @lookup_scantask" do
        LookupScantask.stub(:new).with({'these' => 'params'}) { mock_lookup_scantask(:save => false) }
        post :create, :lookup_scantask => {'these' => 'params'}
        assigns(:lookup_scantask).should be(mock_lookup_scantask)
      end

      it "re-renders the 'new' template" do
        LookupScantask.stub(:new) { mock_lookup_scantask(:save => false) }
        post :create, :lookup_scantask => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lookup_scantask" do
        LookupScantask.stub(:find).with("37") { mock_lookup_scantask }
        mock_lookup_scantask.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lookup_scantask => {'these' => 'params'}
      end

      it "assigns the requested lookup_scantask as @lookup_scantask" do
        LookupScantask.stub(:find) { mock_lookup_scantask(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lookup_scantask).should be(mock_lookup_scantask)
      end

      it "redirects to the lookup_scantask" do
        LookupScantask.stub(:find) { mock_lookup_scantask(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lookup_scantask_url(mock_lookup_scantask))
      end
    end

    describe "with invalid params" do
      it "assigns the lookup_scantask as @lookup_scantask" do
        LookupScantask.stub(:find) { mock_lookup_scantask(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lookup_scantask).should be(mock_lookup_scantask)
      end

      it "re-renders the 'edit' template" do
        LookupScantask.stub(:find) { mock_lookup_scantask(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lookup_scantask" do
      LookupScantask.stub(:find).with("37") { mock_lookup_scantask }
      mock_lookup_scantask.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lookup_scantasks list" do
      LookupScantask.stub(:find) { mock_lookup_scantask }
      delete :destroy, :id => "1"
      response.should redirect_to(lookup_scantasks_url)
    end
  end

end
