require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LookupImagingplanesController do

  def mock_lookup_imagingplane(stubs={})
    @mock_lookup_imagingplane ||= mock_model(LookupImagingplane, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lookup_imagingplanes as @lookup_imagingplanes" do
      LookupImagingplane.stub(:all) { [mock_lookup_imagingplane] }
      get :index
      assigns(:lookup_imagingplanes).should eq([mock_lookup_imagingplane])
    end
  end

  describe "GET show" do
    it "assigns the requested lookup_imagingplane as @lookup_imagingplane" do
      LookupImagingplane.stub(:find).with("37") { mock_lookup_imagingplane }
      get :show, :id => "37"
      assigns(:lookup_imagingplane).should be(mock_lookup_imagingplane)
    end
  end

  describe "GET new" do
    it "assigns a new lookup_imagingplane as @lookup_imagingplane" do
      LookupImagingplane.stub(:new) { mock_lookup_imagingplane }
      get :new
      assigns(:lookup_imagingplane).should be(mock_lookup_imagingplane)
    end
  end

  describe "GET edit" do
    it "assigns the requested lookup_imagingplane as @lookup_imagingplane" do
      LookupImagingplane.stub(:find).with("37") { mock_lookup_imagingplane }
      get :edit, :id => "37"
      assigns(:lookup_imagingplane).should be(mock_lookup_imagingplane)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lookup_imagingplane as @lookup_imagingplane" do
        LookupImagingplane.stub(:new).with({'these' => 'params'}) { mock_lookup_imagingplane(:save => true) }
        post :create, :lookup_imagingplane => {'these' => 'params'}
        assigns(:lookup_imagingplane).should be(mock_lookup_imagingplane)
      end

      it "redirects to the created lookup_imagingplane" do
        LookupImagingplane.stub(:new) { mock_lookup_imagingplane(:save => true) }
        post :create, :lookup_imagingplane => {}
        response.should redirect_to(lookup_imagingplane_url(mock_lookup_imagingplane))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lookup_imagingplane as @lookup_imagingplane" do
        LookupImagingplane.stub(:new).with({'these' => 'params'}) { mock_lookup_imagingplane(:save => false) }
        post :create, :lookup_imagingplane => {'these' => 'params'}
        assigns(:lookup_imagingplane).should be(mock_lookup_imagingplane)
      end

      it "re-renders the 'new' template" do
        LookupImagingplane.stub(:new) { mock_lookup_imagingplane(:save => false) }
        post :create, :lookup_imagingplane => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lookup_imagingplane" do
        LookupImagingplane.stub(:find).with("37") { mock_lookup_imagingplane }
        mock_lookup_imagingplane.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lookup_imagingplane => {'these' => 'params'}
      end

      it "assigns the requested lookup_imagingplane as @lookup_imagingplane" do
        LookupImagingplane.stub(:find) { mock_lookup_imagingplane(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lookup_imagingplane).should be(mock_lookup_imagingplane)
      end

      it "redirects to the lookup_imagingplane" do
        LookupImagingplane.stub(:find) { mock_lookup_imagingplane(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lookup_imagingplane_url(mock_lookup_imagingplane))
      end
    end

    describe "with invalid params" do
      it "assigns the lookup_imagingplane as @lookup_imagingplane" do
        LookupImagingplane.stub(:find) { mock_lookup_imagingplane(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lookup_imagingplane).should be(mock_lookup_imagingplane)
      end

      it "re-renders the 'edit' template" do
        LookupImagingplane.stub(:find) { mock_lookup_imagingplane(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lookup_imagingplane" do
      LookupImagingplane.stub(:find).with("37") { mock_lookup_imagingplane }
      mock_lookup_imagingplane.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lookup_imagingplanes list" do
      LookupImagingplane.stub(:find) { mock_lookup_imagingplane }
      delete :destroy, :id => "1"
      response.should redirect_to(lookup_imagingplanes_url)
    end
  end

end
