require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LookupHardwaresController do

  def mock_lookup_hardware(stubs={})
    @mock_lookup_hardware ||= mock_model(LookupHardware, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lookup_hardwares as @lookup_hardwares" do
      LookupHardware.stub(:all) { [mock_lookup_hardware] }
      get :index
      assigns(:lookup_hardwares).should eq([mock_lookup_hardware])
    end
  end

  describe "GET show" do
    it "assigns the requested lookup_hardware as @lookup_hardware" do
      LookupHardware.stub(:find).with("37") { mock_lookup_hardware }
      get :show, :id => "37"
      assigns(:lookup_hardware).should be(mock_lookup_hardware)
    end
  end

  describe "GET new" do
    it "assigns a new lookup_hardware as @lookup_hardware" do
      LookupHardware.stub(:new) { mock_lookup_hardware }
      get :new
      assigns(:lookup_hardware).should be(mock_lookup_hardware)
    end
  end

  describe "GET edit" do
    it "assigns the requested lookup_hardware as @lookup_hardware" do
      LookupHardware.stub(:find).with("37") { mock_lookup_hardware }
      get :edit, :id => "37"
      assigns(:lookup_hardware).should be(mock_lookup_hardware)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lookup_hardware as @lookup_hardware" do
        LookupHardware.stub(:new).with({'these' => 'params'}) { mock_lookup_hardware(:save => true) }
        post :create, :lookup_hardware => {'these' => 'params'}
        assigns(:lookup_hardware).should be(mock_lookup_hardware)
      end

      it "redirects to the created lookup_hardware" do
        LookupHardware.stub(:new) { mock_lookup_hardware(:save => true) }
        post :create, :lookup_hardware => {}
        response.should redirect_to(lookup_hardware_url(mock_lookup_hardware))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lookup_hardware as @lookup_hardware" do
        LookupHardware.stub(:new).with({'these' => 'params'}) { mock_lookup_hardware(:save => false) }
        post :create, :lookup_hardware => {'these' => 'params'}
        assigns(:lookup_hardware).should be(mock_lookup_hardware)
      end

      it "re-renders the 'new' template" do
        LookupHardware.stub(:new) { mock_lookup_hardware(:save => false) }
        post :create, :lookup_hardware => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lookup_hardware" do
        LookupHardware.stub(:find).with("37") { mock_lookup_hardware }
        mock_lookup_hardware.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lookup_hardware => {'these' => 'params'}
      end

      it "assigns the requested lookup_hardware as @lookup_hardware" do
        LookupHardware.stub(:find) { mock_lookup_hardware(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lookup_hardware).should be(mock_lookup_hardware)
      end

      it "redirects to the lookup_hardware" do
        LookupHardware.stub(:find) { mock_lookup_hardware(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lookup_hardware_url(mock_lookup_hardware))
      end
    end

    describe "with invalid params" do
      it "assigns the lookup_hardware as @lookup_hardware" do
        LookupHardware.stub(:find) { mock_lookup_hardware(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lookup_hardware).should be(mock_lookup_hardware)
      end

      it "re-renders the 'edit' template" do
        LookupHardware.stub(:find) { mock_lookup_hardware(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lookup_hardware" do
      LookupHardware.stub(:find).with("37") { mock_lookup_hardware }
      mock_lookup_hardware.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lookup_hardwares list" do
      LookupHardware.stub(:find) { mock_lookup_hardware }
      delete :destroy, :id => "1"
      response.should redirect_to(lookup_hardwares_url)
    end
  end

end
