require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LookupDrugfreqsController do

  def mock_lookup_drugfreq(stubs={})
    @mock_lookup_drugfreq ||= mock_model(LookupDrugfreq, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lookup_drugfreqs as @lookup_drugfreqs" do
      LookupDrugfreq.stub(:all) { [mock_lookup_drugfreq] }
      get :index
      assigns(:lookup_drugfreqs).should eq([mock_lookup_drugfreq])
    end
  end

  describe "GET show" do
    it "assigns the requested lookup_drugfreq as @lookup_drugfreq" do
      LookupDrugfreq.stub(:find).with("37") { mock_lookup_drugfreq }
      get :show, :id => "37"
      assigns(:lookup_drugfreq).should be(mock_lookup_drugfreq)
    end
  end

  describe "GET new" do
    it "assigns a new lookup_drugfreq as @lookup_drugfreq" do
      LookupDrugfreq.stub(:new) { mock_lookup_drugfreq }
      get :new
      assigns(:lookup_drugfreq).should be(mock_lookup_drugfreq)
    end
  end

  describe "GET edit" do
    it "assigns the requested lookup_drugfreq as @lookup_drugfreq" do
      LookupDrugfreq.stub(:find).with("37") { mock_lookup_drugfreq }
      get :edit, :id => "37"
      assigns(:lookup_drugfreq).should be(mock_lookup_drugfreq)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lookup_drugfreq as @lookup_drugfreq" do
        LookupDrugfreq.stub(:new).with({'these' => 'params'}) { mock_lookup_drugfreq(:save => true) }
        post :create, :lookup_drugfreq => {'these' => 'params'}
        assigns(:lookup_drugfreq).should be(mock_lookup_drugfreq)
      end

      it "redirects to the created lookup_drugfreq" do
        LookupDrugfreq.stub(:new) { mock_lookup_drugfreq(:save => true) }
        post :create, :lookup_drugfreq => {}
        response.should redirect_to(lookup_drugfreq_url(mock_lookup_drugfreq))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lookup_drugfreq as @lookup_drugfreq" do
        LookupDrugfreq.stub(:new).with({'these' => 'params'}) { mock_lookup_drugfreq(:save => false) }
        post :create, :lookup_drugfreq => {'these' => 'params'}
        assigns(:lookup_drugfreq).should be(mock_lookup_drugfreq)
      end

      it "re-renders the 'new' template" do
        LookupDrugfreq.stub(:new) { mock_lookup_drugfreq(:save => false) }
        post :create, :lookup_drugfreq => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lookup_drugfreq" do
        LookupDrugfreq.stub(:find).with("37") { mock_lookup_drugfreq }
        mock_lookup_drugfreq.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lookup_drugfreq => {'these' => 'params'}
      end

      it "assigns the requested lookup_drugfreq as @lookup_drugfreq" do
        LookupDrugfreq.stub(:find) { mock_lookup_drugfreq(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lookup_drugfreq).should be(mock_lookup_drugfreq)
      end

      it "redirects to the lookup_drugfreq" do
        LookupDrugfreq.stub(:find) { mock_lookup_drugfreq(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lookup_drugfreq_url(mock_lookup_drugfreq))
      end
    end

    describe "with invalid params" do
      it "assigns the lookup_drugfreq as @lookup_drugfreq" do
        LookupDrugfreq.stub(:find) { mock_lookup_drugfreq(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lookup_drugfreq).should be(mock_lookup_drugfreq)
      end

      it "re-renders the 'edit' template" do
        LookupDrugfreq.stub(:find) { mock_lookup_drugfreq(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lookup_drugfreq" do
      LookupDrugfreq.stub(:find).with("37") { mock_lookup_drugfreq }
      mock_lookup_drugfreq.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lookup_drugfreqs list" do
      LookupDrugfreq.stub(:find) { mock_lookup_drugfreq }
      delete :destroy, :id => "1"
      response.should redirect_to(lookup_drugfreqs_url)
    end
  end

end
