require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LookupRecruitsourcesController do

  def mock_lookup_recruitsource(stubs={})
    @mock_lookup_recruitsource ||= mock_model(LookupRecruitsource, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lookup_recruitsources as @lookup_recruitsources" do
      LookupRecruitsource.stub(:all) { [mock_lookup_recruitsource] }
      get :index
      assigns(:lookup_recruitsources).should eq([mock_lookup_recruitsource])
    end
  end

  describe "GET show" do
    it "assigns the requested lookup_recruitsource as @lookup_recruitsource" do
      LookupRecruitsource.stub(:find).with("37") { mock_lookup_recruitsource }
      get :show, :id => "37"
      assigns(:lookup_recruitsource).should be(mock_lookup_recruitsource)
    end
  end

  describe "GET new" do
    it "assigns a new lookup_recruitsource as @lookup_recruitsource" do
      LookupRecruitsource.stub(:new) { mock_lookup_recruitsource }
      get :new
      assigns(:lookup_recruitsource).should be(mock_lookup_recruitsource)
    end
  end

  describe "GET edit" do
    it "assigns the requested lookup_recruitsource as @lookup_recruitsource" do
      LookupRecruitsource.stub(:find).with("37") { mock_lookup_recruitsource }
      get :edit, :id => "37"
      assigns(:lookup_recruitsource).should be(mock_lookup_recruitsource)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lookup_recruitsource as @lookup_recruitsource" do
        LookupRecruitsource.stub(:new).with({'these' => 'params'}) { mock_lookup_recruitsource(:save => true) }
        post :create, :lookup_recruitsource => {'these' => 'params'}
        assigns(:lookup_recruitsource).should be(mock_lookup_recruitsource)
      end

      it "redirects to the created lookup_recruitsource" do
        LookupRecruitsource.stub(:new) { mock_lookup_recruitsource(:save => true) }
        post :create, :lookup_recruitsource => {}
        response.should redirect_to(lookup_recruitsource_url(mock_lookup_recruitsource))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lookup_recruitsource as @lookup_recruitsource" do
        LookupRecruitsource.stub(:new).with({'these' => 'params'}) { mock_lookup_recruitsource(:save => false) }
        post :create, :lookup_recruitsource => {'these' => 'params'}
        assigns(:lookup_recruitsource).should be(mock_lookup_recruitsource)
      end

      it "re-renders the 'new' template" do
        LookupRecruitsource.stub(:new) { mock_lookup_recruitsource(:save => false) }
        post :create, :lookup_recruitsource => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lookup_recruitsource" do
        LookupRecruitsource.stub(:find).with("37") { mock_lookup_recruitsource }
        mock_lookup_recruitsource.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lookup_recruitsource => {'these' => 'params'}
      end

      it "assigns the requested lookup_recruitsource as @lookup_recruitsource" do
        LookupRecruitsource.stub(:find) { mock_lookup_recruitsource(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lookup_recruitsource).should be(mock_lookup_recruitsource)
      end

      it "redirects to the lookup_recruitsource" do
        LookupRecruitsource.stub(:find) { mock_lookup_recruitsource(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lookup_recruitsource_url(mock_lookup_recruitsource))
      end
    end

    describe "with invalid params" do
      it "assigns the lookup_recruitsource as @lookup_recruitsource" do
        LookupRecruitsource.stub(:find) { mock_lookup_recruitsource(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lookup_recruitsource).should be(mock_lookup_recruitsource)
      end

      it "re-renders the 'edit' template" do
        LookupRecruitsource.stub(:find) { mock_lookup_recruitsource(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lookup_recruitsource" do
      LookupRecruitsource.stub(:find).with("37") { mock_lookup_recruitsource }
      mock_lookup_recruitsource.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lookup_recruitsources list" do
      LookupRecruitsource.stub(:find) { mock_lookup_recruitsource }
      delete :destroy, :id => "1"
      response.should redirect_to(lookup_recruitsources_url)
    end
  end

end
