require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LookupDrugunitsController do

  def mock_lookup_drugunit(stubs={})
    @mock_lookup_drugunit ||= mock_model(LookupDrugunit, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lookup_drugunits as @lookup_drugunits" do
      LookupDrugunit.stub(:all) { [mock_lookup_drugunit] }
      get :index
      assigns(:lookup_drugunits).should eq([mock_lookup_drugunit])
    end
  end

  describe "GET show" do
    it "assigns the requested lookup_drugunit as @lookup_drugunit" do
      LookupDrugunit.stub(:find).with("37") { mock_lookup_drugunit }
      get :show, :id => "37"
      assigns(:lookup_drugunit).should be(mock_lookup_drugunit)
    end
  end

  describe "GET new" do
    it "assigns a new lookup_drugunit as @lookup_drugunit" do
      LookupDrugunit.stub(:new) { mock_lookup_drugunit }
      get :new
      assigns(:lookup_drugunit).should be(mock_lookup_drugunit)
    end
  end

  describe "GET edit" do
    it "assigns the requested lookup_drugunit as @lookup_drugunit" do
      LookupDrugunit.stub(:find).with("37") { mock_lookup_drugunit }
      get :edit, :id => "37"
      assigns(:lookup_drugunit).should be(mock_lookup_drugunit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lookup_drugunit as @lookup_drugunit" do
        LookupDrugunit.stub(:new).with({'these' => 'params'}) { mock_lookup_drugunit(:save => true) }
        post :create, :lookup_drugunit => {'these' => 'params'}
        assigns(:lookup_drugunit).should be(mock_lookup_drugunit)
      end

      it "redirects to the created lookup_drugunit" do
        LookupDrugunit.stub(:new) { mock_lookup_drugunit(:save => true) }
        post :create, :lookup_drugunit => {}
        response.should redirect_to(lookup_drugunit_url(mock_lookup_drugunit))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lookup_drugunit as @lookup_drugunit" do
        LookupDrugunit.stub(:new).with({'these' => 'params'}) { mock_lookup_drugunit(:save => false) }
        post :create, :lookup_drugunit => {'these' => 'params'}
        assigns(:lookup_drugunit).should be(mock_lookup_drugunit)
      end

      it "re-renders the 'new' template" do
        LookupDrugunit.stub(:new) { mock_lookup_drugunit(:save => false) }
        post :create, :lookup_drugunit => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lookup_drugunit" do
        LookupDrugunit.stub(:find).with("37") { mock_lookup_drugunit }
        mock_lookup_drugunit.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lookup_drugunit => {'these' => 'params'}
      end

      it "assigns the requested lookup_drugunit as @lookup_drugunit" do
        LookupDrugunit.stub(:find) { mock_lookup_drugunit(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lookup_drugunit).should be(mock_lookup_drugunit)
      end

      it "redirects to the lookup_drugunit" do
        LookupDrugunit.stub(:find) { mock_lookup_drugunit(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lookup_drugunit_url(mock_lookup_drugunit))
      end
    end

    describe "with invalid params" do
      it "assigns the lookup_drugunit as @lookup_drugunit" do
        LookupDrugunit.stub(:find) { mock_lookup_drugunit(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lookup_drugunit).should be(mock_lookup_drugunit)
      end

      it "re-renders the 'edit' template" do
        LookupDrugunit.stub(:find) { mock_lookup_drugunit(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lookup_drugunit" do
      LookupDrugunit.stub(:find).with("37") { mock_lookup_drugunit }
      mock_lookup_drugunit.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lookup_drugunits list" do
      LookupDrugunit.stub(:find) { mock_lookup_drugunit }
      delete :destroy, :id => "1"
      response.should redirect_to(lookup_drugunits_url)
    end
  end

end
