require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LookupRelationshipsController do

  def mock_lookup_relationship(stubs={})
    @mock_lookup_relationship ||= mock_model(LookupRelationship, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lookup_relationships as @lookup_relationships" do
      LookupRelationship.stub(:all) { [mock_lookup_relationship] }
      get :index
      assigns(:lookup_relationships).should eq([mock_lookup_relationship])
    end
  end

  describe "GET show" do
    it "assigns the requested lookup_relationship as @lookup_relationship" do
      LookupRelationship.stub(:find).with("37") { mock_lookup_relationship }
      get :show, :id => "37"
      assigns(:lookup_relationship).should be(mock_lookup_relationship)
    end
  end

  describe "GET new" do
    it "assigns a new lookup_relationship as @lookup_relationship" do
      LookupRelationship.stub(:new) { mock_lookup_relationship }
      get :new
      assigns(:lookup_relationship).should be(mock_lookup_relationship)
    end
  end

  describe "GET edit" do
    it "assigns the requested lookup_relationship as @lookup_relationship" do
      LookupRelationship.stub(:find).with("37") { mock_lookup_relationship }
      get :edit, :id => "37"
      assigns(:lookup_relationship).should be(mock_lookup_relationship)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lookup_relationship as @lookup_relationship" do
        LookupRelationship.stub(:new).with({'these' => 'params'}) { mock_lookup_relationship(:save => true) }
        post :create, :lookup_relationship => {'these' => 'params'}
        assigns(:lookup_relationship).should be(mock_lookup_relationship)
      end

      it "redirects to the created lookup_relationship" do
        LookupRelationship.stub(:new) { mock_lookup_relationship(:save => true) }
        post :create, :lookup_relationship => {}
        response.should redirect_to(lookup_relationship_url(mock_lookup_relationship))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lookup_relationship as @lookup_relationship" do
        LookupRelationship.stub(:new).with({'these' => 'params'}) { mock_lookup_relationship(:save => false) }
        post :create, :lookup_relationship => {'these' => 'params'}
        assigns(:lookup_relationship).should be(mock_lookup_relationship)
      end

      it "re-renders the 'new' template" do
        LookupRelationship.stub(:new) { mock_lookup_relationship(:save => false) }
        post :create, :lookup_relationship => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lookup_relationship" do
        LookupRelationship.stub(:find).with("37") { mock_lookup_relationship }
        mock_lookup_relationship.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lookup_relationship => {'these' => 'params'}
      end

      it "assigns the requested lookup_relationship as @lookup_relationship" do
        LookupRelationship.stub(:find) { mock_lookup_relationship(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lookup_relationship).should be(mock_lookup_relationship)
      end

      it "redirects to the lookup_relationship" do
        LookupRelationship.stub(:find) { mock_lookup_relationship(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lookup_relationship_url(mock_lookup_relationship))
      end
    end

    describe "with invalid params" do
      it "assigns the lookup_relationship as @lookup_relationship" do
        LookupRelationship.stub(:find) { mock_lookup_relationship(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lookup_relationship).should be(mock_lookup_relationship)
      end

      it "re-renders the 'edit' template" do
        LookupRelationship.stub(:find) { mock_lookup_relationship(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lookup_relationship" do
      LookupRelationship.stub(:find).with("37") { mock_lookup_relationship }
      mock_lookup_relationship.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lookup_relationships list" do
      LookupRelationship.stub(:find) { mock_lookup_relationship }
      delete :destroy, :id => "1"
      response.should redirect_to(lookup_relationships_url)
    end
  end

end
