require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LookupEligibilityoutcomesController do

  def mock_lookup_eligibilityoutcome(stubs={})
    @mock_lookup_eligibilityoutcome ||= mock_model(LookupEligibilityoutcome, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lookup_eligibilityoutcomes as @lookup_eligibilityoutcomes" do
      LookupEligibilityoutcome.stub(:all) { [mock_lookup_eligibilityoutcome] }
      get :index
      assigns(:lookup_eligibilityoutcomes).should eq([mock_lookup_eligibilityoutcome])
    end
  end

  describe "GET show" do
    it "assigns the requested lookup_eligibilityoutcome as @lookup_eligibilityoutcome" do
      LookupEligibilityoutcome.stub(:find).with("37") { mock_lookup_eligibilityoutcome }
      get :show, :id => "37"
      assigns(:lookup_eligibilityoutcome).should be(mock_lookup_eligibilityoutcome)
    end
  end

  describe "GET new" do
    it "assigns a new lookup_eligibilityoutcome as @lookup_eligibilityoutcome" do
      LookupEligibilityoutcome.stub(:new) { mock_lookup_eligibilityoutcome }
      get :new
      assigns(:lookup_eligibilityoutcome).should be(mock_lookup_eligibilityoutcome)
    end
  end

  describe "GET edit" do
    it "assigns the requested lookup_eligibilityoutcome as @lookup_eligibilityoutcome" do
      LookupEligibilityoutcome.stub(:find).with("37") { mock_lookup_eligibilityoutcome }
      get :edit, :id => "37"
      assigns(:lookup_eligibilityoutcome).should be(mock_lookup_eligibilityoutcome)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lookup_eligibilityoutcome as @lookup_eligibilityoutcome" do
        LookupEligibilityoutcome.stub(:new).with({'these' => 'params'}) { mock_lookup_eligibilityoutcome(:save => true) }
        post :create, :lookup_eligibilityoutcome => {'these' => 'params'}
        assigns(:lookup_eligibilityoutcome).should be(mock_lookup_eligibilityoutcome)
      end

      it "redirects to the created lookup_eligibilityoutcome" do
        LookupEligibilityoutcome.stub(:new) { mock_lookup_eligibilityoutcome(:save => true) }
        post :create, :lookup_eligibilityoutcome => {}
        response.should redirect_to(lookup_eligibilityoutcome_url(mock_lookup_eligibilityoutcome))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lookup_eligibilityoutcome as @lookup_eligibilityoutcome" do
        LookupEligibilityoutcome.stub(:new).with({'these' => 'params'}) { mock_lookup_eligibilityoutcome(:save => false) }
        post :create, :lookup_eligibilityoutcome => {'these' => 'params'}
        assigns(:lookup_eligibilityoutcome).should be(mock_lookup_eligibilityoutcome)
      end

      it "re-renders the 'new' template" do
        LookupEligibilityoutcome.stub(:new) { mock_lookup_eligibilityoutcome(:save => false) }
        post :create, :lookup_eligibilityoutcome => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lookup_eligibilityoutcome" do
        LookupEligibilityoutcome.stub(:find).with("37") { mock_lookup_eligibilityoutcome }
        mock_lookup_eligibilityoutcome.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lookup_eligibilityoutcome => {'these' => 'params'}
      end

      it "assigns the requested lookup_eligibilityoutcome as @lookup_eligibilityoutcome" do
        LookupEligibilityoutcome.stub(:find) { mock_lookup_eligibilityoutcome(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lookup_eligibilityoutcome).should be(mock_lookup_eligibilityoutcome)
      end

      it "redirects to the lookup_eligibilityoutcome" do
        LookupEligibilityoutcome.stub(:find) { mock_lookup_eligibilityoutcome(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lookup_eligibilityoutcome_url(mock_lookup_eligibilityoutcome))
      end
    end

    describe "with invalid params" do
      it "assigns the lookup_eligibilityoutcome as @lookup_eligibilityoutcome" do
        LookupEligibilityoutcome.stub(:find) { mock_lookup_eligibilityoutcome(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lookup_eligibilityoutcome).should be(mock_lookup_eligibilityoutcome)
      end

      it "re-renders the 'edit' template" do
        LookupEligibilityoutcome.stub(:find) { mock_lookup_eligibilityoutcome(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lookup_eligibilityoutcome" do
      LookupEligibilityoutcome.stub(:find).with("37") { mock_lookup_eligibilityoutcome }
      mock_lookup_eligibilityoutcome.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lookup_eligibilityoutcomes list" do
      LookupEligibilityoutcome.stub(:find) { mock_lookup_eligibilityoutcome }
      delete :destroy, :id => "1"
      response.should redirect_to(lookup_eligibilityoutcomes_url)
    end
  end

end
