require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LookupPettracesController do

  def mock_lookup_pettrace(stubs={})
    @mock_lookup_pettrace ||= mock_model(LookupPettrace, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lookup_pettraces as @lookup_pettraces" do
      LookupPettrace.stub(:all) { [mock_lookup_pettrace] }
      get :index
      assigns(:lookup_pettraces).should eq([mock_lookup_pettrace])
    end
  end

  describe "GET show" do
    it "assigns the requested lookup_pettrace as @lookup_pettrace" do
      LookupPettrace.stub(:find).with("37") { mock_lookup_pettrace }
      get :show, :id => "37"
      assigns(:lookup_pettrace).should be(mock_lookup_pettrace)
    end
  end

  describe "GET new" do
    it "assigns a new lookup_pettrace as @lookup_pettrace" do
      LookupPettrace.stub(:new) { mock_lookup_pettrace }
      get :new
      assigns(:lookup_pettrace).should be(mock_lookup_pettrace)
    end
  end

  describe "GET edit" do
    it "assigns the requested lookup_pettrace as @lookup_pettrace" do
      LookupPettrace.stub(:find).with("37") { mock_lookup_pettrace }
      get :edit, :id => "37"
      assigns(:lookup_pettrace).should be(mock_lookup_pettrace)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lookup_pettrace as @lookup_pettrace" do
        LookupPettrace.stub(:new).with({'these' => 'params'}) { mock_lookup_pettrace(:save => true) }
        post :create, :lookup_pettrace => {'these' => 'params'}
        assigns(:lookup_pettrace).should be(mock_lookup_pettrace)
      end

      it "redirects to the created lookup_pettrace" do
        LookupPettrace.stub(:new) { mock_lookup_pettrace(:save => true) }
        post :create, :lookup_pettrace => {}
        response.should redirect_to(lookup_pettrace_url(mock_lookup_pettrace))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lookup_pettrace as @lookup_pettrace" do
        LookupPettrace.stub(:new).with({'these' => 'params'}) { mock_lookup_pettrace(:save => false) }
        post :create, :lookup_pettrace => {'these' => 'params'}
        assigns(:lookup_pettrace).should be(mock_lookup_pettrace)
      end

      it "re-renders the 'new' template" do
        LookupPettrace.stub(:new) { mock_lookup_pettrace(:save => false) }
        post :create, :lookup_pettrace => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lookup_pettrace" do
        LookupPettrace.stub(:find).with("37") { mock_lookup_pettrace }
        mock_lookup_pettrace.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lookup_pettrace => {'these' => 'params'}
      end

      it "assigns the requested lookup_pettrace as @lookup_pettrace" do
        LookupPettrace.stub(:find) { mock_lookup_pettrace(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lookup_pettrace).should be(mock_lookup_pettrace)
      end

      it "redirects to the lookup_pettrace" do
        LookupPettrace.stub(:find) { mock_lookup_pettrace(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lookup_pettrace_url(mock_lookup_pettrace))
      end
    end

    describe "with invalid params" do
      it "assigns the lookup_pettrace as @lookup_pettrace" do
        LookupPettrace.stub(:find) { mock_lookup_pettrace(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lookup_pettrace).should be(mock_lookup_pettrace)
      end

      it "re-renders the 'edit' template" do
        LookupPettrace.stub(:find) { mock_lookup_pettrace(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lookup_pettrace" do
      LookupPettrace.stub(:find).with("37") { mock_lookup_pettrace }
      mock_lookup_pettrace.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lookup_pettraces list" do
      LookupPettrace.stub(:find) { mock_lookup_pettrace }
      delete :destroy, :id => "1"
      response.should redirect_to(lookup_pettraces_url)
    end
  end

end
