require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LookupDemographicmaritialstatusesController do

  def mock_lookup_demographicmaritialstatus(stubs={})
    @mock_lookup_demographicmaritialstatus ||= mock_model(LookupDemographicmaritialstatus, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lookup_demographicmaritialstatuses as @lookup_demographicmaritialstatuses" do
      LookupDemographicmaritialstatus.stub(:all) { [mock_lookup_demographicmaritialstatus] }
      get :index
      assigns(:lookup_demographicmaritialstatuses).should eq([mock_lookup_demographicmaritialstatus])
    end
  end

  describe "GET show" do
    it "assigns the requested lookup_demographicmaritialstatus as @lookup_demographicmaritialstatus" do
      LookupDemographicmaritialstatus.stub(:find).with("37") { mock_lookup_demographicmaritialstatus }
      get :show, :id => "37"
      assigns(:lookup_demographicmaritialstatus).should be(mock_lookup_demographicmaritialstatus)
    end
  end

  describe "GET new" do
    it "assigns a new lookup_demographicmaritialstatus as @lookup_demographicmaritialstatus" do
      LookupDemographicmaritialstatus.stub(:new) { mock_lookup_demographicmaritialstatus }
      get :new
      assigns(:lookup_demographicmaritialstatus).should be(mock_lookup_demographicmaritialstatus)
    end
  end

  describe "GET edit" do
    it "assigns the requested lookup_demographicmaritialstatus as @lookup_demographicmaritialstatus" do
      LookupDemographicmaritialstatus.stub(:find).with("37") { mock_lookup_demographicmaritialstatus }
      get :edit, :id => "37"
      assigns(:lookup_demographicmaritialstatus).should be(mock_lookup_demographicmaritialstatus)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lookup_demographicmaritialstatus as @lookup_demographicmaritialstatus" do
        LookupDemographicmaritialstatus.stub(:new).with({'these' => 'params'}) { mock_lookup_demographicmaritialstatus(:save => true) }
        post :create, :lookup_demographicmaritialstatus => {'these' => 'params'}
        assigns(:lookup_demographicmaritialstatus).should be(mock_lookup_demographicmaritialstatus)
      end

      it "redirects to the created lookup_demographicmaritialstatus" do
        LookupDemographicmaritialstatus.stub(:new) { mock_lookup_demographicmaritialstatus(:save => true) }
        post :create, :lookup_demographicmaritialstatus => {}
        response.should redirect_to(lookup_demographicmaritialstatus_url(mock_lookup_demographicmaritialstatus))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lookup_demographicmaritialstatus as @lookup_demographicmaritialstatus" do
        LookupDemographicmaritialstatus.stub(:new).with({'these' => 'params'}) { mock_lookup_demographicmaritialstatus(:save => false) }
        post :create, :lookup_demographicmaritialstatus => {'these' => 'params'}
        assigns(:lookup_demographicmaritialstatus).should be(mock_lookup_demographicmaritialstatus)
      end

      it "re-renders the 'new' template" do
        LookupDemographicmaritialstatus.stub(:new) { mock_lookup_demographicmaritialstatus(:save => false) }
        post :create, :lookup_demographicmaritialstatus => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lookup_demographicmaritialstatus" do
        LookupDemographicmaritialstatus.stub(:find).with("37") { mock_lookup_demographicmaritialstatus }
        mock_lookup_demographicmaritialstatus.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lookup_demographicmaritialstatus => {'these' => 'params'}
      end

      it "assigns the requested lookup_demographicmaritialstatus as @lookup_demographicmaritialstatus" do
        LookupDemographicmaritialstatus.stub(:find) { mock_lookup_demographicmaritialstatus(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lookup_demographicmaritialstatus).should be(mock_lookup_demographicmaritialstatus)
      end

      it "redirects to the lookup_demographicmaritialstatus" do
        LookupDemographicmaritialstatus.stub(:find) { mock_lookup_demographicmaritialstatus(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lookup_demographicmaritialstatus_url(mock_lookup_demographicmaritialstatus))
      end
    end

    describe "with invalid params" do
      it "assigns the lookup_demographicmaritialstatus as @lookup_demographicmaritialstatus" do
        LookupDemographicmaritialstatus.stub(:find) { mock_lookup_demographicmaritialstatus(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lookup_demographicmaritialstatus).should be(mock_lookup_demographicmaritialstatus)
      end

      it "re-renders the 'edit' template" do
        LookupDemographicmaritialstatus.stub(:find) { mock_lookup_demographicmaritialstatus(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lookup_demographicmaritialstatus" do
      LookupDemographicmaritialstatus.stub(:find).with("37") { mock_lookup_demographicmaritialstatus }
      mock_lookup_demographicmaritialstatus.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lookup_demographicmaritialstatuses list" do
      LookupDemographicmaritialstatus.stub(:find) { mock_lookup_demographicmaritialstatus }
      delete :destroy, :id => "1"
      response.should redirect_to(lookup_demographicmaritialstatuses_url)
    end
  end

end
