require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LookupDrugcodesController do

  def mock_lookup_drugcode(stubs={})
    @mock_lookup_drugcode ||= mock_model(LookupDrugcode, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lookup_drugcodes as @lookup_drugcodes" do
      LookupDrugcode.stub(:all) { [mock_lookup_drugcode] }
      get :index
      assigns(:lookup_drugcodes).should eq([mock_lookup_drugcode])
    end
  end

  describe "GET show" do
    it "assigns the requested lookup_drugcode as @lookup_drugcode" do
      LookupDrugcode.stub(:find).with("37") { mock_lookup_drugcode }
      get :show, :id => "37"
      assigns(:lookup_drugcode).should be(mock_lookup_drugcode)
    end
  end

  describe "GET new" do
    it "assigns a new lookup_drugcode as @lookup_drugcode" do
      LookupDrugcode.stub(:new) { mock_lookup_drugcode }
      get :new
      assigns(:lookup_drugcode).should be(mock_lookup_drugcode)
    end
  end

  describe "GET edit" do
    it "assigns the requested lookup_drugcode as @lookup_drugcode" do
      LookupDrugcode.stub(:find).with("37") { mock_lookup_drugcode }
      get :edit, :id => "37"
      assigns(:lookup_drugcode).should be(mock_lookup_drugcode)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lookup_drugcode as @lookup_drugcode" do
        LookupDrugcode.stub(:new).with({'these' => 'params'}) { mock_lookup_drugcode(:save => true) }
        post :create, :lookup_drugcode => {'these' => 'params'}
        assigns(:lookup_drugcode).should be(mock_lookup_drugcode)
      end

      it "redirects to the created lookup_drugcode" do
        LookupDrugcode.stub(:new) { mock_lookup_drugcode(:save => true) }
        post :create, :lookup_drugcode => {}
        response.should redirect_to(lookup_drugcode_url(mock_lookup_drugcode))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lookup_drugcode as @lookup_drugcode" do
        LookupDrugcode.stub(:new).with({'these' => 'params'}) { mock_lookup_drugcode(:save => false) }
        post :create, :lookup_drugcode => {'these' => 'params'}
        assigns(:lookup_drugcode).should be(mock_lookup_drugcode)
      end

      it "re-renders the 'new' template" do
        LookupDrugcode.stub(:new) { mock_lookup_drugcode(:save => false) }
        post :create, :lookup_drugcode => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lookup_drugcode" do
        LookupDrugcode.stub(:find).with("37") { mock_lookup_drugcode }
        mock_lookup_drugcode.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lookup_drugcode => {'these' => 'params'}
      end

      it "assigns the requested lookup_drugcode as @lookup_drugcode" do
        LookupDrugcode.stub(:find) { mock_lookup_drugcode(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lookup_drugcode).should be(mock_lookup_drugcode)
      end

      it "redirects to the lookup_drugcode" do
        LookupDrugcode.stub(:find) { mock_lookup_drugcode(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lookup_drugcode_url(mock_lookup_drugcode))
      end
    end

    describe "with invalid params" do
      it "assigns the lookup_drugcode as @lookup_drugcode" do
        LookupDrugcode.stub(:find) { mock_lookup_drugcode(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lookup_drugcode).should be(mock_lookup_drugcode)
      end

      it "re-renders the 'edit' template" do
        LookupDrugcode.stub(:find) { mock_lookup_drugcode(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lookup_drugcode" do
      LookupDrugcode.stub(:find).with("37") { mock_lookup_drugcode }
      mock_lookup_drugcode.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lookup_drugcodes list" do
      LookupDrugcode.stub(:find) { mock_lookup_drugcode }
      delete :destroy, :id => "1"
      response.should redirect_to(lookup_drugcodes_url)
    end
  end

end
