require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LookupCohortsController do

  def mock_lookup_cohort(stubs={})
    @mock_lookup_cohort ||= mock_model(LookupCohort, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lookup_cohorts as @lookup_cohorts" do
      LookupCohort.stub(:all) { [mock_lookup_cohort] }
      get :index
      assigns(:lookup_cohorts).should eq([mock_lookup_cohort])
    end
  end

  describe "GET show" do
    it "assigns the requested lookup_cohort as @lookup_cohort" do
      LookupCohort.stub(:find).with("37") { mock_lookup_cohort }
      get :show, :id => "37"
      assigns(:lookup_cohort).should be(mock_lookup_cohort)
    end
  end

  describe "GET new" do
    it "assigns a new lookup_cohort as @lookup_cohort" do
      LookupCohort.stub(:new) { mock_lookup_cohort }
      get :new
      assigns(:lookup_cohort).should be(mock_lookup_cohort)
    end
  end

  describe "GET edit" do
    it "assigns the requested lookup_cohort as @lookup_cohort" do
      LookupCohort.stub(:find).with("37") { mock_lookup_cohort }
      get :edit, :id => "37"
      assigns(:lookup_cohort).should be(mock_lookup_cohort)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lookup_cohort as @lookup_cohort" do
        LookupCohort.stub(:new).with({'these' => 'params'}) { mock_lookup_cohort(:save => true) }
        post :create, :lookup_cohort => {'these' => 'params'}
        assigns(:lookup_cohort).should be(mock_lookup_cohort)
      end

      it "redirects to the created lookup_cohort" do
        LookupCohort.stub(:new) { mock_lookup_cohort(:save => true) }
        post :create, :lookup_cohort => {}
        response.should redirect_to(lookup_cohort_url(mock_lookup_cohort))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lookup_cohort as @lookup_cohort" do
        LookupCohort.stub(:new).with({'these' => 'params'}) { mock_lookup_cohort(:save => false) }
        post :create, :lookup_cohort => {'these' => 'params'}
        assigns(:lookup_cohort).should be(mock_lookup_cohort)
      end

      it "re-renders the 'new' template" do
        LookupCohort.stub(:new) { mock_lookup_cohort(:save => false) }
        post :create, :lookup_cohort => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lookup_cohort" do
        LookupCohort.stub(:find).with("37") { mock_lookup_cohort }
        mock_lookup_cohort.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lookup_cohort => {'these' => 'params'}
      end

      it "assigns the requested lookup_cohort as @lookup_cohort" do
        LookupCohort.stub(:find) { mock_lookup_cohort(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lookup_cohort).should be(mock_lookup_cohort)
      end

      it "redirects to the lookup_cohort" do
        LookupCohort.stub(:find) { mock_lookup_cohort(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lookup_cohort_url(mock_lookup_cohort))
      end
    end

    describe "with invalid params" do
      it "assigns the lookup_cohort as @lookup_cohort" do
        LookupCohort.stub(:find) { mock_lookup_cohort(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lookup_cohort).should be(mock_lookup_cohort)
      end

      it "re-renders the 'edit' template" do
        LookupCohort.stub(:find) { mock_lookup_cohort(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lookup_cohort" do
      LookupCohort.stub(:find).with("37") { mock_lookup_cohort }
      mock_lookup_cohort.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lookup_cohorts list" do
      LookupCohort.stub(:find) { mock_lookup_cohort }
      delete :destroy, :id => "1"
      response.should redirect_to(lookup_cohorts_url)
    end
  end

end
