require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LookupCogstatusesController do

  def mock_lookup_cogstatus(stubs={})
    @mock_lookup_cogstatus ||= mock_model(LookupCogstatus, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lookup_cogstatuses as @lookup_cogstatuses" do
      LookupCogstatus.stub(:all) { [mock_lookup_cogstatus] }
      get :index
      assigns(:lookup_cogstatuses).should eq([mock_lookup_cogstatus])
    end
  end

  describe "GET show" do
    it "assigns the requested lookup_cogstatus as @lookup_cogstatus" do
      LookupCogstatus.stub(:find).with("37") { mock_lookup_cogstatus }
      get :show, :id => "37"
      assigns(:lookup_cogstatus).should be(mock_lookup_cogstatus)
    end
  end

  describe "GET new" do
    it "assigns a new lookup_cogstatus as @lookup_cogstatus" do
      LookupCogstatus.stub(:new) { mock_lookup_cogstatus }
      get :new
      assigns(:lookup_cogstatus).should be(mock_lookup_cogstatus)
    end
  end

  describe "GET edit" do
    it "assigns the requested lookup_cogstatus as @lookup_cogstatus" do
      LookupCogstatus.stub(:find).with("37") { mock_lookup_cogstatus }
      get :edit, :id => "37"
      assigns(:lookup_cogstatus).should be(mock_lookup_cogstatus)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lookup_cogstatus as @lookup_cogstatus" do
        LookupCogstatus.stub(:new).with({'these' => 'params'}) { mock_lookup_cogstatus(:save => true) }
        post :create, :lookup_cogstatus => {'these' => 'params'}
        assigns(:lookup_cogstatus).should be(mock_lookup_cogstatus)
      end

      it "redirects to the created lookup_cogstatus" do
        LookupCogstatus.stub(:new) { mock_lookup_cogstatus(:save => true) }
        post :create, :lookup_cogstatus => {}
        response.should redirect_to(lookup_cogstatus_url(mock_lookup_cogstatus))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lookup_cogstatus as @lookup_cogstatus" do
        LookupCogstatus.stub(:new).with({'these' => 'params'}) { mock_lookup_cogstatus(:save => false) }
        post :create, :lookup_cogstatus => {'these' => 'params'}
        assigns(:lookup_cogstatus).should be(mock_lookup_cogstatus)
      end

      it "re-renders the 'new' template" do
        LookupCogstatus.stub(:new) { mock_lookup_cogstatus(:save => false) }
        post :create, :lookup_cogstatus => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lookup_cogstatus" do
        LookupCogstatus.stub(:find).with("37") { mock_lookup_cogstatus }
        mock_lookup_cogstatus.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lookup_cogstatus => {'these' => 'params'}
      end

      it "assigns the requested lookup_cogstatus as @lookup_cogstatus" do
        LookupCogstatus.stub(:find) { mock_lookup_cogstatus(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lookup_cogstatus).should be(mock_lookup_cogstatus)
      end

      it "redirects to the lookup_cogstatus" do
        LookupCogstatus.stub(:find) { mock_lookup_cogstatus(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lookup_cogstatus_url(mock_lookup_cogstatus))
      end
    end

    describe "with invalid params" do
      it "assigns the lookup_cogstatus as @lookup_cogstatus" do
        LookupCogstatus.stub(:find) { mock_lookup_cogstatus(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lookup_cogstatus).should be(mock_lookup_cogstatus)
      end

      it "re-renders the 'edit' template" do
        LookupCogstatus.stub(:find) { mock_lookup_cogstatus(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lookup_cogstatus" do
      LookupCogstatus.stub(:find).with("37") { mock_lookup_cogstatus }
      mock_lookup_cogstatus.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lookup_cogstatuses list" do
      LookupCogstatus.stub(:find) { mock_lookup_cogstatus }
      delete :destroy, :id => "1"
      response.should redirect_to(lookup_cogstatuses_url)
    end
  end

end
