require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LookupBvmtpercentilesController do

  def mock_lookup_bvmtpercentile(stubs={})
    @mock_lookup_bvmtpercentile ||= mock_model(LookupBvmtpercentile, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lookup_bvmtpercentiles as @lookup_bvmtpercentiles" do
      LookupBvmtpercentile.stub(:all) { [mock_lookup_bvmtpercentile] }
      get :index
      assigns(:lookup_bvmtpercentiles).should eq([mock_lookup_bvmtpercentile])
    end
  end

  describe "GET show" do
    it "assigns the requested lookup_bvmtpercentile as @lookup_bvmtpercentile" do
      LookupBvmtpercentile.stub(:find).with("37") { mock_lookup_bvmtpercentile }
      get :show, :id => "37"
      assigns(:lookup_bvmtpercentile).should be(mock_lookup_bvmtpercentile)
    end
  end

  describe "GET new" do
    it "assigns a new lookup_bvmtpercentile as @lookup_bvmtpercentile" do
      LookupBvmtpercentile.stub(:new) { mock_lookup_bvmtpercentile }
      get :new
      assigns(:lookup_bvmtpercentile).should be(mock_lookup_bvmtpercentile)
    end
  end

  describe "GET edit" do
    it "assigns the requested lookup_bvmtpercentile as @lookup_bvmtpercentile" do
      LookupBvmtpercentile.stub(:find).with("37") { mock_lookup_bvmtpercentile }
      get :edit, :id => "37"
      assigns(:lookup_bvmtpercentile).should be(mock_lookup_bvmtpercentile)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lookup_bvmtpercentile as @lookup_bvmtpercentile" do
        LookupBvmtpercentile.stub(:new).with({'these' => 'params'}) { mock_lookup_bvmtpercentile(:save => true) }
        post :create, :lookup_bvmtpercentile => {'these' => 'params'}
        assigns(:lookup_bvmtpercentile).should be(mock_lookup_bvmtpercentile)
      end

      it "redirects to the created lookup_bvmtpercentile" do
        LookupBvmtpercentile.stub(:new) { mock_lookup_bvmtpercentile(:save => true) }
        post :create, :lookup_bvmtpercentile => {}
        response.should redirect_to(lookup_bvmtpercentile_url(mock_lookup_bvmtpercentile))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lookup_bvmtpercentile as @lookup_bvmtpercentile" do
        LookupBvmtpercentile.stub(:new).with({'these' => 'params'}) { mock_lookup_bvmtpercentile(:save => false) }
        post :create, :lookup_bvmtpercentile => {'these' => 'params'}
        assigns(:lookup_bvmtpercentile).should be(mock_lookup_bvmtpercentile)
      end

      it "re-renders the 'new' template" do
        LookupBvmtpercentile.stub(:new) { mock_lookup_bvmtpercentile(:save => false) }
        post :create, :lookup_bvmtpercentile => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lookup_bvmtpercentile" do
        LookupBvmtpercentile.stub(:find).with("37") { mock_lookup_bvmtpercentile }
        mock_lookup_bvmtpercentile.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lookup_bvmtpercentile => {'these' => 'params'}
      end

      it "assigns the requested lookup_bvmtpercentile as @lookup_bvmtpercentile" do
        LookupBvmtpercentile.stub(:find) { mock_lookup_bvmtpercentile(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lookup_bvmtpercentile).should be(mock_lookup_bvmtpercentile)
      end

      it "redirects to the lookup_bvmtpercentile" do
        LookupBvmtpercentile.stub(:find) { mock_lookup_bvmtpercentile(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lookup_bvmtpercentile_url(mock_lookup_bvmtpercentile))
      end
    end

    describe "with invalid params" do
      it "assigns the lookup_bvmtpercentile as @lookup_bvmtpercentile" do
        LookupBvmtpercentile.stub(:find) { mock_lookup_bvmtpercentile(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lookup_bvmtpercentile).should be(mock_lookup_bvmtpercentile)
      end

      it "re-renders the 'edit' template" do
        LookupBvmtpercentile.stub(:find) { mock_lookup_bvmtpercentile(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lookup_bvmtpercentile" do
      LookupBvmtpercentile.stub(:find).with("37") { mock_lookup_bvmtpercentile }
      mock_lookup_bvmtpercentile.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lookup_bvmtpercentiles list" do
      LookupBvmtpercentile.stub(:find) { mock_lookup_bvmtpercentile }
      delete :destroy, :id => "1"
      response.should redirect_to(lookup_bvmtpercentiles_url)
    end
  end

end
