require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LookupDemographicrelativerelationshipsController do

  def mock_lookup_demographicrelativerelationship(stubs={})
    @mock_lookup_demographicrelativerelationship ||= mock_model(LookupDemographicrelativerelationship, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lookup_demographicrelativerelationships as @lookup_demographicrelativerelationships" do
      LookupDemographicrelativerelationship.stub(:all) { [mock_lookup_demographicrelativerelationship] }
      get :index
      assigns(:lookup_demographicrelativerelationships).should eq([mock_lookup_demographicrelativerelationship])
    end
  end

  describe "GET show" do
    it "assigns the requested lookup_demographicrelativerelationship as @lookup_demographicrelativerelationship" do
      LookupDemographicrelativerelationship.stub(:find).with("37") { mock_lookup_demographicrelativerelationship }
      get :show, :id => "37"
      assigns(:lookup_demographicrelativerelationship).should be(mock_lookup_demographicrelativerelationship)
    end
  end

  describe "GET new" do
    it "assigns a new lookup_demographicrelativerelationship as @lookup_demographicrelativerelationship" do
      LookupDemographicrelativerelationship.stub(:new) { mock_lookup_demographicrelativerelationship }
      get :new
      assigns(:lookup_demographicrelativerelationship).should be(mock_lookup_demographicrelativerelationship)
    end
  end

  describe "GET edit" do
    it "assigns the requested lookup_demographicrelativerelationship as @lookup_demographicrelativerelationship" do
      LookupDemographicrelativerelationship.stub(:find).with("37") { mock_lookup_demographicrelativerelationship }
      get :edit, :id => "37"
      assigns(:lookup_demographicrelativerelationship).should be(mock_lookup_demographicrelativerelationship)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lookup_demographicrelativerelationship as @lookup_demographicrelativerelationship" do
        LookupDemographicrelativerelationship.stub(:new).with({'these' => 'params'}) { mock_lookup_demographicrelativerelationship(:save => true) }
        post :create, :lookup_demographicrelativerelationship => {'these' => 'params'}
        assigns(:lookup_demographicrelativerelationship).should be(mock_lookup_demographicrelativerelationship)
      end

      it "redirects to the created lookup_demographicrelativerelationship" do
        LookupDemographicrelativerelationship.stub(:new) { mock_lookup_demographicrelativerelationship(:save => true) }
        post :create, :lookup_demographicrelativerelationship => {}
        response.should redirect_to(lookup_demographicrelativerelationship_url(mock_lookup_demographicrelativerelationship))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lookup_demographicrelativerelationship as @lookup_demographicrelativerelationship" do
        LookupDemographicrelativerelationship.stub(:new).with({'these' => 'params'}) { mock_lookup_demographicrelativerelationship(:save => false) }
        post :create, :lookup_demographicrelativerelationship => {'these' => 'params'}
        assigns(:lookup_demographicrelativerelationship).should be(mock_lookup_demographicrelativerelationship)
      end

      it "re-renders the 'new' template" do
        LookupDemographicrelativerelationship.stub(:new) { mock_lookup_demographicrelativerelationship(:save => false) }
        post :create, :lookup_demographicrelativerelationship => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lookup_demographicrelativerelationship" do
        LookupDemographicrelativerelationship.stub(:find).with("37") { mock_lookup_demographicrelativerelationship }
        mock_lookup_demographicrelativerelationship.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lookup_demographicrelativerelationship => {'these' => 'params'}
      end

      it "assigns the requested lookup_demographicrelativerelationship as @lookup_demographicrelativerelationship" do
        LookupDemographicrelativerelationship.stub(:find) { mock_lookup_demographicrelativerelationship(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lookup_demographicrelativerelationship).should be(mock_lookup_demographicrelativerelationship)
      end

      it "redirects to the lookup_demographicrelativerelationship" do
        LookupDemographicrelativerelationship.stub(:find) { mock_lookup_demographicrelativerelationship(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lookup_demographicrelativerelationship_url(mock_lookup_demographicrelativerelationship))
      end
    end

    describe "with invalid params" do
      it "assigns the lookup_demographicrelativerelationship as @lookup_demographicrelativerelationship" do
        LookupDemographicrelativerelationship.stub(:find) { mock_lookup_demographicrelativerelationship(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lookup_demographicrelativerelationship).should be(mock_lookup_demographicrelativerelationship)
      end

      it "re-renders the 'edit' template" do
        LookupDemographicrelativerelationship.stub(:find) { mock_lookup_demographicrelativerelationship(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lookup_demographicrelativerelationship" do
      LookupDemographicrelativerelationship.stub(:find).with("37") { mock_lookup_demographicrelativerelationship }
      mock_lookup_demographicrelativerelationship.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lookup_demographicrelativerelationships list" do
      LookupDemographicrelativerelationship.stub(:find) { mock_lookup_demographicrelativerelationship }
      delete :destroy, :id => "1"
      response.should redirect_to(lookup_demographicrelativerelationships_url)
    end
  end

end
