require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LookupEthnicitiesController do

  def mock_lookup_ethnicity(stubs={})
    @mock_lookup_ethnicity ||= mock_model(LookupEthnicity, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lookup_ethnicities as @lookup_ethnicities" do
      LookupEthnicity.stub(:all) { [mock_lookup_ethnicity] }
      get :index
      assigns(:lookup_ethnicities).should eq([mock_lookup_ethnicity])
    end
  end

  describe "GET show" do
    it "assigns the requested lookup_ethnicity as @lookup_ethnicity" do
      LookupEthnicity.stub(:find).with("37") { mock_lookup_ethnicity }
      get :show, :id => "37"
      assigns(:lookup_ethnicity).should be(mock_lookup_ethnicity)
    end
  end

  describe "GET new" do
    it "assigns a new lookup_ethnicity as @lookup_ethnicity" do
      LookupEthnicity.stub(:new) { mock_lookup_ethnicity }
      get :new
      assigns(:lookup_ethnicity).should be(mock_lookup_ethnicity)
    end
  end

  describe "GET edit" do
    it "assigns the requested lookup_ethnicity as @lookup_ethnicity" do
      LookupEthnicity.stub(:find).with("37") { mock_lookup_ethnicity }
      get :edit, :id => "37"
      assigns(:lookup_ethnicity).should be(mock_lookup_ethnicity)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lookup_ethnicity as @lookup_ethnicity" do
        LookupEthnicity.stub(:new).with({'these' => 'params'}) { mock_lookup_ethnicity(:save => true) }
        post :create, :lookup_ethnicity => {'these' => 'params'}
        assigns(:lookup_ethnicity).should be(mock_lookup_ethnicity)
      end

      it "redirects to the created lookup_ethnicity" do
        LookupEthnicity.stub(:new) { mock_lookup_ethnicity(:save => true) }
        post :create, :lookup_ethnicity => {}
        response.should redirect_to(lookup_ethnicity_url(mock_lookup_ethnicity))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lookup_ethnicity as @lookup_ethnicity" do
        LookupEthnicity.stub(:new).with({'these' => 'params'}) { mock_lookup_ethnicity(:save => false) }
        post :create, :lookup_ethnicity => {'these' => 'params'}
        assigns(:lookup_ethnicity).should be(mock_lookup_ethnicity)
      end

      it "re-renders the 'new' template" do
        LookupEthnicity.stub(:new) { mock_lookup_ethnicity(:save => false) }
        post :create, :lookup_ethnicity => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lookup_ethnicity" do
        LookupEthnicity.stub(:find).with("37") { mock_lookup_ethnicity }
        mock_lookup_ethnicity.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lookup_ethnicity => {'these' => 'params'}
      end

      it "assigns the requested lookup_ethnicity as @lookup_ethnicity" do
        LookupEthnicity.stub(:find) { mock_lookup_ethnicity(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lookup_ethnicity).should be(mock_lookup_ethnicity)
      end

      it "redirects to the lookup_ethnicity" do
        LookupEthnicity.stub(:find) { mock_lookup_ethnicity(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lookup_ethnicity_url(mock_lookup_ethnicity))
      end
    end

    describe "with invalid params" do
      it "assigns the lookup_ethnicity as @lookup_ethnicity" do
        LookupEthnicity.stub(:find) { mock_lookup_ethnicity(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lookup_ethnicity).should be(mock_lookup_ethnicity)
      end

      it "re-renders the 'edit' template" do
        LookupEthnicity.stub(:find) { mock_lookup_ethnicity(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lookup_ethnicity" do
      LookupEthnicity.stub(:find).with("37") { mock_lookup_ethnicity }
      mock_lookup_ethnicity.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lookup_ethnicities list" do
      LookupEthnicity.stub(:find) { mock_lookup_ethnicity }
      delete :destroy, :id => "1"
      response.should redirect_to(lookup_ethnicities_url)
    end
  end

end
