require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LookupPettracersController do

  def mock_lookup_pettracer(stubs={})
    @mock_lookup_pettracer ||= mock_model(LookupPettracer, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lookup_pettracers as @lookup_pettracers" do
      LookupPettracer.stub(:all) { [mock_lookup_pettracer] }
      get :index
      assigns(:lookup_pettracers).should eq([mock_lookup_pettracer])
    end
  end

  describe "GET show" do
    it "assigns the requested lookup_pettracer as @lookup_pettracer" do
      LookupPettracer.stub(:find).with("37") { mock_lookup_pettracer }
      get :show, :id => "37"
      assigns(:lookup_pettracer).should be(mock_lookup_pettracer)
    end
  end

  describe "GET new" do
    it "assigns a new lookup_pettracer as @lookup_pettracer" do
      LookupPettracer.stub(:new) { mock_lookup_pettracer }
      get :new
      assigns(:lookup_pettracer).should be(mock_lookup_pettracer)
    end
  end

  describe "GET edit" do
    it "assigns the requested lookup_pettracer as @lookup_pettracer" do
      LookupPettracer.stub(:find).with("37") { mock_lookup_pettracer }
      get :edit, :id => "37"
      assigns(:lookup_pettracer).should be(mock_lookup_pettracer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lookup_pettracer as @lookup_pettracer" do
        LookupPettracer.stub(:new).with({'these' => 'params'}) { mock_lookup_pettracer(:save => true) }
        post :create, :lookup_pettracer => {'these' => 'params'}
        assigns(:lookup_pettracer).should be(mock_lookup_pettracer)
      end

      it "redirects to the created lookup_pettracer" do
        LookupPettracer.stub(:new) { mock_lookup_pettracer(:save => true) }
        post :create, :lookup_pettracer => {}
        response.should redirect_to(lookup_pettracer_url(mock_lookup_pettracer))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lookup_pettracer as @lookup_pettracer" do
        LookupPettracer.stub(:new).with({'these' => 'params'}) { mock_lookup_pettracer(:save => false) }
        post :create, :lookup_pettracer => {'these' => 'params'}
        assigns(:lookup_pettracer).should be(mock_lookup_pettracer)
      end

      it "re-renders the 'new' template" do
        LookupPettracer.stub(:new) { mock_lookup_pettracer(:save => false) }
        post :create, :lookup_pettracer => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lookup_pettracer" do
        LookupPettracer.stub(:find).with("37") { mock_lookup_pettracer }
        mock_lookup_pettracer.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lookup_pettracer => {'these' => 'params'}
      end

      it "assigns the requested lookup_pettracer as @lookup_pettracer" do
        LookupPettracer.stub(:find) { mock_lookup_pettracer(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lookup_pettracer).should be(mock_lookup_pettracer)
      end

      it "redirects to the lookup_pettracer" do
        LookupPettracer.stub(:find) { mock_lookup_pettracer(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lookup_pettracer_url(mock_lookup_pettracer))
      end
    end

    describe "with invalid params" do
      it "assigns the lookup_pettracer as @lookup_pettracer" do
        LookupPettracer.stub(:find) { mock_lookup_pettracer(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lookup_pettracer).should be(mock_lookup_pettracer)
      end

      it "re-renders the 'edit' template" do
        LookupPettracer.stub(:find) { mock_lookup_pettracer(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lookup_pettracer" do
      LookupPettracer.stub(:find).with("37") { mock_lookup_pettracer }
      mock_lookup_pettracer.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lookup_pettracers list" do
      LookupPettracer.stub(:find) { mock_lookup_pettracer }
      delete :destroy, :id => "1"
      response.should redirect_to(lookup_pettracers_url)
    end
  end

end
