require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LumbarpuncturesController do

  def mock_lumbarpuncture(stubs={})
    @mock_lumbarpuncture ||= mock_model(Lumbarpuncture, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all lumbarpunctures as @lumbarpunctures" do
      Lumbarpuncture.stub(:all) { [mock_lumbarpuncture] }
      get :index
      assigns(:lumbarpunctures).should eq([mock_lumbarpuncture])
    end
  end

  describe "GET show" do
    it "assigns the requested lumbarpuncture as @lumbarpuncture" do
      Lumbarpuncture.stub(:find).with("37") { mock_lumbarpuncture }
      get :show, :id => "37"
      assigns(:lumbarpuncture).should be(mock_lumbarpuncture)
    end
  end

  describe "GET new" do
    it "assigns a new lumbarpuncture as @lumbarpuncture" do
      Lumbarpuncture.stub(:new) { mock_lumbarpuncture }
      get :new
      assigns(:lumbarpuncture).should be(mock_lumbarpuncture)
    end
  end

  describe "GET edit" do
    it "assigns the requested lumbarpuncture as @lumbarpuncture" do
      Lumbarpuncture.stub(:find).with("37") { mock_lumbarpuncture }
      get :edit, :id => "37"
      assigns(:lumbarpuncture).should be(mock_lumbarpuncture)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created lumbarpuncture as @lumbarpuncture" do
        Lumbarpuncture.stub(:new).with({'these' => 'params'}) { mock_lumbarpuncture(:save => true) }
        post :create, :lumbarpuncture => {'these' => 'params'}
        assigns(:lumbarpuncture).should be(mock_lumbarpuncture)
      end

      it "redirects to the created lumbarpuncture" do
        Lumbarpuncture.stub(:new) { mock_lumbarpuncture(:save => true) }
        post :create, :lumbarpuncture => {}
        response.should redirect_to(lumbarpuncture_url(mock_lumbarpuncture))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lumbarpuncture as @lumbarpuncture" do
        Lumbarpuncture.stub(:new).with({'these' => 'params'}) { mock_lumbarpuncture(:save => false) }
        post :create, :lumbarpuncture => {'these' => 'params'}
        assigns(:lumbarpuncture).should be(mock_lumbarpuncture)
      end

      it "re-renders the 'new' template" do
        Lumbarpuncture.stub(:new) { mock_lumbarpuncture(:save => false) }
        post :create, :lumbarpuncture => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lumbarpuncture" do
        Lumbarpuncture.stub(:find).with("37") { mock_lumbarpuncture }
        mock_lumbarpuncture.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :lumbarpuncture => {'these' => 'params'}
      end

      it "assigns the requested lumbarpuncture as @lumbarpuncture" do
        Lumbarpuncture.stub(:find) { mock_lumbarpuncture(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:lumbarpuncture).should be(mock_lumbarpuncture)
      end

      it "redirects to the lumbarpuncture" do
        Lumbarpuncture.stub(:find) { mock_lumbarpuncture(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(lumbarpuncture_url(mock_lumbarpuncture))
      end
    end

    describe "with invalid params" do
      it "assigns the lumbarpuncture as @lumbarpuncture" do
        Lumbarpuncture.stub(:find) { mock_lumbarpuncture(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:lumbarpuncture).should be(mock_lumbarpuncture)
      end

      it "re-renders the 'edit' template" do
        Lumbarpuncture.stub(:find) { mock_lumbarpuncture(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lumbarpuncture" do
      Lumbarpuncture.stub(:find).with("37") { mock_lumbarpuncture }
      mock_lumbarpuncture.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the lumbarpunctures list" do
      Lumbarpuncture.stub(:find) { mock_lumbarpuncture }
      delete :destroy, :id => "1"
      response.should redirect_to(lumbarpunctures_url)
    end
  end

end
