require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MriperformancesController do

  def mock_mriperformance(stubs={})
    @mock_mriperformance ||= mock_model(Mriperformance, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all mriperformances as @mriperformances" do
      Mriperformance.stub(:all) { [mock_mriperformance] }
      get :index
      assigns(:mriperformances).should eq([mock_mriperformance])
    end
  end

  describe "GET show" do
    it "assigns the requested mriperformance as @mriperformance" do
      Mriperformance.stub(:find).with("37") { mock_mriperformance }
      get :show, :id => "37"
      assigns(:mriperformance).should be(mock_mriperformance)
    end
  end

  describe "GET new" do
    it "assigns a new mriperformance as @mriperformance" do
      Mriperformance.stub(:new) { mock_mriperformance }
      get :new
      assigns(:mriperformance).should be(mock_mriperformance)
    end
  end

  describe "GET edit" do
    it "assigns the requested mriperformance as @mriperformance" do
      Mriperformance.stub(:find).with("37") { mock_mriperformance }
      get :edit, :id => "37"
      assigns(:mriperformance).should be(mock_mriperformance)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created mriperformance as @mriperformance" do
        Mriperformance.stub(:new).with({'these' => 'params'}) { mock_mriperformance(:save => true) }
        post :create, :mriperformance => {'these' => 'params'}
        assigns(:mriperformance).should be(mock_mriperformance)
      end

      it "redirects to the created mriperformance" do
        Mriperformance.stub(:new) { mock_mriperformance(:save => true) }
        post :create, :mriperformance => {}
        response.should redirect_to(mriperformance_url(mock_mriperformance))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mriperformance as @mriperformance" do
        Mriperformance.stub(:new).with({'these' => 'params'}) { mock_mriperformance(:save => false) }
        post :create, :mriperformance => {'these' => 'params'}
        assigns(:mriperformance).should be(mock_mriperformance)
      end

      it "re-renders the 'new' template" do
        Mriperformance.stub(:new) { mock_mriperformance(:save => false) }
        post :create, :mriperformance => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mriperformance" do
        Mriperformance.stub(:find).with("37") { mock_mriperformance }
        mock_mriperformance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :mriperformance => {'these' => 'params'}
      end

      it "assigns the requested mriperformance as @mriperformance" do
        Mriperformance.stub(:find) { mock_mriperformance(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:mriperformance).should be(mock_mriperformance)
      end

      it "redirects to the mriperformance" do
        Mriperformance.stub(:find) { mock_mriperformance(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(mriperformance_url(mock_mriperformance))
      end
    end

    describe "with invalid params" do
      it "assigns the mriperformance as @mriperformance" do
        Mriperformance.stub(:find) { mock_mriperformance(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:mriperformance).should be(mock_mriperformance)
      end

      it "re-renders the 'edit' template" do
        Mriperformance.stub(:find) { mock_mriperformance(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mriperformance" do
      Mriperformance.stub(:find).with("37") { mock_mriperformance }
      mock_mriperformance.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the mriperformances list" do
      Mriperformance.stub(:find) { mock_mriperformance }
      delete :destroy, :id => "1"
      response.should redirect_to(mriperformances_url)
    end
  end

end
