require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MriscantasksController do

  def mock_mriscantask(stubs={})
    @mock_mriscantask ||= mock_model(Mriscantask, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all mriscantasks as @mriscantasks" do
      Mriscantask.stub(:all) { [mock_mriscantask] }
      get :index
      assigns(:mriscantasks).should eq([mock_mriscantask])
    end
  end

  describe "GET show" do
    it "assigns the requested mriscantask as @mriscantask" do
      Mriscantask.stub(:find).with("37") { mock_mriscantask }
      get :show, :id => "37"
      assigns(:mriscantask).should be(mock_mriscantask)
    end
  end

  describe "GET new" do
    it "assigns a new mriscantask as @mriscantask" do
      Mriscantask.stub(:new) { mock_mriscantask }
      get :new
      assigns(:mriscantask).should be(mock_mriscantask)
    end
  end

  describe "GET edit" do
    it "assigns the requested mriscantask as @mriscantask" do
      Mriscantask.stub(:find).with("37") { mock_mriscantask }
      get :edit, :id => "37"
      assigns(:mriscantask).should be(mock_mriscantask)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created mriscantask as @mriscantask" do
        Mriscantask.stub(:new).with({'these' => 'params'}) { mock_mriscantask(:save => true) }
        post :create, :mriscantask => {'these' => 'params'}
        assigns(:mriscantask).should be(mock_mriscantask)
      end

      it "redirects to the created mriscantask" do
        Mriscantask.stub(:new) { mock_mriscantask(:save => true) }
        post :create, :mriscantask => {}
        response.should redirect_to(mriscantask_url(mock_mriscantask))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mriscantask as @mriscantask" do
        Mriscantask.stub(:new).with({'these' => 'params'}) { mock_mriscantask(:save => false) }
        post :create, :mriscantask => {'these' => 'params'}
        assigns(:mriscantask).should be(mock_mriscantask)
      end

      it "re-renders the 'new' template" do
        Mriscantask.stub(:new) { mock_mriscantask(:save => false) }
        post :create, :mriscantask => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mriscantask" do
        Mriscantask.stub(:find).with("37") { mock_mriscantask }
        mock_mriscantask.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :mriscantask => {'these' => 'params'}
      end

      it "assigns the requested mriscantask as @mriscantask" do
        Mriscantask.stub(:find) { mock_mriscantask(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:mriscantask).should be(mock_mriscantask)
      end

      it "redirects to the mriscantask" do
        Mriscantask.stub(:find) { mock_mriscantask(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(mriscantask_url(mock_mriscantask))
      end
    end

    describe "with invalid params" do
      it "assigns the mriscantask as @mriscantask" do
        Mriscantask.stub(:find) { mock_mriscantask(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:mriscantask).should be(mock_mriscantask)
      end

      it "re-renders the 'edit' template" do
        Mriscantask.stub(:find) { mock_mriscantask(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mriscantask" do
      Mriscantask.stub(:find).with("37") { mock_mriscantask }
      mock_mriscantask.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the mriscantasks list" do
      Mriscantask.stub(:find) { mock_mriscantask }
      delete :destroy, :id => "1"
      response.should redirect_to(mriscantasks_url)
    end
  end

end
