require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ProtocolRolesController do

  def mock_protocol_role(stubs={})
    @mock_protocol_role ||= mock_model(ProtocolRole, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all protocol_roles as @protocol_roles" do
      ProtocolRole.stub(:all) { [mock_protocol_role] }
      get :index
      assigns(:protocol_roles).should eq([mock_protocol_role])
    end
  end

  describe "GET show" do
    it "assigns the requested protocol_role as @protocol_role" do
      ProtocolRole.stub(:find).with("37") { mock_protocol_role }
      get :show, :id => "37"
      assigns(:protocol_role).should be(mock_protocol_role)
    end
  end

  describe "GET new" do
    it "assigns a new protocol_role as @protocol_role" do
      ProtocolRole.stub(:new) { mock_protocol_role }
      get :new
      assigns(:protocol_role).should be(mock_protocol_role)
    end
  end

  describe "GET edit" do
    it "assigns the requested protocol_role as @protocol_role" do
      ProtocolRole.stub(:find).with("37") { mock_protocol_role }
      get :edit, :id => "37"
      assigns(:protocol_role).should be(mock_protocol_role)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created protocol_role as @protocol_role" do
        ProtocolRole.stub(:new).with({'these' => 'params'}) { mock_protocol_role(:save => true) }
        post :create, :protocol_role => {'these' => 'params'}
        assigns(:protocol_role).should be(mock_protocol_role)
      end

      it "redirects to the created protocol_role" do
        ProtocolRole.stub(:new) { mock_protocol_role(:save => true) }
        post :create, :protocol_role => {}
        response.should redirect_to(protocol_role_url(mock_protocol_role))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved protocol_role as @protocol_role" do
        ProtocolRole.stub(:new).with({'these' => 'params'}) { mock_protocol_role(:save => false) }
        post :create, :protocol_role => {'these' => 'params'}
        assigns(:protocol_role).should be(mock_protocol_role)
      end

      it "re-renders the 'new' template" do
        ProtocolRole.stub(:new) { mock_protocol_role(:save => false) }
        post :create, :protocol_role => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested protocol_role" do
        ProtocolRole.stub(:find).with("37") { mock_protocol_role }
        mock_protocol_role.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :protocol_role => {'these' => 'params'}
      end

      it "assigns the requested protocol_role as @protocol_role" do
        ProtocolRole.stub(:find) { mock_protocol_role(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:protocol_role).should be(mock_protocol_role)
      end

      it "redirects to the protocol_role" do
        ProtocolRole.stub(:find) { mock_protocol_role(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(protocol_role_url(mock_protocol_role))
      end
    end

    describe "with invalid params" do
      it "assigns the protocol_role as @protocol_role" do
        ProtocolRole.stub(:find) { mock_protocol_role(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:protocol_role).should be(mock_protocol_role)
      end

      it "re-renders the 'edit' template" do
        ProtocolRole.stub(:find) { mock_protocol_role(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested protocol_role" do
      ProtocolRole.stub(:find).with("37") { mock_protocol_role }
      mock_protocol_role.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the protocol_roles list" do
      ProtocolRole.stub(:find) { mock_protocol_role }
      delete :destroy, :id => "1"
      response.should redirect_to(protocol_roles_url)
    end
  end

end
