require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe QDataController do

  def mock_q_datum(stubs={})
    @mock_q_datum ||= mock_model(QDatum, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all q_data as @q_data" do
      QDatum.stub(:all) { [mock_q_datum] }
      get :index
      assigns(:q_data).should eq([mock_q_datum])
    end
  end

  describe "GET show" do
    it "assigns the requested q_datum as @q_datum" do
      QDatum.stub(:find).with("37") { mock_q_datum }
      get :show, :id => "37"
      assigns(:q_datum).should be(mock_q_datum)
    end
  end

  describe "GET new" do
    it "assigns a new q_datum as @q_datum" do
      QDatum.stub(:new) { mock_q_datum }
      get :new
      assigns(:q_datum).should be(mock_q_datum)
    end
  end

  describe "GET edit" do
    it "assigns the requested q_datum as @q_datum" do
      QDatum.stub(:find).with("37") { mock_q_datum }
      get :edit, :id => "37"
      assigns(:q_datum).should be(mock_q_datum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created q_datum as @q_datum" do
        QDatum.stub(:new).with({'these' => 'params'}) { mock_q_datum(:save => true) }
        post :create, :q_datum => {'these' => 'params'}
        assigns(:q_datum).should be(mock_q_datum)
      end

      it "redirects to the created q_datum" do
        QDatum.stub(:new) { mock_q_datum(:save => true) }
        post :create, :q_datum => {}
        response.should redirect_to(q_datum_url(mock_q_datum))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved q_datum as @q_datum" do
        QDatum.stub(:new).with({'these' => 'params'}) { mock_q_datum(:save => false) }
        post :create, :q_datum => {'these' => 'params'}
        assigns(:q_datum).should be(mock_q_datum)
      end

      it "re-renders the 'new' template" do
        QDatum.stub(:new) { mock_q_datum(:save => false) }
        post :create, :q_datum => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested q_datum" do
        QDatum.stub(:find).with("37") { mock_q_datum }
        mock_q_datum.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :q_datum => {'these' => 'params'}
      end

      it "assigns the requested q_datum as @q_datum" do
        QDatum.stub(:find) { mock_q_datum(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:q_datum).should be(mock_q_datum)
      end

      it "redirects to the q_datum" do
        QDatum.stub(:find) { mock_q_datum(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(q_datum_url(mock_q_datum))
      end
    end

    describe "with invalid params" do
      it "assigns the q_datum as @q_datum" do
        QDatum.stub(:find) { mock_q_datum(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:q_datum).should be(mock_q_datum)
      end

      it "re-renders the 'edit' template" do
        QDatum.stub(:find) { mock_q_datum(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested q_datum" do
      QDatum.stub(:find).with("37") { mock_q_datum }
      mock_q_datum.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the q_data list" do
      QDatum.stub(:find) { mock_q_datum }
      delete :destroy, :id => "1"
      response.should redirect_to(q_data_url)
    end
  end

end
