require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe QDataFormsController do

  def mock_q_data_form(stubs={})
    @mock_q_data_form ||= mock_model(QDataForm, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all q_data_forms as @q_data_forms" do
      QDataForm.stub(:all) { [mock_q_data_form] }
      get :index
      assigns(:q_data_forms).should eq([mock_q_data_form])
    end
  end

  describe "GET show" do
    it "assigns the requested q_data_form as @q_data_form" do
      QDataForm.stub(:find).with("37") { mock_q_data_form }
      get :show, :id => "37"
      assigns(:q_data_form).should be(mock_q_data_form)
    end
  end

  describe "GET new" do
    it "assigns a new q_data_form as @q_data_form" do
      QDataForm.stub(:new) { mock_q_data_form }
      get :new
      assigns(:q_data_form).should be(mock_q_data_form)
    end
  end

  describe "GET edit" do
    it "assigns the requested q_data_form as @q_data_form" do
      QDataForm.stub(:find).with("37") { mock_q_data_form }
      get :edit, :id => "37"
      assigns(:q_data_form).should be(mock_q_data_form)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created q_data_form as @q_data_form" do
        QDataForm.stub(:new).with({'these' => 'params'}) { mock_q_data_form(:save => true) }
        post :create, :q_data_form => {'these' => 'params'}
        assigns(:q_data_form).should be(mock_q_data_form)
      end

      it "redirects to the created q_data_form" do
        QDataForm.stub(:new) { mock_q_data_form(:save => true) }
        post :create, :q_data_form => {}
        response.should redirect_to(q_data_form_url(mock_q_data_form))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved q_data_form as @q_data_form" do
        QDataForm.stub(:new).with({'these' => 'params'}) { mock_q_data_form(:save => false) }
        post :create, :q_data_form => {'these' => 'params'}
        assigns(:q_data_form).should be(mock_q_data_form)
      end

      it "re-renders the 'new' template" do
        QDataForm.stub(:new) { mock_q_data_form(:save => false) }
        post :create, :q_data_form => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested q_data_form" do
        QDataForm.stub(:find).with("37") { mock_q_data_form }
        mock_q_data_form.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :q_data_form => {'these' => 'params'}
      end

      it "assigns the requested q_data_form as @q_data_form" do
        QDataForm.stub(:find) { mock_q_data_form(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:q_data_form).should be(mock_q_data_form)
      end

      it "redirects to the q_data_form" do
        QDataForm.stub(:find) { mock_q_data_form(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(q_data_form_url(mock_q_data_form))
      end
    end

    describe "with invalid params" do
      it "assigns the q_data_form as @q_data_form" do
        QDataForm.stub(:find) { mock_q_data_form(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:q_data_form).should be(mock_q_data_form)
      end

      it "re-renders the 'edit' template" do
        QDataForm.stub(:find) { mock_q_data_form(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested q_data_form" do
      QDataForm.stub(:find).with("37") { mock_q_data_form }
      mock_q_data_form.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the q_data_forms list" do
      QDataForm.stub(:find) { mock_q_data_form }
      delete :destroy, :id => "1"
      response.should redirect_to(q_data_forms_url)
    end
  end

end
