require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe QuestionnairesController do

  def mock_questionnaire(stubs={})
    @mock_questionnaire ||= mock_model(Questionnaire, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all questionnaires as @questionnaires" do
      Questionnaire.stub(:all) { [mock_questionnaire] }
      get :index
      assigns(:questionnaires).should eq([mock_questionnaire])
    end
  end

  describe "GET show" do
    it "assigns the requested questionnaire as @questionnaire" do
      Questionnaire.stub(:find).with("37") { mock_questionnaire }
      get :show, :id => "37"
      assigns(:questionnaire).should be(mock_questionnaire)
    end
  end

  describe "GET new" do
    it "assigns a new questionnaire as @questionnaire" do
      Questionnaire.stub(:new) { mock_questionnaire }
      get :new
      assigns(:questionnaire).should be(mock_questionnaire)
    end
  end

  describe "GET edit" do
    it "assigns the requested questionnaire as @questionnaire" do
      Questionnaire.stub(:find).with("37") { mock_questionnaire }
      get :edit, :id => "37"
      assigns(:questionnaire).should be(mock_questionnaire)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created questionnaire as @questionnaire" do
        Questionnaire.stub(:new).with({'these' => 'params'}) { mock_questionnaire(:save => true) }
        post :create, :questionnaire => {'these' => 'params'}
        assigns(:questionnaire).should be(mock_questionnaire)
      end

      it "redirects to the created questionnaire" do
        Questionnaire.stub(:new) { mock_questionnaire(:save => true) }
        post :create, :questionnaire => {}
        response.should redirect_to(questionnaire_url(mock_questionnaire))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved questionnaire as @questionnaire" do
        Questionnaire.stub(:new).with({'these' => 'params'}) { mock_questionnaire(:save => false) }
        post :create, :questionnaire => {'these' => 'params'}
        assigns(:questionnaire).should be(mock_questionnaire)
      end

      it "re-renders the 'new' template" do
        Questionnaire.stub(:new) { mock_questionnaire(:save => false) }
        post :create, :questionnaire => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested questionnaire" do
        Questionnaire.stub(:find).with("37") { mock_questionnaire }
        mock_questionnaire.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :questionnaire => {'these' => 'params'}
      end

      it "assigns the requested questionnaire as @questionnaire" do
        Questionnaire.stub(:find) { mock_questionnaire(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:questionnaire).should be(mock_questionnaire)
      end

      it "redirects to the questionnaire" do
        Questionnaire.stub(:find) { mock_questionnaire(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(questionnaire_url(mock_questionnaire))
      end
    end

    describe "with invalid params" do
      it "assigns the questionnaire as @questionnaire" do
        Questionnaire.stub(:find) { mock_questionnaire(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:questionnaire).should be(mock_questionnaire)
      end

      it "re-renders the 'edit' template" do
        Questionnaire.stub(:find) { mock_questionnaire(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested questionnaire" do
      Questionnaire.stub(:find).with("37") { mock_questionnaire }
      mock_questionnaire.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the questionnaires list" do
      Questionnaire.stub(:find) { mock_questionnaire }
      delete :destroy, :id => "1"
      response.should redirect_to(questionnaires_url)
    end
  end

end
