require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe QuestionformsController do

  def mock_questionform(stubs={})
    @mock_questionform ||= mock_model(Questionform, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all questionforms as @questionforms" do
      Questionform.stub(:all) { [mock_questionform] }
      get :index
      assigns(:questionforms).should eq([mock_questionform])
    end
  end

  describe "GET show" do
    it "assigns the requested questionform as @questionform" do
      Questionform.stub(:find).with("37") { mock_questionform }
      get :show, :id => "37"
      assigns(:questionform).should be(mock_questionform)
    end
  end

  describe "GET new" do
    it "assigns a new questionform as @questionform" do
      Questionform.stub(:new) { mock_questionform }
      get :new
      assigns(:questionform).should be(mock_questionform)
    end
  end

  describe "GET edit" do
    it "assigns the requested questionform as @questionform" do
      Questionform.stub(:find).with("37") { mock_questionform }
      get :edit, :id => "37"
      assigns(:questionform).should be(mock_questionform)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created questionform as @questionform" do
        Questionform.stub(:new).with({'these' => 'params'}) { mock_questionform(:save => true) }
        post :create, :questionform => {'these' => 'params'}
        assigns(:questionform).should be(mock_questionform)
      end

      it "redirects to the created questionform" do
        Questionform.stub(:new) { mock_questionform(:save => true) }
        post :create, :questionform => {}
        response.should redirect_to(questionform_url(mock_questionform))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved questionform as @questionform" do
        Questionform.stub(:new).with({'these' => 'params'}) { mock_questionform(:save => false) }
        post :create, :questionform => {'these' => 'params'}
        assigns(:questionform).should be(mock_questionform)
      end

      it "re-renders the 'new' template" do
        Questionform.stub(:new) { mock_questionform(:save => false) }
        post :create, :questionform => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested questionform" do
        Questionform.stub(:find).with("37") { mock_questionform }
        mock_questionform.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :questionform => {'these' => 'params'}
      end

      it "assigns the requested questionform as @questionform" do
        Questionform.stub(:find) { mock_questionform(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:questionform).should be(mock_questionform)
      end

      it "redirects to the questionform" do
        Questionform.stub(:find) { mock_questionform(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(questionform_url(mock_questionform))
      end
    end

    describe "with invalid params" do
      it "assigns the questionform as @questionform" do
        Questionform.stub(:find) { mock_questionform(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:questionform).should be(mock_questionform)
      end

      it "re-renders the 'edit' template" do
        Questionform.stub(:find) { mock_questionform(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested questionform" do
      Questionform.stub(:find).with("37") { mock_questionform }
      mock_questionform.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the questionforms list" do
      Questionform.stub(:find) { mock_questionform }
      delete :destroy, :id => "1"
      response.should redirect_to(questionforms_url)
    end
  end

end
