require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe QuestionformQuestionsController do

  def mock_questionform_question(stubs={})
    @mock_questionform_question ||= mock_model(QuestionformQuestion, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all questionform_questions as @questionform_questions" do
      QuestionformQuestion.stub(:all) { [mock_questionform_question] }
      get :index
      assigns(:questionform_questions).should eq([mock_questionform_question])
    end
  end

  describe "GET show" do
    it "assigns the requested questionform_question as @questionform_question" do
      QuestionformQuestion.stub(:find).with("37") { mock_questionform_question }
      get :show, :id => "37"
      assigns(:questionform_question).should be(mock_questionform_question)
    end
  end

  describe "GET new" do
    it "assigns a new questionform_question as @questionform_question" do
      QuestionformQuestion.stub(:new) { mock_questionform_question }
      get :new
      assigns(:questionform_question).should be(mock_questionform_question)
    end
  end

  describe "GET edit" do
    it "assigns the requested questionform_question as @questionform_question" do
      QuestionformQuestion.stub(:find).with("37") { mock_questionform_question }
      get :edit, :id => "37"
      assigns(:questionform_question).should be(mock_questionform_question)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created questionform_question as @questionform_question" do
        QuestionformQuestion.stub(:new).with({'these' => 'params'}) { mock_questionform_question(:save => true) }
        post :create, :questionform_question => {'these' => 'params'}
        assigns(:questionform_question).should be(mock_questionform_question)
      end

      it "redirects to the created questionform_question" do
        QuestionformQuestion.stub(:new) { mock_questionform_question(:save => true) }
        post :create, :questionform_question => {}
        response.should redirect_to(questionform_question_url(mock_questionform_question))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved questionform_question as @questionform_question" do
        QuestionformQuestion.stub(:new).with({'these' => 'params'}) { mock_questionform_question(:save => false) }
        post :create, :questionform_question => {'these' => 'params'}
        assigns(:questionform_question).should be(mock_questionform_question)
      end

      it "re-renders the 'new' template" do
        QuestionformQuestion.stub(:new) { mock_questionform_question(:save => false) }
        post :create, :questionform_question => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested questionform_question" do
        QuestionformQuestion.stub(:find).with("37") { mock_questionform_question }
        mock_questionform_question.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :questionform_question => {'these' => 'params'}
      end

      it "assigns the requested questionform_question as @questionform_question" do
        QuestionformQuestion.stub(:find) { mock_questionform_question(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:questionform_question).should be(mock_questionform_question)
      end

      it "redirects to the questionform_question" do
        QuestionformQuestion.stub(:find) { mock_questionform_question(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(questionform_question_url(mock_questionform_question))
      end
    end

    describe "with invalid params" do
      it "assigns the questionform_question as @questionform_question" do
        QuestionformQuestion.stub(:find) { mock_questionform_question(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:questionform_question).should be(mock_questionform_question)
      end

      it "re-renders the 'edit' template" do
        QuestionformQuestion.stub(:find) { mock_questionform_question(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested questionform_question" do
      QuestionformQuestion.stub(:find).with("37") { mock_questionform_question }
      mock_questionform_question.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the questionform_questions list" do
      QuestionformQuestion.stub(:find) { mock_questionform_question }
      delete :destroy, :id => "1"
      response.should redirect_to(questionform_questions_url)
    end
  end

end
