require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe QuestionScanProtocolsController do

  def mock_question_scan_protocol(stubs={})
    @mock_question_scan_protocol ||= mock_model(QuestionScanProtocol, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all question_scan_protocols as @question_scan_protocols" do
      QuestionScanProtocol.stub(:all) { [mock_question_scan_protocol] }
      get :index
      assigns(:question_scan_protocols).should eq([mock_question_scan_protocol])
    end
  end

  describe "GET show" do
    it "assigns the requested question_scan_protocol as @question_scan_protocol" do
      QuestionScanProtocol.stub(:find).with("37") { mock_question_scan_protocol }
      get :show, :id => "37"
      assigns(:question_scan_protocol).should be(mock_question_scan_protocol)
    end
  end

  describe "GET new" do
    it "assigns a new question_scan_protocol as @question_scan_protocol" do
      QuestionScanProtocol.stub(:new) { mock_question_scan_protocol }
      get :new
      assigns(:question_scan_protocol).should be(mock_question_scan_protocol)
    end
  end

  describe "GET edit" do
    it "assigns the requested question_scan_protocol as @question_scan_protocol" do
      QuestionScanProtocol.stub(:find).with("37") { mock_question_scan_protocol }
      get :edit, :id => "37"
      assigns(:question_scan_protocol).should be(mock_question_scan_protocol)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created question_scan_protocol as @question_scan_protocol" do
        QuestionScanProtocol.stub(:new).with({'these' => 'params'}) { mock_question_scan_protocol(:save => true) }
        post :create, :question_scan_protocol => {'these' => 'params'}
        assigns(:question_scan_protocol).should be(mock_question_scan_protocol)
      end

      it "redirects to the created question_scan_protocol" do
        QuestionScanProtocol.stub(:new) { mock_question_scan_protocol(:save => true) }
        post :create, :question_scan_protocol => {}
        response.should redirect_to(question_scan_protocol_url(mock_question_scan_protocol))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved question_scan_protocol as @question_scan_protocol" do
        QuestionScanProtocol.stub(:new).with({'these' => 'params'}) { mock_question_scan_protocol(:save => false) }
        post :create, :question_scan_protocol => {'these' => 'params'}
        assigns(:question_scan_protocol).should be(mock_question_scan_protocol)
      end

      it "re-renders the 'new' template" do
        QuestionScanProtocol.stub(:new) { mock_question_scan_protocol(:save => false) }
        post :create, :question_scan_protocol => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested question_scan_protocol" do
        QuestionScanProtocol.stub(:find).with("37") { mock_question_scan_protocol }
        mock_question_scan_protocol.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :question_scan_protocol => {'these' => 'params'}
      end

      it "assigns the requested question_scan_protocol as @question_scan_protocol" do
        QuestionScanProtocol.stub(:find) { mock_question_scan_protocol(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:question_scan_protocol).should be(mock_question_scan_protocol)
      end

      it "redirects to the question_scan_protocol" do
        QuestionScanProtocol.stub(:find) { mock_question_scan_protocol(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(question_scan_protocol_url(mock_question_scan_protocol))
      end
    end

    describe "with invalid params" do
      it "assigns the question_scan_protocol as @question_scan_protocol" do
        QuestionScanProtocol.stub(:find) { mock_question_scan_protocol(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:question_scan_protocol).should be(mock_question_scan_protocol)
      end

      it "re-renders the 'edit' template" do
        QuestionScanProtocol.stub(:find) { mock_question_scan_protocol(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested question_scan_protocol" do
      QuestionScanProtocol.stub(:find).with("37") { mock_question_scan_protocol }
      mock_question_scan_protocol.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the question_scan_protocols list" do
      QuestionScanProtocol.stub(:find) { mock_question_scan_protocol }
      delete :destroy, :id => "1"
      response.should redirect_to(question_scan_protocols_url)
    end
  end

end
