require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe QuestionformScanProceduresController do

  def mock_questionform_scan_procedure(stubs={})
    @mock_questionform_scan_procedure ||= mock_model(QuestionformScanProcedure, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all questionform_scan_procedures as @questionform_scan_procedures" do
      QuestionformScanProcedure.stub(:all) { [mock_questionform_scan_procedure] }
      get :index
      assigns(:questionform_scan_procedures).should eq([mock_questionform_scan_procedure])
    end
  end

  describe "GET show" do
    it "assigns the requested questionform_scan_procedure as @questionform_scan_procedure" do
      QuestionformScanProcedure.stub(:find).with("37") { mock_questionform_scan_procedure }
      get :show, :id => "37"
      assigns(:questionform_scan_procedure).should be(mock_questionform_scan_procedure)
    end
  end

  describe "GET new" do
    it "assigns a new questionform_scan_procedure as @questionform_scan_procedure" do
      QuestionformScanProcedure.stub(:new) { mock_questionform_scan_procedure }
      get :new
      assigns(:questionform_scan_procedure).should be(mock_questionform_scan_procedure)
    end
  end

  describe "GET edit" do
    it "assigns the requested questionform_scan_procedure as @questionform_scan_procedure" do
      QuestionformScanProcedure.stub(:find).with("37") { mock_questionform_scan_procedure }
      get :edit, :id => "37"
      assigns(:questionform_scan_procedure).should be(mock_questionform_scan_procedure)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created questionform_scan_procedure as @questionform_scan_procedure" do
        QuestionformScanProcedure.stub(:new).with({'these' => 'params'}) { mock_questionform_scan_procedure(:save => true) }
        post :create, :questionform_scan_procedure => {'these' => 'params'}
        assigns(:questionform_scan_procedure).should be(mock_questionform_scan_procedure)
      end

      it "redirects to the created questionform_scan_procedure" do
        QuestionformScanProcedure.stub(:new) { mock_questionform_scan_procedure(:save => true) }
        post :create, :questionform_scan_procedure => {}
        response.should redirect_to(questionform_scan_procedure_url(mock_questionform_scan_procedure))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved questionform_scan_procedure as @questionform_scan_procedure" do
        QuestionformScanProcedure.stub(:new).with({'these' => 'params'}) { mock_questionform_scan_procedure(:save => false) }
        post :create, :questionform_scan_procedure => {'these' => 'params'}
        assigns(:questionform_scan_procedure).should be(mock_questionform_scan_procedure)
      end

      it "re-renders the 'new' template" do
        QuestionformScanProcedure.stub(:new) { mock_questionform_scan_procedure(:save => false) }
        post :create, :questionform_scan_procedure => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested questionform_scan_procedure" do
        QuestionformScanProcedure.stub(:find).with("37") { mock_questionform_scan_procedure }
        mock_questionform_scan_procedure.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :questionform_scan_procedure => {'these' => 'params'}
      end

      it "assigns the requested questionform_scan_procedure as @questionform_scan_procedure" do
        QuestionformScanProcedure.stub(:find) { mock_questionform_scan_procedure(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:questionform_scan_procedure).should be(mock_questionform_scan_procedure)
      end

      it "redirects to the questionform_scan_procedure" do
        QuestionformScanProcedure.stub(:find) { mock_questionform_scan_procedure(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(questionform_scan_procedure_url(mock_questionform_scan_procedure))
      end
    end

    describe "with invalid params" do
      it "assigns the questionform_scan_procedure as @questionform_scan_procedure" do
        QuestionformScanProcedure.stub(:find) { mock_questionform_scan_procedure(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:questionform_scan_procedure).should be(mock_questionform_scan_procedure)
      end

      it "re-renders the 'edit' template" do
        QuestionformScanProcedure.stub(:find) { mock_questionform_scan_procedure(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested questionform_scan_procedure" do
      QuestionformScanProcedure.stub(:find).with("37") { mock_questionform_scan_procedure }
      mock_questionform_scan_procedure.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the questionform_scan_procedures list" do
      QuestionformScanProcedure.stub(:find) { mock_questionform_scan_procedure }
      delete :destroy, :id => "1"
      response.should redirect_to(questionform_scan_procedures_url)
    end
  end

end
