require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ScanProceduresVgroupsController do

  def mock_scan_procedures_vgroup(stubs={})
    @mock_scan_procedures_vgroup ||= mock_model(ScanProceduresVgroup, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all scan_procedures_vgroups as @scan_procedures_vgroups" do
      ScanProceduresVgroup.stub(:all) { [mock_scan_procedures_vgroup] }
      get :index
      assigns(:scan_procedures_vgroups).should eq([mock_scan_procedures_vgroup])
    end
  end

  describe "GET show" do
    it "assigns the requested scan_procedures_vgroup as @scan_procedures_vgroup" do
      ScanProceduresVgroup.stub(:find).with("37") { mock_scan_procedures_vgroup }
      get :show, :id => "37"
      assigns(:scan_procedures_vgroup).should be(mock_scan_procedures_vgroup)
    end
  end

  describe "GET new" do
    it "assigns a new scan_procedures_vgroup as @scan_procedures_vgroup" do
      ScanProceduresVgroup.stub(:new) { mock_scan_procedures_vgroup }
      get :new
      assigns(:scan_procedures_vgroup).should be(mock_scan_procedures_vgroup)
    end
  end

  describe "GET edit" do
    it "assigns the requested scan_procedures_vgroup as @scan_procedures_vgroup" do
      ScanProceduresVgroup.stub(:find).with("37") { mock_scan_procedures_vgroup }
      get :edit, :id => "37"
      assigns(:scan_procedures_vgroup).should be(mock_scan_procedures_vgroup)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created scan_procedures_vgroup as @scan_procedures_vgroup" do
        ScanProceduresVgroup.stub(:new).with({'these' => 'params'}) { mock_scan_procedures_vgroup(:save => true) }
        post :create, :scan_procedures_vgroup => {'these' => 'params'}
        assigns(:scan_procedures_vgroup).should be(mock_scan_procedures_vgroup)
      end

      it "redirects to the created scan_procedures_vgroup" do
        ScanProceduresVgroup.stub(:new) { mock_scan_procedures_vgroup(:save => true) }
        post :create, :scan_procedures_vgroup => {}
        response.should redirect_to(scan_procedures_vgroup_url(mock_scan_procedures_vgroup))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved scan_procedures_vgroup as @scan_procedures_vgroup" do
        ScanProceduresVgroup.stub(:new).with({'these' => 'params'}) { mock_scan_procedures_vgroup(:save => false) }
        post :create, :scan_procedures_vgroup => {'these' => 'params'}
        assigns(:scan_procedures_vgroup).should be(mock_scan_procedures_vgroup)
      end

      it "re-renders the 'new' template" do
        ScanProceduresVgroup.stub(:new) { mock_scan_procedures_vgroup(:save => false) }
        post :create, :scan_procedures_vgroup => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested scan_procedures_vgroup" do
        ScanProceduresVgroup.stub(:find).with("37") { mock_scan_procedures_vgroup }
        mock_scan_procedures_vgroup.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :scan_procedures_vgroup => {'these' => 'params'}
      end

      it "assigns the requested scan_procedures_vgroup as @scan_procedures_vgroup" do
        ScanProceduresVgroup.stub(:find) { mock_scan_procedures_vgroup(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:scan_procedures_vgroup).should be(mock_scan_procedures_vgroup)
      end

      it "redirects to the scan_procedures_vgroup" do
        ScanProceduresVgroup.stub(:find) { mock_scan_procedures_vgroup(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(scan_procedures_vgroup_url(mock_scan_procedures_vgroup))
      end
    end

    describe "with invalid params" do
      it "assigns the scan_procedures_vgroup as @scan_procedures_vgroup" do
        ScanProceduresVgroup.stub(:find) { mock_scan_procedures_vgroup(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:scan_procedures_vgroup).should be(mock_scan_procedures_vgroup)
      end

      it "re-renders the 'edit' template" do
        ScanProceduresVgroup.stub(:find) { mock_scan_procedures_vgroup(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested scan_procedures_vgroup" do
      ScanProceduresVgroup.stub(:find).with("37") { mock_scan_procedures_vgroup }
      mock_scan_procedures_vgroup.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the scan_procedures_vgroups list" do
      ScanProceduresVgroup.stub(:find) { mock_scan_procedures_vgroup }
      delete :destroy, :id => "1"
      response.should redirect_to(scan_procedures_vgroups_url)
    end
  end

end
