require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SeriesDescriptionMapsController do

  def mock_series_description_map(stubs={})
    @mock_series_description_map ||= mock_model(SeriesDescriptionMap, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all series_description_maps as @series_description_maps" do
      SeriesDescriptionMap.stub(:all) { [mock_series_description_map] }
      get :index
      assigns(:series_description_maps).should eq([mock_series_description_map])
    end
  end

  describe "GET show" do
    it "assigns the requested series_description_map as @series_description_map" do
      SeriesDescriptionMap.stub(:find).with("37") { mock_series_description_map }
      get :show, :id => "37"
      assigns(:series_description_map).should be(mock_series_description_map)
    end
  end

  describe "GET new" do
    it "assigns a new series_description_map as @series_description_map" do
      SeriesDescriptionMap.stub(:new) { mock_series_description_map }
      get :new
      assigns(:series_description_map).should be(mock_series_description_map)
    end
  end

  describe "GET edit" do
    it "assigns the requested series_description_map as @series_description_map" do
      SeriesDescriptionMap.stub(:find).with("37") { mock_series_description_map }
      get :edit, :id => "37"
      assigns(:series_description_map).should be(mock_series_description_map)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created series_description_map as @series_description_map" do
        SeriesDescriptionMap.stub(:new).with({'these' => 'params'}) { mock_series_description_map(:save => true) }
        post :create, :series_description_map => {'these' => 'params'}
        assigns(:series_description_map).should be(mock_series_description_map)
      end

      it "redirects to the created series_description_map" do
        SeriesDescriptionMap.stub(:new) { mock_series_description_map(:save => true) }
        post :create, :series_description_map => {}
        response.should redirect_to(series_description_map_url(mock_series_description_map))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved series_description_map as @series_description_map" do
        SeriesDescriptionMap.stub(:new).with({'these' => 'params'}) { mock_series_description_map(:save => false) }
        post :create, :series_description_map => {'these' => 'params'}
        assigns(:series_description_map).should be(mock_series_description_map)
      end

      it "re-renders the 'new' template" do
        SeriesDescriptionMap.stub(:new) { mock_series_description_map(:save => false) }
        post :create, :series_description_map => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested series_description_map" do
        SeriesDescriptionMap.stub(:find).with("37") { mock_series_description_map }
        mock_series_description_map.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :series_description_map => {'these' => 'params'}
      end

      it "assigns the requested series_description_map as @series_description_map" do
        SeriesDescriptionMap.stub(:find) { mock_series_description_map(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:series_description_map).should be(mock_series_description_map)
      end

      it "redirects to the series_description_map" do
        SeriesDescriptionMap.stub(:find) { mock_series_description_map(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(series_description_map_url(mock_series_description_map))
      end
    end

    describe "with invalid params" do
      it "assigns the series_description_map as @series_description_map" do
        SeriesDescriptionMap.stub(:find) { mock_series_description_map(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:series_description_map).should be(mock_series_description_map)
      end

      it "re-renders the 'edit' template" do
        SeriesDescriptionMap.stub(:find) { mock_series_description_map(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested series_description_map" do
      SeriesDescriptionMap.stub(:find).with("37") { mock_series_description_map }
      mock_series_description_map.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the series_description_maps list" do
      SeriesDescriptionMap.stub(:find) { mock_series_description_map }
      delete :destroy, :id => "1"
      response.should redirect_to(series_description_maps_url)
    end
  end

end
