require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe VitalsController do

  def mock_vital(stubs={})
    @mock_vital ||= mock_model(Vital, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all vitals as @vitals" do
      Vital.stub(:all) { [mock_vital] }
      get :index
      assigns(:vitals).should eq([mock_vital])
    end
  end

  describe "GET show" do
    it "assigns the requested vital as @vital" do
      Vital.stub(:find).with("37") { mock_vital }
      get :show, :id => "37"
      assigns(:vital).should be(mock_vital)
    end
  end

  describe "GET new" do
    it "assigns a new vital as @vital" do
      Vital.stub(:new) { mock_vital }
      get :new
      assigns(:vital).should be(mock_vital)
    end
  end

  describe "GET edit" do
    it "assigns the requested vital as @vital" do
      Vital.stub(:find).with("37") { mock_vital }
      get :edit, :id => "37"
      assigns(:vital).should be(mock_vital)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created vital as @vital" do
        Vital.stub(:new).with({'these' => 'params'}) { mock_vital(:save => true) }
        post :create, :vital => {'these' => 'params'}
        assigns(:vital).should be(mock_vital)
      end

      it "redirects to the created vital" do
        Vital.stub(:new) { mock_vital(:save => true) }
        post :create, :vital => {}
        response.should redirect_to(vital_url(mock_vital))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vital as @vital" do
        Vital.stub(:new).with({'these' => 'params'}) { mock_vital(:save => false) }
        post :create, :vital => {'these' => 'params'}
        assigns(:vital).should be(mock_vital)
      end

      it "re-renders the 'new' template" do
        Vital.stub(:new) { mock_vital(:save => false) }
        post :create, :vital => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vital" do
        Vital.stub(:find).with("37") { mock_vital }
        mock_vital.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :vital => {'these' => 'params'}
      end

      it "assigns the requested vital as @vital" do
        Vital.stub(:find) { mock_vital(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:vital).should be(mock_vital)
      end

      it "redirects to the vital" do
        Vital.stub(:find) { mock_vital(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(vital_url(mock_vital))
      end
    end

    describe "with invalid params" do
      it "assigns the vital as @vital" do
        Vital.stub(:find) { mock_vital(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:vital).should be(mock_vital)
      end

      it "re-renders the 'edit' template" do
        Vital.stub(:find) { mock_vital(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vital" do
      Vital.stub(:find).with("37") { mock_vital }
      mock_vital.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the vitals list" do
      Vital.stub(:find) { mock_vital }
      delete :destroy, :id => "1"
      response.should redirect_to(vitals_url)
    end
  end

end
